intel/intel-extension-for-transformers

examples/optimization/pytorch/huggingface/README.md
fix document typo
clean format
spellcheck
no
=> fix docs format issue

README.md, examples/optimization/pytorch/huggingface/language-modeling/inference/README.md, examples/optimization/pytorch/huggingface/language-modeling/inference/requirements.txt, examples/optimization/pytorch/huggingface/language-modeling/inference/run_gptj.py
add pytorch gptj inference scripts on Xeon® with PyTorch and Intel® Extension for PyTorch.
=> add pytorch gptj inference scripts

examples/optimization/pytorch/huggingface/language-modeling/inference/run_gptj.py
=> add gpt-j max tokens settting

examples/optimization/pytorch/huggingface/language-modeling/inference/run_gptj.py
modify run_gptj.py to setup default params
=> modify run_gptj.py to setup default params

examples/optimization/pytorch/huggingface/language-modeling/inference/README.md, examples/optimization/pytorch/huggingface/language-modeling/inference/run_gptj.py
=> add warmup and greedy to gptj

examples/optimization/pytorch/huggingface/language-modeling/inference/README.md, examples/optimization/pytorch/huggingface/language-modeling/inference/run_bloom.py
Signed-off-by: Wang, Yi A <yi.a.wang@intel.com>
=> add inference case for bloom and update readme

README.md, examples/optimization/pytorch/huggingface/language-modeling/inference/README.md
document
add bloom showcase
document
spell
no
=> add bloom and minor fix

examples/optimization/pytorch/huggingface/language-modeling/chatbot/README.md, examples/optimization/pytorch/huggingface/language-modeling/chatbot/finetune_clm.py
example code change
Refined data load code.
example test pass
```bash
python finetune_clm.py \
--model_name_or_path "decapoda-research/llama-7b-hf" \
--train_file "/path/to/alpaca_data.json" \
--dataset_concatenation \
--per_device_train_batch_size 8 \
--per_device_eval_batch_size 8 \
--gradient_accumulation_steps 1 \
--do_train \
--learning_rate 2e-5 \
--num_train_epochs 3 \
--logging_steps 100 \
--save_total_limit 2 \
--overwrite_output_dir \
--log_level info \
--save_strategy epoch \
--output_dir "./llama_finetuned_model"
```
=> Refined data load code

examples/huggingface/pytorch/text-generation/deployment/README.md, examples/huggingface/pytorch/text-generation/deployment/run_gptj.py
documentation
Refine the Engine gpt-j example README
updated README for Engine gpt-j example
updated README for Engine gpt-j example
No
=> [Engine]Refine the gpt-j example code

intel_extension_for_transformers/backends/neural_engine/executor/src/model.cpp
=> [Engine] Fix typo in model.cpp

workflows/chatbot/inference/generate.py
=> move some operation from main to load_model

workflows/chatbot/fine_tuning/README.md
=> fix symbol.

intel_extension_for_transformers/backends/neural_engine/graph/models/gptneox/gptneox.h, intel_extension_for_transformers/backends/neural_engine/graph/models/gptneox/gptneox_utils.cpp, intel_extension_for_transformers/backends/neural_engine/graph/models/mpt/mpt.h, intel_extension_for_transformers/backends/neural_engine/graph/models/mpt/mpt_utils.cpp
=> fix nctx and scratch buffer for neox and mpt

examples/huggingface/pytorch/question-answering/deployment/squad/MLperf_example/README.md, examples/huggingface/pytorch/question-answering/deployment/squad/MLperf_example/accuracy-squad.py, examples/huggingface/pytorch/question-answering/deployment/squad/MLperf_example/create_squad_data.py, examples/huggingface/pytorch/question-answering/deployment/squad/MLperf_example/datasets/gen_data.py, examples/huggingface/pytorch/question-answering/deployment/squad/MLperf_example/utils_qa.py, examples/huggingface/pytorch/text-classification/deployment/mrpc/distilbert_base_uncased/README.md, examples/huggingface/pytorch/text-classification/deployment/mrpc/roberta_base/README.md
Add Mlperf example minilm_l8 data generate and accuracy test
=> Add Mlperf example minilm_l8 data generate and accuracy test

examples/.config/pytorch_optimize.json
bug fix
fix benchmark bug of weight-only
=> fix benchmark bug of weight-only

intel_extension_for_transformers/backends/neural_engine/graph/application/ChatSTARCODER/CMakeLists.txt, intel_extension_for_transformers/backends/neural_engine/graph/application/ChatSTARCODER/main_starcoder.cpp, intel_extension_for_transformers/backends/neural_engine/graph/application/ChatSTARCODER/quant_starcoder.cpp, intel_extension_for_transformers/backends/neural_engine/graph/core/ne_layers.c, intel_extension_for_transformers/backends/neural_engine/graph/models/model_utils/model_files.h, intel_extension_for_transformers/backends/neural_engine/graph/models/model_utils/model_types.h, intel_extension_for_transformers/backends/neural_engine/graph/models/starcoder/CMakeLists.txt, intel_extension_for_transformers/backends/neural_engine/graph/models/starcoder/starcoder.cpp, intel_extension_for_transformers/backends/neural_engine/graph/models/starcoder/starcoder.h, intel_extension_for_transformers/backends/neural_engine/graph/models/starcoder/starcoder_utils.cpp, intel_extension_for_transformers/backends/neural_engine/graph/scripts/convert_starcoder.py
- starcoder with jblas
- fix int overflow
no
=> update starcoder with jblas

workflows/chatbot/inference/README.md, workflows/chatbot/inference/generate.py
=> add perf stats in predict_stream

intel_extension_for_transformers/backends/neural_engine/graph/README.md, intel_extension_for_transformers/backends/neural_engine/graph/application/ChatDOLLY/CMakeLists.txt, intel_extension_for_transformers/backends/neural_engine/graph/application/ChatDOLLY/main_dolly.cpp, intel_extension_for_transformers/backends/neural_engine/graph/application/ChatDOLLY/quant_dolly.cpp, intel_extension_for_transformers/backends/neural_engine/graph/models/gptneox/gptneox.h, intel_extension_for_transformers/backends/neural_engine/graph/scripts/convert_dolly.py
feature 
enable dolly-v2-3b cpp model
=> enable dolly-v2-3b cpp model

examples/huggingface/pytorch/translation/quantization/run_translation.py, intel_extension_for_transformers/optimization/trainer.py
bug fix
No API changed
Fixed the latest version of transformers 
Run summarization task successfully in transformers >4.30 
Local tested
=> Fixed summarization example issue for new version transformers

examples/.config/pytorch_optimize.json, examples/huggingface/pytorch/text2text-generation/run_benchmark.sh, examples/huggingface/pytorch/text2text-generation/run_seq2seq_generation.py, examples/huggingface/pytorch/text2text-generation/run_tuning.sh, intel_extension_for_transformers/optimization/modeling/modeling_seq2seq.py
=> Fixed typo for text2text example test script

workflows/chatbot/fine_tuning/README.md, workflows/chatbot/fine_tuning/instruction_tuning_pipeline/data_utils.py
fix read HuggingFaceH4/oasst1_en dataset issue
=> fix oasst dataset issue.

intel_extension_for_transformers/optimization/modeling/modeling_base_seq2seq.py
bug fix
No API changed
Fixed error of loading model for text2text generation task
load model and convert to jit model successfully for text2text generation task model.
Local tested
=> Fixed error of loading model for text2text generation task

.github/workflows/format_scan.yml, .github/workflows/py-spelling.yml
remove echo github params
remove echo '${{ toJSON(github) }}'
No
pre-ci
No
=> [pre-ci] remove echo github params

intel_extension_for_transformers/backends/neural_engine/graph/README.md, intel_extension_for_transformers/backends/neural_engine/graph/scripts/convert_starcoder.py
amend starcoder input model path
=> amend starcoder input model path

neural_chat/pipeline/plugins/intent_detector/IntentDetection.py, neural_chat/pipeline/plugins/memory/memory.py, neural_chat/pipeline/plugins/prompts/prompt.py
Add the local prompt generator and the memory part
=> add prompt generator and memory

examples/huggingface/pytorch/language-modeling/quantization/run_clm_no_trainer.py
feature for example
add eval_func for alpha tuning and support latest weight-only loading
ext test pass
local test
=> add eval_func for alpha tuning and new load for weight-only

neural_chat/chatbot.py, neural_chat/models/base_model.py, neural_chat/pipeline/plugins/intent_detector/IntentDetection.py, neural_chat/pipeline/plugins/prompts/prompt.py, neural_chat/pipeline/plugins/retrievers/indexing/DocumentParse.py, neural_chat/pipeline/plugins/retrievers/ranker/__init__.py, neural_chat/pipeline/plugins/retrievers/retriever/__init__.py, neural_chat/pipeline/plugins/retrievers/retriever/colbert.py, neural_chat/pipeline/plugins/retrievers/retriever/langchain_retriever.py
=> add register

workflows/compression_aware_training/requirements.txt, workflows/hf_finetuning_and_inference_nlp/requirements.txt
=> Updated 3rd party versions for compliance

.github/workflows/chatbot-inference-llama-2-7b-chat-hf.yml, .github/workflows/chatbot-test.yml, workflows/chatbot/inference/docker/Dockerfile, workflows/chatbot/inference/generate.py
CI
add inference test for llama-2-7b-chat-hf
=> add inference test for llama-2-7b-chat-hf

examples/huggingface/pytorch/text-generation/quantization/run_generation.py
to enhance trace.
neural-chat-7b-v1-1 need inference 1 time before traceing.
=> Enhance text-generation example

workflows/chatbot/fine_tuning/instruction_tuning_pipeline/finetune_clm.py
=> remove hard print.

examples/huggingface/pytorch/language-modeling/quantization/README.md, examples/huggingface/pytorch/language-modeling/quantization/requirements.txt, examples/huggingface/pytorch/language-modeling/quantization/run_clm_no_trainer.py
example
Support PEFT model
Can load peft model
https://github.com/huggingface/peft.git
=> Support PEFT model

neural_chat/README.md
documentation change
This PR is used to refine the neuralchat documentation
=> NeuralChat README refinement

examples/huggingface/pytorch/language-modeling/quantization/README.md, examples/huggingface/pytorch/language-modeling/quantization/requirements.txt, examples/huggingface/pytorch/language-modeling/quantization/run_clm_no_trainer.py, neural_chat/__init__.py, neural_chat/chatbot.py, neural_chat/cli/cli_commands.py, neural_chat/config.py, neural_chat/models/base_model.py, neural_chat/pipeline/plugins/audio/__init__.py, neural_chat/pipeline/plugins/audio/asr.py, neural_chat/pipeline/plugins/audio/asr_chinese.py, neural_chat/pipeline/plugins/audio/tts.py, neural_chat/pipeline/plugins/audio/tts_chinese.py, neural_chat/pipeline/plugins/intent_detector/__init__.py, neural_chat/pipeline/plugins/intent_detector/intent_detection.py, neural_chat/pipeline/plugins/security/safety_checker.py, neural_chat/pipeline/plugins/security/sensitive_checker.py, neural_chat/plugins.py, neural_chat/requirements.txt, neural_chat/tests/api/test_chatbot_build_api.py, neural_chat/utils/docdoct.py, neural_chat/utils/dotdict.py, workflows/chatbot/fine_tuning/README.md, workflows/chatbot/fine_tuning/instruction_tuning_pipeline/data_utils.py, workflows/chatbot/fine_tuning/instruction_tuning_pipeline/eval_utils.py, workflows/chatbot/fine_tuning/instruction_tuning_pipeline/finetune_clm.py
feature
API changed
Update NeuralChat plugins related API
Users can enable, disable, configure plugins easily using NeuralChat new API.
Unit test and example test.
No.
=> Update NeuralChat plugins API

neural_chat/chatbot.py, neural_chat/config.py, neural_chat/models/base_model.py, neural_chat/pipeline/inference/inference.py, neural_chat/requirements.txt, neural_chat/tests/optimization/test_optimization.py
Added bitsandbytes support in NeuralChat optimization and supported inference on NV GPU device.
Added bitsandbytes support in NeuralChat optimization and supported inference on NV GPU device.
pass UT
UT
bitsandbytes library dependency introduced
=> Added bitsandbytes support in NeuralChat optimization and supported inference on NV GPU device.

workflows/chatbot/fine_tuning/instruction_tuning_pipeline/finetune_clm.py
fix double remove dataset columns when concatenation
=> fix double remove issue.

examples/huggingface/pytorch/code-generation/quantization/README.md, examples/huggingface/pytorch/code-generation/quantization/makefile
improve readme.
1. change the wrong installation
2. mbpp python dataset is not the best choice for test multiple-lua tasks.
=> Improve starcoder README

workflows/chatbot/fine_tuning/instruction_tuning_pipeline/finetune_clm.py
mpt not support left padding especially when training
=> fix mpt not support left padding issue.

intel_extension_for_transformers/llm/runtime/graph/models/starcoder/starcoder_utils.cpp
=> fix starcoder quantization bug

workflows/chatbot/fine_tuning/docker/Dockerfile, workflows/chatbot/inference/docker/Dockerfile, workflows/chatbot/inference/generate.py
=> return correct input len without pad to user

intel_extension_for_transformers/llm/runtime/graph/README.md
documentation 
Refine reademe of llm runtime
n/a
n/a
n/a
=> Refine reademe of llm runtime

.github/workflows/chatbot-finetune-mpt-7b-chat-hpu.yml, .github/workflows/chatbot-test.yml
CI test for finetuning mpt-7b-chat with hpu
=> add finetuning test for mpt-7b-chat with hpu

workflows/chatbot/inference/checkpoint_utils.py, workflows/chatbot/inference/docker/0001-fix-lm-head-overriden-issue-move-it-from-checkpoint-.patch, workflows/chatbot/inference/docker/Dockerfile, workflows/chatbot/inference/generate.py
=> llama 70b AutoTP inference

.github/workflows/chatbot-inference-llama-2-7b-chat-hf-hpu.yml, .github/workflows/chatbot-inference-mpt-7b-chat-hpu.yml, .github/workflows/chatbot-test.yml
CI test for  llama-2-7b-chat-hf with hpu
=> add inference test for llama-2-7b-chat-hf and mpt-7b-chat with hpu

.github/workflows/copyright_check.yml, .github/workflows/cpp-graph-test.yml, .github/workflows/deploy-test.yml, .github/workflows/llm-test.yml, .github/workflows/optimize-test.yml
bugfix
update docker clean mechanism
no clean permission issues
CI
no
=> update docker clean

intel_extension_for_transformers/neural_chat/pipeline/tools/cut_video.py, intel_extension_for_transformers/neural_chat/ui/basic_frontend/fastchat/serve/cli.py, workflows/chatbot/demo/basic_frontend/fastchat/serve/cli.py, workflows/chatbot/fine_tuning/instruction_tuning_pipeline/finetune_clm.py, workflows/chatbot/inference/backend/chat/model_worker.py, workflows/chatbot/inference/memory_controller/chat_with_memory.py
bug fix
Fix checkmarx security issues to avoid code inject security issues.
The checkmarx security issues can be fixed.
No.
=> Fix checkmarx security issues

intel_extension_for_transformers/neural_chat/pipeline/plugins/audio/asr.py
optimization
This provides a way other than librosa.load or HuggingFace Dataset wrapper to load audio from audio path to librosa-like float32 waveform array, and extremely decreases the time of ASR process
As mentioned above. No other risk since it will fallback to the original one if there is an exception
Run ASR UT
None
=> optimize ASR audio to waveform loading

.github/workflows/unit-test-engine.yml, .github/workflows/unit-test-optimize.yml, intel_extension_for_transformers/llm/finetuning/data_utils.py, intel_extension_for_transformers/llm/finetuning/eval_utils.py, intel_extension_for_transformers/llm/finetuning/finetuning.py, intel_extension_for_transformers/llm/inference/inference.py, intel_extension_for_transformers/llm/quantization/optimization.py, intel_extension_for_transformers/neural_chat/__init__.py, intel_extension_for_transformers/neural_chat/chatbot.py, intel_extension_for_transformers/neural_chat/config.py, intel_extension_for_transformers/neural_chat/tests/finetuning/test_finetuning.py, intel_extension_for_transformers/neural_chat/tests/optimization/test_optimization.py
Added QLoRA support in NeuralChat finetuning and refined NeuralChat optimization API.
API changed
Added QLoRA support in NeuralChat finetuning and refined NeuralChat optimization API.
pass UT
UT
=> Added QLoRA support in NeuralChat finetuning and refined NeuralChat optimization API.

intel_extension_for_transformers/neural_chat/README.md, intel_extension_for_transformers/neural_chat/examples/retrieval/README.md, intel_extension_for_transformers/neural_chat/examples/retrieval/retrieval_chat.py
Update the readme for RAG example and neuralchat readme
=> update rag readme

.github/workflows/chatbot-inference-llama-2-7b-chat-hf-hpu.yml, .github/workflows/chatbot-inference-llama-2-7b-chat-hf.yml, .github/workflows/chatbot-inference-mpt-7b-chat-hpu.yml, .github/workflows/chatbot-inference-mpt-7b-chat.yml
fix docker image build dir for inference
=> fix docker image build dir for inference

examples/huggingface/pytorch/language-modeling/inference/run_clm_no_trainer.py, examples/huggingface/pytorch/language-modeling/quantization/run_clm_no_trainer.py, examples/huggingface/pytorch/text2text-generation/run_seq2seq_generation.py, examples/huggingface/pytorch/text2text-generation/run_seq2seq_generation_bart.py, workflows/chatbot/fine_tuning/instruction_tuning_pipeline/finetune_clm.py
bug fix
No API changed
Fixed import issue for seq2seq examples
Run text2text task examples successfully
Local tested
=> Fixed import issue for seq2seq examples

.github/workflows/script/formatScan/nlp_dict.txt, README.md, intel_extension_for_transformers/neural_chat/README.md
Add latest news "NeuralChat" in main readme
=> Add latest update in readme

intel_extension_for_transformers/neural_chat/examples/retrieval/README.md, intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/README.md, intel_extension_for_transformers/neural_chat/pipeline/plugins/security/README.md
=> add README for retrieval, safety checker plugins

docs/build_docs/build.sh, docs/build_docs/source/_templates/footer.html, docs/build_docs/source/_templates/layout.html, docs/build_docs/source/conf.py, docs/build_docs/source/index.rst, docs/examples.md
feature of documentation
1. IT ask to support adobe analytics in online doc.
2. fix anchor issues in examples
3. add repo link in list menu
=> support adobe analytics, fix anchor issues in examples, add repo link in list

intel_extension_for_transformers/llm/runtime/graph/core/layers/inner_product.cpp, intel_extension_for_transformers/llm/runtime/graph/core/layers/ip_fusion_ffn.cpp, intel_extension_for_transformers/llm/runtime/graph/core/layers/ip_fusion_qkv.cpp, intel_extension_for_transformers/llm/runtime/graph/core/layers/jblas_common.hpp
fix the crash of vnni 
llama-7b
=> [Cpp Graph]fix q8 pern QKV fusion of vnni

.github/workflows/chatbot-test.yml, .github/workflows/script/chatbot/hpu_check/readme, .github/workflows/script/chatbot/hpu_check/run_check.sh, .github/workflows/script/chatbot/hpu_check/to_hpu.py
add a pre-script to check hpu availability before each workflow job
=> Hpu pre script

intel_extension_for_transformers/neural_chat/requirements.txt
=> add xlsx requirements for neuralchat

examples/huggingface/pytorch/text-to-image/deployment/stable_diffusion/README.md
=>  Update SD README.md

.github/workflows/script/formatScan/clangformat.sh, intel_extension_for_transformers/llm/runtime/graph/application/main_run.cpp, intel_extension_for_transformers/llm/runtime/graph/core/ne_layers.c, intel_extension_for_transformers/llm/runtime/graph/core/ne_layers.h, intel_extension_for_transformers/llm/runtime/graph/core/parallel_context.cpp, intel_extension_for_transformers/llm/runtime/graph/core/parallel_context.h, intel_extension_for_transformers/llm/runtime/graph/models/bloom/bloom.cpp, intel_extension_for_transformers/llm/runtime/graph/models/chatglm/chatglm1.cpp, intel_extension_for_transformers/llm/runtime/graph/models/chatglm/chatglm1_utils.cpp, intel_extension_for_transformers/llm/runtime/graph/models/chatglm/chatglm2.cpp, intel_extension_for_transformers/llm/runtime/graph/models/chatglm/chatglm2.h, intel_extension_for_transformers/llm/runtime/graph/models/chatglm/chatglm2_utils.cpp, intel_extension_for_transformers/llm/runtime/graph/models/falcon/falcon.cpp, intel_extension_for_transformers/llm/runtime/graph/models/gptj/gptj.cpp, intel_extension_for_transformers/llm/runtime/graph/models/gptneox/gptneox.cpp, intel_extension_for_transformers/llm/runtime/graph/models/model_utils/arg_parse.cpp, intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_files.h, intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_types.h, intel_extension_for_transformers/llm/runtime/graph/models/model_utils/quant_config.h, intel_extension_for_transformers/llm/runtime/graph/models/mpt/mpt.cpp, intel_extension_for_transformers/llm/runtime/graph/models/starcoder/starcoder.cpp
fix broken format
In addition, a kv-cache checking bug introduced in #179 is fixed in this PR.
=> [CPP Graph] fix broken format

intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_utils.h, intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_weight_compression.h, intel_extension_for_transformers/llm/library/jblas/jblas/kernel_ref.h, intel_extension_for_transformers/llm/library/jblas/jblas/kernel_wrapper.h, intel_extension_for_transformers/llm/runtime/graph/core/layers/inner_product.cpp, intel_extension_for_transformers/llm/runtime/graph/core/layers/ip_fusion_ffn.cpp, intel_extension_for_transformers/llm/runtime/graph/core/layers/ip_fusion_qkv.cpp, intel_extension_for_transformers/llm/runtime/graph/core/layers/jblas_common.hpp, intel_extension_for_transformers/llm/runtime/graph/core/ne_layers.c, intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_utils.cpp
add q4 per channel quant and kernel.
fix q4 quant low accuracy bug.
llama-7b gptj-6b
=> Q4 perchannel

.pre-commit-config.yaml, workflows/chatbot/inference/memory_controller/chat_with_memory.py
add debug-statements checker
depend on pre-commit ci
no
no
no
=> add debug-statements checker

.github/workflows/cpp-graph-test.yml, .github/workflows/script/formatScan/pylint.sh, .github/workflows/script/models/cpp_graph_inference.sh, intel_extension_for_transformers/transformers/modeling/modeling_base_seq2seq.py, workflows/chatbot/inference/backend/fastrag/fastrag_service.py
=> update pylint and cpp graph

.github/workflows/chatbot-finetune-mpt-7b-chat.yml
print logs even previous ft step fails.
=> enhance mpi logging

README.md
documentation
add icon and refine document
n/a
n/a
n/a
=> add icons to main page

intel_extension_for_transformers/llm/runtime/graph/application/main_run.cpp, intel_extension_for_transformers/llm/runtime/graph/models/gptj/gptj.cpp, intel_extension_for_transformers/llm/runtime/graph/models/llama/llama.cpp
- This is another fix for #179
- Configure Vcur dim correctly for q4_0 gptj
- Remove extra rope for q4_0 llama
- In addition, generation of `logits.txt` is removed to avoid unnecessary disk usage.
N/A
Model quantization for testing:
- q40 quant params: `--bits 4 --nthread 10`
- q4j quant params:  `--bits 4 --compute_type int8 --block_size 128 --nthread 10`
<details>
<summary>Interference result:</summary>
```bash
set -ex
rm -rf bin && cmake .. -GNinja -DNE_BUILD_TESTS=ON -DNE_PROFILING=OFF -DCMAKE_BUILD_TYPE=Release && ninja run_gptj && env ENGINE_PROFILING=1 numactl -m 1 -C 56-111 bin/run_gptj -m /home_local/dingyi/data/gpt-j-6B-pr270-q40.bin --seed 1234 -t 56 -b 2048 -c 2048 -n 128 -p "$GIRL_PROMPT" --memory-auto
rm -rf bin && cmake .. -GNinja -DNE_BUILD_TESTS=ON …
```
=> [CPP Graph] Fix q4_0 gptj with MHA fusion enabled

intel_extension_for_transformers/llm/runtime/deprecated/CMakeLists.txt
- Disable building OneDNN examples & tests
N/A
pre-commit
N/A
=> Disable building OneDNN examples & tests

.github/workflows/script/models/calculate_percentage.py
bugfix
update calculate percentage method
=> update calculate method

intel_extension_for_transformers/llm/runtime/graph/CMakeLists.txt, intel_extension_for_transformers/llm/runtime/graph/application/main_run.cpp, intel_extension_for_transformers/llm/runtime/graph/models/bloom/bloom.cpp, intel_extension_for_transformers/llm/runtime/graph/models/gptneox/gptneox.cpp
=> fix the bloom and dolly ffn fusion error (#284)

.github/workflows/script/formatScan/nlp_dict.txt, README.md
=> fix readme model path

examples/huggingface/pytorch/text-generation/quantization/run_generation.py
llama model tokenizer config has the wrong tokenizer class name, it caused we couldn't use the AutoTokenizer to get the correct tokenizer.
https://jira.devtools.intel.com/browse/NLPTOOLKIU-856
=> Fix llama model tokenizer issue

.github/workflows/script/formatScan/nlp_dict.txt, README.md
add invitation of channel
n/a
n/a
n/a
n/a
=> add invitation of channel

intel_extension_for_transformers/neural_chat/models/base_model.py, intel_extension_for_transformers/neural_chat/pipeline/plugins/security/safety_checker.py
Bug fix for security checker. 
No api changed. 
With security checker on, response is none due to bug. 
no. 
no.
=> Fix None response bug for security checker

intel_extension_for_transformers/llm/runtime/graph/README.md, intel_extension_for_transformers/llm/runtime/graph/application/common.h, intel_extension_for_transformers/llm/runtime/graph/core/layers/mha_dense.cpp, intel_extension_for_transformers/llm/runtime/graph/models/chatglm/chatglm2_utils.cpp
fix the compilation errors of cpp graph on Windows.
update readme for Windows compilation guide.
Compilation only.
=> [Graph] windows build

examples/huggingface/pytorch/question-answering/deployment/squad/length_adaptive_transformer/run_qa.py, examples/huggingface/pytorch/question-answering/deployment/squad/length_adaptive_transformer/trainer_qa.py, examples/huggingface/pytorch/question-answering/dynamic/run_qa.py, examples/huggingface/pytorch/question-answering/dynamic/trainer_qa.py
due to ITREX adopt to transformers 4.33.1, update the QuLAT example
JIRA ticket: https://jira.devtools.intel.com/browse/NLPTOOLKIU-860
=> update QuLAT example transformers version

intel_extension_for_transformers/neural_chat/models/base_model.py, intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/retrieval_agent.py
=> fix bugs in RAG code for converting the prompt

intel_extension_for_transformers/neural_chat/tests/api/test_inference.py
=> add ut to override parm PR

intel_extension_for_transformers/neural_chat/README.md, intel_extension_for_transformers/neural_chat/docs/full_notebooks.md
This PR shows the selected notebook in main readme and the full notebook in separate readme.
=> Refine NeuralChat notebook

examples/huggingface/tensorflow/multiple-choice/quantization/run_swag.py
bug fix
fix distributed_state not found error
fix distributed_state not found error
CI test
None
=> fix distributed_state not found error

intel_extension_for_transformers/llm/runtime/deprecated/__init__.py, intel_extension_for_transformers/neural_chat/examples/tts_finetuning/inference.py, intel_extension_for_transformers/neural_chat/pipeline/plugins/audio/utils/cut_video.py, intel_extension_for_transformers/neural_chat/pipeline/plugins/audio/utils/video_to_wav.py, setup.py
bugfix
fix checkmar static code scan issues
none
CI & Checkmarx scan
no
=> fix checkmarx issue

examples/huggingface/pytorch/text-generation/quantization/build_env.sh
=> Update text-generation build_env.sh

intel_extension_for_transformers/neural_chat/README.md
fix borken link in documentation 
update  intel_extension_for_transformers/neural_chat/README.md
click the link, it goes to the destination
=> fix broken link in document

intel_extension_for_transformers/llm/runtime/graph/README.md
Doc update
Update ChatGLM-6B to README.md
N/A
=> Update ChatGLM-6B to README.md

examples/.config/pytorch_optimize.json, examples/huggingface/pytorch/text-generation/quantization/build_env.sh, examples/huggingface/pytorch/text-generation/quantization/run_benchmark.sh, examples/huggingface/pytorch/text-generation/quantization/run_tuning.sh
update text-generation scripts for extension test.
=> update text-generation scripts

.github/workflows/unit-test-neuralchat.yml
add the scope of the UT test.
fix the issue of ut test not activate
=> fix ut test config for neural chat 

.github/workflows/script/formatScan/nlp_dict.txt, README.md, docs/contributions.md
docs
update documentation and mailto
none
spellcheck
no
=> update publication and mailto

.github/workflows/script/formatScan/nlp_dict.txt
=> add check dict

.github/workflows/chatbot-test.yml, .github/workflows/script/formatScan/nlp_dict.txt, README.md, docs/publication.md
**temperately disable HPU test since machines all unavailable**
=> Temperately disable hpu test

.github/workflows/script/formatScan/nlp_dict.txt, README.md
=> fix discord link

examples/huggingface/pytorch/language-modeling/quantization/run_clm_no_trainer.py
fix dtype issue for chatGLM example for woq
pass extension test
passed local test
=> fix dtype issue for chatGLM example

intel_extension_for_transformers/neural_chat/docker/inference/README.md
=> fix neuralchat docker readme

intel_extension_for_transformers/neural_chat/requirements_cpu.txt
Install torch and torch audio CPU version in neural-chat requirements_cpu.txt.
Update neural-chat requirements_cpu.txt
No.
set up a new enviroment
pip install -r requirements_cpu.txt
1. check the install package is cpu version.
2. check a neural-example runs successfully
=> Xwang update doc

intel_extension_for_transformers/neural_chat/docs/notebooks/setup_text_chatbot_service_on_spr.ipynb, intel_extension_for_transformers/neural_chat/examples/textbot/backend/textbot.yaml, intel_extension_for_transformers/neural_chat/requirements.txt
Refined Jupyter notebook and example for setting up an end to end text chatbot
=> Refined documentation for setting up an end to end text chatbot

examples/huggingface/pytorch/text-generation/quantization/README.md, examples/huggingface/pytorch/text-generation/quantization/run_benchmark.sh
=> improve text-generaion example typing

.github/workflows/chatbot-finetune-mpt-7b-chat.yml, .github/workflows/chatbot-inference-llama-2-7b-chat-hf.yml, .github/workflows/chatbot-inference-mpt-7b-chat.yml, intel_extension_for_transformers/neural_chat/docker/Dockerfile
=> improve CI

examples/huggingface/pytorch/language-modeling/pruning/README.md, examples/huggingface/pytorch/language-modeling/pruning/run_clm_sparsegpt.py, examples/huggingface/pytorch/language-modeling/pruning/scripts/run_llm_sparseGPT.sh
bug fix or documentation or others
=> refine sparseGPT example & scripts

.github/workflows/chatbot-test.yml, .github/workflows/unit-test-neuralchat.yml
refine chatobot CI trigger condition
=> refine trigger condition

intel_extension_for_transformers/llm/runtime/graph/README.md, intel_extension_for_transformers/llm/runtime/graph/core/README.md
add readme for LLM runtime kernels
=> add readme for llm kernels

intel_extension_for_transformers/llm/runtime/graph/README.md
=> Update README.md for llama2 70B

intel_extension_for_transformers/neural_chat/docs/full_notebooks.md
Doc
Add notebook entry
Add entry to notebook example of building Talking Bot on Windows PC
None
None
=> add notebook entry

intel_extension_for_transformers/neural_chat/README.md
Simplify NeuralChat document and align the notebook description
=> Refine Chatbot readme

workflows/chatbot/fine_tuning/dpo_pipeline/requirements.txt
remove denpendency of fairscale
=> remove denpendency of fairscale.

intel_extension_for_transformers/neural_chat/docs/notebooks/amp_optimization_on_spr.ipynb, intel_extension_for_transformers/neural_chat/docs/notebooks/build_chatbot_on_icx.ipynb, intel_extension_for_transformers/neural_chat/docs/notebooks/build_chatbot_on_nv_a100.ipynb, intel_extension_for_transformers/neural_chat/docs/notebooks/build_chatbot_on_spr.ipynb, intel_extension_for_transformers/neural_chat/docs/notebooks/build_chatbot_on_xpu.ipynb, intel_extension_for_transformers/neural_chat/docs/notebooks/customize_chatbot_with_finetuned_models.ipynb, intel_extension_for_transformers/neural_chat/docs/notebooks/customize_chatbot_with_optimized_models.ipynb, intel_extension_for_transformers/neural_chat/docs/notebooks/deploy_chatbot_on_icx.ipynb, intel_extension_for_transformers/neural_chat/docs/notebooks/deploy_chatbot_on_nv_a100.ipynb, intel_extension_for_transformers/neural_chat/docs/notebooks/deploy_chatbot_on_spr.ipynb, intel_extension_for_transformers/neural_chat/docs/notebooks/deploy_chatbot_on_xpu.ipynb, intel_extension_for_transformers/neural_chat/docs/notebooks/finetuning_on_nv_a100.ipynb, intel_extension_for_transformers/neural_chat/docs/notebooks/setup_talking_chatbot_service_on_spr.ipynb, intel_extension_for_transformers/neural_chat/docs/notebooks/setup_text_chatbot_service_on_spr.ipynb, intel_extension_for_transformers/neural_chat/docs/notebooks/single_node_finetuning_on_spr.ipynb, intel_extension_for_transformers/neural_chat/docs/notebooks/weight_only_optimization_on_nv_a100.ipynb, intel_extension_for_transformers/neural_chat/models/neuralchat_model.py
bug fix
Fix double import issue and update pip install itrex
Double import issue fixed.
No.
=> Fix double import issue and update pip install itrex

README.md, intel_extension_for_transformers/neural_chat/docker/Dockerfile
bugfix
build from source in develop mode is not working, need to install with C++ compile.
pip install -v or python setup.py install works fine
CI
NO
=> fix install from source

intel_extension_for_transformers/llm/quantization/utils.py, tests/test_quantization.py, tests/test_weight_only.py
bug fix
No API changed
Fixed bug for woq with AWQ due to not set calib_iters if calib_dataloader is not None.
=> Fixed bug for woq with AWQ

examples/huggingface/pytorch/question-answering/dynamic/requirements.txt, examples/huggingface/pytorch/question-answering/pruning/basic_magnitude/requirements.txt, examples/huggingface/pytorch/question-answering/pruning/longformer_triviaqa/requirements.txt, examples/huggingface/pytorch/summarization/quantization/requirements.txt, examples/huggingface/pytorch/text-classification/cascade-models/requirements.txt, examples/huggingface/pytorch/text-classification/new_pruning/requirements.txt, examples/huggingface/pytorch/text-classification/orchestrate_optimizations/requirements.txt, examples/huggingface/pytorch/text-classification/pruning/requirements.txt, examples/huggingface/pytorch/text-classification/quantization/ptq/requirements.txt, examples/huggingface/pytorch/text-classification/quantization/qat/requirements.txt, examples/huggingface/pytorch/text-classification/quantization/requirements.txt, examples/huggingface/pytorch/token-classification/quantization/requirements.txt, examples/huggingface/pytorch/translation/quantization/requirements.txt, intel_extension_for_transformers/neural_chat/examples/instruction_tuning/requirements.txt, intel_extension_for_transformers/neural_chat/requirements.txt, intel_extension_for_transformers/neural_chat/requirements_cpu.txt, intel_extension_for_transformers/neural_chat/requirements_hpu.txt, intel_extension_for_transformers/neural_chat/requirements_pc.txt, intel_extension_for_transformers/neural_chat/requirements_xpu.txt, intel_extension_for_transformers/neural_chat/ui/textbot/requirements.txt, requirements.txt, workflows/hf_finetuning_and_inference_nlp/requirements.txt
temperately restrain component version until we adapt to the latest
=> restrain langchain version

intel_extension_for_transformers/llm/runtime/graph/CMakeLists.txt, intel_extension_for_transformers/llm/runtime/graph/__init__.py, intel_extension_for_transformers/llm/runtime/graph/application/CMakeLists.txt, intel_extension_for_transformers/llm/runtime/graph/application/main_pybind.cpp, setup.py
related issue: https://github.com/intel/intel-extension-for-transformers/issues/411
By default, `generate` does not use the history commands each time it is run
```bash
['Once upon a time, a little girl named Alice was dreaming of her future. She dreamed about an exciting adventure and she would like to share it with all you guys! So join the cute']
['Once upon a time, a little girl was born and she grew into the most beautiful woman in this whole world.\nEvery day we can see her everywhere; on TV commercials or ads for']
['Once upon a time, a little girl was born.\nWhen she turned 18 months old her mother took the young woman and showed her to our Lord Jesus Christ in church one Sunday morning as']
['Once upon a time, a little girl named Emily was born and grew up in the United States. …
```
=> reinit cpp model and infinite text generation

.github/workflows/chatbot-finetune-mpt-7b-chat.yml, .github/workflows/chatbot-inference-llama-2-7b-chat-hf.yml, .github/workflows/chatbot-inference-mpt-7b-chat.yml
neuralchat docker build need input of ${REPO} to fit with fork repo
=> fix chatbot docker build repo input

tests/requirements.txt
remaining torch version restrain in tests/requirements
=> update tests requirement of pytorch

intel_extension_for_transformers/neural_chat/requirements_cpu.txt, intel_extension_for_transformers/neural_chat/requirements_hpu.txt, intel_extension_for_transformers/neural_chat/requirements_pc.txt, intel_extension_for_transformers/neural_chat/requirements_xpu.txt, requirements.txt
(1) update setuptools for docker build image
(2) update langchain to solve CVE
=> update requirement for docker

docker/Dockerfile_code_gen, docker/docker-compose.yml, examples/huggingface/pytorch/code-generation/quantization/requirements.txt, requirements.txt, tests/requirements.txt
add docker with lm-eval for code-generation. @VincyZhang  @kevinintel 
```
python run_generation.py     --model bigcode/starcoderbase     --output_dir "./saved_results"     --quantize     --sq     --alpha 0.7      --ipex     --calib_iters 500     --calib_batch_size 1     --dataset "mbpp"     --calib_split "test" --int8 --accuracy --batch_size 20 --n_samples 20 --allow_code_execution --temperature 0.2 --do_sample
python run_generation.py     --model bigcode/starcoderbase --accuracy --batch_size 20 --n_samples 20 --allow_code_execution --temperature 0.2 --do_sample
python run_generation.py     --model bigcode/starcoderbase   --int8  --output_dir "./saved_results"  --accuracy --batch_size 20 --n_samples 20 --allow_code_execution --temperature 0.2 --do_sample
python run_generation.py …
```
=> add docker for code-generation

examples/huggingface/onnxruntime/speech-recognition/quantization/README.md, examples/huggingface/onnxruntime/speech-recognition/quantization/requirements.txt, examples/huggingface/onnxruntime/speech-recognition/quantization/run_audio_inference.sh, examples/huggingface/onnxruntime/speech-recognition/quantization/run_whisper.py
example
Add audio sample inference code for ONNX whisper model
=> Add audio sample inference code for ONNX whisper model

examples/huggingface/onnxruntime/speech-recognition/quantization/README.md, examples/huggingface/onnxruntime/speech-recognition/quantization/requirements.txt, examples/huggingface/onnxruntime/speech-recognition/quantization/run_benchmark.sh, examples/huggingface/onnxruntime/speech-recognition/quantization/run_whisper.py
add example
Add INT4 ONNX whisper example 
=> Add INT4 ONNX whisper example 

examples/huggingface/pytorch/code-generation/quantization/README.md, examples/huggingface/pytorch/code-generation/quantization/run_generation.py, intel_extension_for_transformers/transformers/modeling/gpt_bigcode/modeling_gpt_bigcode.py
modify the model_gpt_bigcode.py to make mha fusion.
update benchmark info by token.
remaining to do, will update ipex installation after 2.1 release.
=> Support starcoder MHA fusion

intel_extension_for_transformers/transformers/modeling/modeling_map.py
=> fix AutoModelForCausalLM mapping

docker/Dockerfile_code_gen, intel_extension_for_transformers/llm/finetuning/data_utils.py, intel_extension_for_transformers/llm/finetuning/finetuning.py, intel_extension_for_transformers/neural_chat/config.py
=> Add starcoder evaluation support when finetuing

examples/huggingface/pytorch/code-generation/quantization/run_generation.py
bug fix
add past-key-values and attention_mask update
=> Update code-generation benchmark info

intel_extension_for_transformers/llm/library/jblas/jblas/kernel_avx2.h, intel_extension_for_transformers/llm/operator/cscr/dispatcher/src/jblas_weightonly_dispatcher.cpp
feature or bug fix or documentation or others: feature
enable avx_vnni ISA in qbits & fix windows compile
=> Upgrade qbits backend

intel_extension_for_transformers/llm/runtime/graph/application/main_run.cpp, intel_extension_for_transformers/llm/runtime/graph/models/bloom/bloom.cpp, intel_extension_for_transformers/llm/runtime/graph/models/falcon/falcon.cpp, intel_extension_for_transformers/llm/runtime/graph/models/gptj/gptj.cpp, intel_extension_for_transformers/llm/runtime/graph/models/gptneox/gptneox.cpp, intel_extension_for_transformers/llm/runtime/graph/models/llama/llama.cpp, intel_extension_for_transformers/llm/runtime/graph/models/model_utils/arg_parse.cpp, intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_utils.cpp, intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_utils.h, intel_extension_for_transformers/llm/runtime/graph/models/mpt/mpt.cpp, intel_extension_for_transformers/llm/runtime/graph/models/opt/opt.cpp, intel_extension_for_transformers/llm/runtime/graph/models/starcoder/starcoder.cpp, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_baichuan.py, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_bloom.py, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_chatglm.py, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_dolly.py, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_falcon.py, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_gptj.py, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_gptneox.py, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_llama.py, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_mpt.py, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_opt.py, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_starcoder.py
bug fix
The original model did not handle end of text correctly
=> read special token id from tokenizer

intel_extension_for_transformers/utils/llm_carbon_calc.py, intel_extension_for_transformers/utils/llm_carbon_calc_readme.md, tests/test_carbon_calc.py
feature - utility tool 
No API changed
Add a simple LLM carbon emission calculator
=> utils: add LLM carbon emission calculator

intel_extension_for_transformers/neural_chat/tests/api/test_model.py
=> fix UT test_model

intel_extension_for_transformers/llm/runtime/graph/application/main_run.cpp
Bug fix
Fix the msvc compile issue.
N/A
Manual tests
N/A
=> Fix the msvc compile issue of the Baichuan

intel_extension_for_transformers/llm/runtime/graph/__init__.py, intel_extension_for_transformers/llm/runtime/graph/application/main_pybind.cpp, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_opt.py, setup.py
=> fix post process with topk topp of python api

intel_extension_for_transformers/neural_chat/chatbot.py, intel_extension_for_transformers/neural_chat/config.py, intel_extension_for_transformers/neural_chat/models/base_model.py, intel_extension_for_transformers/neural_chat/models/model_utils.py, workflows/chatbot/inference/generate.py
=> NeuralChat support IPEX int8 model

intel_extension_for_transformers/neural_chat/docker/Dockerfile, intel_extension_for_transformers/neural_chat/docker/finetuning/Dockerfile, intel_extension_for_transformers/neural_chat/docs/notebooks/multi_node_finetuning_on_spr.ipynb, intel_extension_for_transformers/neural_chat/examples/instruction_tuning/README.md, workflows/chatbot/fine_tuning/README.md
Restrain oneccl_bind_pt version to 2.0.0+cpu before IPEX 2.1.0 release
To make torch/IPEX/oneccl/torchaudio/torchvision match with each other
=> restrain oneccl version

intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_epilogue.h, intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_prologue.h, intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_utils.h, intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_weight_compression.h, intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_wrapper.h, intel_extension_for_transformers/llm/library/jblas/jblas/kernel_avx2.h, intel_extension_for_transformers/llm/library/jblas/jblas/kernel_avx512f.h, intel_extension_for_transformers/llm/library/jblas/jblas/kernel_jit.h, intel_extension_for_transformers/llm/library/jblas/jblas/kernel_ref.h, intel_extension_for_transformers/llm/library/jblas/jblas/kernel_wrapper.h, intel_extension_for_transformers/llm/operator/cscr/dispatcher/src/jblas_weightonly_dispatcher.cpp, intel_extension_for_transformers/llm/runtime/graph/core/layers/inner_product.cpp, intel_extension_for_transformers/llm/runtime/graph/core/layers/ip_fusion_ffn.cpp, intel_extension_for_transformers/llm/runtime/graph/core/layers/ip_fusion_qkv.cpp, intel_extension_for_transformers/llm/runtime/graph/core/layers/mha_dense.cpp
=> [CPP Graph] Opt qbits dequant

intel_extension_for_transformers/neural_chat/models/model_utils.py
bug fix
Fix ChatGLM2 model loading issue
ChatGLM2 model can run successfully in NeuralChat.
None.
=> Fix ChatGLM2 model loading issue

intel_extension_for_transformers/llm/runtime/graph/README.md, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_baichuan.py, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_bloom.py, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_chatglm.py, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_dolly.py, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_falcon.py, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_gptj.py, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_gptneox.py, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_mpt.py, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_opt.py, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_starcoder.py, intel_extension_for_transformers/llm/runtime/graph/scripts/inference.py, intel_extension_for_transformers/llm/runtime/graph/scripts/quantize.py, intel_extension_for_transformers/llm/runtime/graph/scripts/run.py, intel_extension_for_transformers/transformers/modeling/modeling_auto.py
=> update python api readme

examples/huggingface/pytorch/question-answering/deployment/squad/MLperf_example/README.md, examples/huggingface/pytorch/question-answering/deployment/squad/bert_large/README.md, examples/huggingface/pytorch/question-answering/dynamic/README.md, examples/huggingface/pytorch/question-answering/pruning/basic_magnitude/README.md
Fix documentation
This pull request fixes typos in markdown files for `examples/huggingface/pytorch/question-answering`.
=> docs: fix typos in question answering of pytorch

.github/workflows/script/unitTest/coverage/calc_coverage.sh, intel_extension_for_transformers/neural_chat/docker/Dockerfile, intel_extension_for_transformers/neural_chat/docker/finetuning/Dockerfile
neuralchat docker refine
(1) compatible with docker/Dockerfile
(2) do not need git clone repo inside docker, as we can copy from outside. Save time and avoid potential network issue
=> [NeuralChat] Refine neuralchat docker

intel_extension_for_transformers/llm/runtime/graph/models/baichuan/baichuan.cpp, intel_extension_for_transformers/llm/runtime/graph/models/baichuan/baichuan_utils.cpp, intel_extension_for_transformers/llm/runtime/graph/models/llama/llama.cpp, intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_utils.cpp
Feature Add
Baichuan MHA vs MHA memory-f16 performance
first token: 5.05ms vs 7.25ms
Next toekn: 46.74ms vs 51.33ms
MHA Screenshot:
MHA memory-f16 Screenshot:
N/A
Extension tests and manual tests.
https://inteltf-jenk.sh.intel.com/job/ITREX-cpp-graph-extension/157/
N/A
=> [LLM Runtime] Baichuan FFN & MHA support

.github/workflows/script/formatScan/nlp_dict.txt, README.md, intel_extension_for_transformers/llm/runtime/graph/README.md
documentation
upload streaming llm video
=> [Documentation] upload streaming llm video

examples/huggingface/pytorch/text-generation/quantization/run_generation.py, intel_extension_for_transformers/transformers/modeling/modeling_auto.py
bug fix
sq alpha auto tune need provide calib_dataloader.
=> Support smooth quant alpha auto tune

.github/workflows/unit-test-neuralchat.yml
Bugfix, fix remaining issue in this PR: https://github.com/intel/intel-extension-for-transformers/pull/489
=> fix minor issue

intel_extension_for_transformers/neural_chat/examples/textbot/backend/textbot.yaml, intel_extension_for_transformers/neural_chat/server/neuralchat_server.py
=> Add tokenizer name support for NeuralChat textbot

intel_extension_for_transformers/neural_chat/tests/cache/test_cache.py
=> [NeuralChat] Update test_cache.py

intel_extension_for_transformers/neural_chat/chatbot.py, intel_extension_for_transformers/neural_chat/docker/Dockerfile, intel_extension_for_transformers/neural_chat/docker/inference/0001-fix-lm-head-overriden-issue-move-it-from-checkpoint-.patch, intel_extension_for_transformers/neural_chat/models/model_utils.py, workflows/chatbot/inference/README.md, workflows/chatbot/utils/gaudi_spawn.py
=> Habana 1.12

docs/README.md
Updated documentation for better user experience
I have improved this readme by implementing a well-defined structure, enhancing readability, and delivering a more user-friendly experience, thereby ensuring greater clarity and ease for the user.
=> Updated documentation for better user experience

.github/workflows/chatbot-inference-llama-2-7b_70b-chat-hf-hpu.yml, intel_extension_for_transformers/neural_chat/chatbot.py, intel_extension_for_transformers/neural_chat/docker/Dockerfile, intel_extension_for_transformers/neural_chat/docker/inference/0001-fix-lm-head-overriden-issue-move-it-from-checkpoint-.patch, intel_extension_for_transformers/neural_chat/models/model_utils.py, workflows/chatbot/inference/README.md, workflows/chatbot/utils/gaudi_spawn.py
=> run inference with habana 1.12 and deepspeed

.github/workflows/chatbot_finetuning.yml, .github/workflows/deploy-test.yml, .github/workflows/optimize-test.yml
=> clean CI code

tests/test_tf_autodistillation.py, tests/test_tf_distillation.py
=> [CI]fix ut model name

intel_extension_for_transformers/neural_chat/examples/talkingbot/README.md, intel_extension_for_transformers/neural_chat/examples/textbot/README.md
bug fix
Fix README frontend link issue
The user can follow the link to check the frontend README file.
Document change only.
None.
=> Fix README frontend link issue

.github/workflows/unit-test-neuralchat.yml
migrate neuralchat UT to azure ICX
better dispatch for ut jobs
=> migrate neuralchat UT to azure

docs/export.md
=> fix-minor-typo

.github/workflows/deploy-test.yml, .github/workflows/optimize-test.yml, .github/workflows/unit-test-engine.yml, .github/workflows/unit-test-kernel.yml, .github/workflows/unit-test-optimize.yml
use shared disk instead of assign disk in each node
(1) huggingface cache move to shared disk
(2) local file use shared disk
=> [CI] Use shared disk

intel_extension_for_transformers/neural_chat/examples/deployment/rag/README.md, intel_extension_for_transformers/neural_chat/examples/deployment/talkingbot/server/backend/README.md, intel_extension_for_transformers/neural_chat/examples/deployment/talkingbot/server/frontend, intel_extension_for_transformers/neural_chat/examples/deployment/textbot/backend/README.md, intel_extension_for_transformers/neural_chat/examples/deployment/textbot/frontend, intel_extension_for_transformers/neural_chat/examples/photo_ai/backend/README.md, intel_extension_for_transformers/neural_chat/ui/side_by_side/README.md, intel_extension_for_transformers/neural_chat/ui/textbot/README.md, workflows/chatbot/inference/backend/chat/README.md, workflows/chatbot/inference/backend/fastrag/README.md, workflows/chatbot/inference/backend/sd/README.md
bug fix
Fix frontend directory symbolic Link issue
Users can access the frontend directory in examples.
None.
=> Fix frontend directory symbolic Link issue

.github/workflows/chatbot-test.yml, .github/workflows/unit-test-engine.yml, .github/workflows/unit-test-neuralchat.yml, .github/workflows/unit-test-optimize.yml, intel_extension_for_transformers/neural_chat/tests/server/test_askdoc_server.py
bugfix
chatbot workflow name error
=> [Infra] fix chatbot workflow name

tests/test_tf_distillation.py
=> [UT] fix tf ut

intel_extension_for_transformers/llm/runtime/graph/README.md
documentation 
n/a
n/a
n/a
n/a
=> [Doc] change the structure of llm runtime readme

docs/build_docs/source/kernel_perf.rst, docs/examples.md
=> [Doc] Typos fix in mulitple docs files

intel_extension_for_transformers/neural_chat/server/README.md, intel_extension_for_transformers/neural_chat/server/config/neuralchat.yaml, intel_extension_for_transformers/neural_chat/server/neuralchat_server.py
feature
Support peft model in server mode
Users can specify peft mode in yaml file to run it in server mode.
None.
=> Support peft model in server mode

examples/huggingface/pytorch/text-generation/quantization/requirements.txt
=> fix text-generation requirements.txt

docker/Dockerfile_chatbot, docker/README_chatbot.md, docker/docker-compose.yml, intel_extension_for_transformers/neural_chat/docker/Dockerfile, intel_extension_for_transformers/neural_chat/examples/textbot/backend/README.md, intel_extension_for_transformers/neural_chat/requirements.txt, intel_extension_for_transformers/neural_chat/requirements_cpu.txt, intel_extension_for_transformers/neural_chat/requirements_xpu.txt, tests/requirements.txt
=> Combine docker

.github/workflows/script/unitTest/run_unit_test_neuralchat.sh, intel_extension_for_transformers/neural_chat/tests/audio/test_cut_video.py, intel_extension_for_transformers/neural_chat/tests/audio/test_video_to_wav.py
=> [NeuralChat] fix video path

intel_extension_for_transformers/neural_chat/requirements.txt, intel_extension_for_transformers/neural_chat/requirements_cpu.txt, intel_extension_for_transformers/neural_chat/requirements_hpu.txt, intel_extension_for_transformers/neural_chat/requirements_pc.txt, intel_extension_for_transformers/neural_chat/requirements_xpu.txt, intel_extension_for_transformers/neural_chat/tests/requirements.txt
bug fix
Fix compatibility issue caused by the latest version of Pydantic
The neuralchat frontend and backend service can be run successfully.
None.
=> [NeuralChat] Fix compatibility issue caused by the latest version of Pydantic

tests/test_tf_autodistillation.py
bug fix
fix tf autodistill ut fail
None
None
=> [UT]fix tf autodistill ut fail

intel_extension_for_transformers/neural_chat/examples/finetuning/ppo_pipeline/README.md, intel_extension_for_transformers/neural_chat/examples/finetuning/ppo_pipeline/requirements.txt, intel_extension_for_transformers/neural_chat/examples/finetuning/ppo_pipeline/reward_modeling.py
=> [NeuralChat] add reward modeling handle for PPO

examples/huggingface/pytorch/text-classification/deployment/mrpc/bge_large/README.md, examples/huggingface/pytorch/text-classification/deployment/mrpc/bge_large/run_bge.sh
README update
* Bge deployment example README update
N/A
Bge-base:
Best result: 0.7500
Best tunning result: 0.7643
Please check the https://github.com/intel/intel-extension-for-transformers/pull/619 for more perf data.
N/A
=> [Example] BAAI/bge-large-en-v1.5 & BAAI/bge-base-en-v1.5 README update

intel_extension_for_transformers/neural_chat/pipeline/plugins/audio/README.md, intel_extension_for_transformers/neural_chat/pipeline/plugins/audio/requirements.txt, intel_extension_for_transformers/neural_chat/requirements.txt, intel_extension_for_transformers/neural_chat/requirements_cpu.txt, intel_extension_for_transformers/neural_chat/requirements_hpu.txt, intel_extension_for_transformers/neural_chat/requirements_pc.txt, intel_extension_for_transformers/neural_chat/requirements_xpu.txt, intel_extension_for_transformers/neural_chat/tests/requirements.txt
bug fix
loose paddle version for security check
security CI passed
CI
paddle -> latest
=> loose version for security check

examples/huggingface/onnxruntime/speech-recognition/quantization/run_benchmark.sh
=> Fix benchmark cmd for onnx whisper example

examples/huggingface/pytorch/text-generation/deployment/README.md
link cpp graph to text-generation  example.
=> [LLM Runtime] Update example README.md

docker/README_chatbot.md
minor fix for docker documents
=> update docker readme

intel_extension_for_transformers/neural_chat/ui/textbot/app.py
bug fix
Fix textbot chatglm model conversation issue
Users can use chatglm2 to setup text chatbot.
None.
=> Fix textbot chatglm model conversation issue

examples/huggingface/onnxruntime/speech-recognition/quantization/run_benchmark.sh, examples/huggingface/onnxruntime/speech-recognition/quantization/run_whisper.py
=> Add providers for onnx whisper example

.github/workflows/script/formatScan/pylint.sh, intel_extension_for_transformers/neural_chat/models/model_utils.py
bug fix
Fix llm runtime int4 multi-turn inference issue, chatglm2 still has issue now.
Users can deploy llm runtime int4 service using neuralchat.
None.
=> Fix llm runtime int4 multi-turn inference issue

intel_extension_for_transformers/neural_chat/pipeline/plugins/audio/tts.py, intel_extension_for_transformers/neural_chat/pipeline/plugins/audio/utils/reduce_noise.py, intel_extension_for_transformers/neural_chat/tests/ci/plugins/audio/test_tts.py
feature
Noise reducer and amplifier applied as default in case for speecht5
Remove output electronic noise
run tts test
None
=> add noise reducer and amplifier

intel_extension_for_transformers/llm/finetuning/data_utils.py, intel_extension_for_transformers/llm/finetuning/finetuning.py, intel_extension_for_transformers/neural_chat/examples/finetuning/instruction/README.md, intel_extension_for_transformers/neural_chat/prompts/prompt.py, intel_extension_for_transformers/neural_chat/requirements_hpu.txt, intel_extension_for_transformers/neural_chat/requirements_pc.txt, intel_extension_for_transformers/neural_chat/tests/nightly/finetuning/test_finetuning.py
feature and documentation
Added StarCoder, CodeLlama, Falcon and Mistral finetuning example in NeuralChat.
pass local test
follow readme
=> [NeuralChat] Added StarCoder, CodeLlama, Falcon and Mistral finetuning example in NeuralChat

.github/workflows/script/formatScan/nlp_dict.txt, README.md, docs/contributors.md, docs/support_matrix.md, intel_extension_for_transformers/llm/runtime/graph/README.md
documentation 
add AVX2 support in readme
n/a
n/a
n/a
=> [Doc]add readme

intel_extension_for_transformers/neural_chat/models/base_model.py
Fix the issue of the prompt has been used twice to construct the input
=> [NeuralChat] Fix the bug in prompt generation

.github/workflows/script/models/cpp_graph_inference.sh, intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_utils.cpp
as title, will disable bf16 scale and reset to f32
=> [LLM Runtime] disable bf16 scale for jblas

intel_extension_for_transformers/neural_chat/tests/audio/test_asr_chinese.py, intel_extension_for_transformers/neural_chat/tests/ci/api/test_chatbot_build_api.py, intel_extension_for_transformers/neural_chat/tests/ci/api/test_inference.py, intel_extension_for_transformers/neural_chat/tests/ci/api/test_rag.py, intel_extension_for_transformers/neural_chat/tests/ci/cli/test_cli.py, intel_extension_for_transformers/neural_chat/tests/ci/plugins/audio/test_asr.py, intel_extension_for_transformers/neural_chat/tests/ci/plugins/audio/test_cut_video.py, intel_extension_for_transformers/neural_chat/tests/ci/plugins/audio/test_split_audio.py, intel_extension_for_transformers/neural_chat/tests/ci/plugins/audio/test_tts.py, intel_extension_for_transformers/neural_chat/tests/ci/plugins/audio/test_video_to_wav.py, intel_extension_for_transformers/neural_chat/tests/ci/server/test_askdoc_server.py, intel_extension_for_transformers/neural_chat/tests/ci/server/test_bits_and_bytes_server.py, intel_extension_for_transformers/neural_chat/tests/ci/server/test_ipex_int8_textchat_server.py, intel_extension_for_transformers/neural_chat/tests/ci/server/test_itrex_int4_textchat_server.py, intel_extension_for_transformers/neural_chat/tests/ci/server/test_itrex_llm_runtime_int4_server.py, intel_extension_for_transformers/neural_chat/tests/ci/server/test_mix_precision_server.py, intel_extension_for_transformers/neural_chat/tests/ci/server/test_textchat_server.py, intel_extension_for_transformers/neural_chat/tests/ci/server/test_textchat_with_retrieval_server.py, intel_extension_for_transformers/neural_chat/tests/ci/server/test_voicechat_server.py, intel_extension_for_transformers/neural_chat/tests/nightly/plugins/test_ner.py, intel_extension_for_transformers/neural_chat/tests/server/test_textchat_witch_cache_server.py
Fix neuralchat UT path when locally run
=> [Neural Chat] Fix neuralchat ut path

examples/huggingface/pytorch/text-generation/quantization/README.md, examples/huggingface/pytorch/text-generation/quantization/run_generation.py
support peft model make mixedprecision, woq, smoothquant and load. 
update readme usage.
=> [LLM] text-generation example support peft model quantization

intel_extension_for_transformers/llm/runtime/graph/models/gptneox/gptneox_utils.cpp
fix bug
not 
JIRA ticket: None
=> [LLM Runtime]Fix gptneox bug

README.md, docs/tutorials/README.md
Documentation
add readme of tutorials
n/a
n/a
n/a
=> [Doc] add readme of tutorials

.gitpod.yml
others
use correct gitpod config
n/a
n/a
n/a
=> [others]refine gitpod

intel_extension_for_transformers/llm/runtime/graph/README.md, intel_extension_for_transformers/llm/runtime/graph/__init__.py, intel_extension_for_transformers/llm/runtime/graph/application/main_pybind.cpp, intel_extension_for_transformers/transformers/modeling/modeling_auto.py, intel_extension_for_transformers/transformers/utils/quantization_config.py, tests/test_llm_runtime.py
feature
```python
from transformers import AutoTokenizer, TextStreamer
from intel_extension_for_transformers.transformers import AutoModelForCausalLM, WeightOnlyQuantConfig
from transformers import StoppingCriteria, StoppingCriteriaList
import torch
from typing import (IO, TYPE_CHECKING, Any, Callable, Dict, Iterable, List,
Literal, Optional, Sequence, Tuple, TypeVar, Union)
model_name = "/mnt/disk1/data2/zhenweil/models/llama/Llama-2-7b-chat-hf"  # or local path to model
woq_config = WeightOnlyQuantConfig(compute_dtype="int8", weight_dtype="int4", use_cache=True)
prompt = "[INST] 1+1=? [\INST]"
tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
inputs = tokenizer(prompt, return_tensors="pt").input_ids
streamer = TextStreamer(tokenizer)
class …
```
=> [LLM Runtime] Refine Python API

intel_extension_for_transformers/llm/runtime/graph/__init__.py
not
add python api for mistral
- [issue678](https://github.com/intel/intel-extension-for-transformers/issues/678)
=> [LLM Runtime] add python api for mistral

examples/huggingface/pytorch/text-generation/quantization/run_generation.py
add save for mixedprecision model
=> [LLM Example] add save for mixedprecision model

intel_extension_for_transformers/neural_chat/models/model_utils.py
bug fix
Fix issues found during integration test with ChatGLM2 llm runtime int4
ChatGLM2 llm runtime int4 model can work well, currently still has accuracy issue exist. 
Local test and pre-CI.
None.
=> Fix ChatGLM2 llm runtime int4 issue

intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_utils.h, intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_weight_compression.h, intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_wrapper.h, intel_extension_for_transformers/llm/library/jblas/jblas/kernel_avx512_bf16.h, intel_extension_for_transformers/llm/library/jblas/jblas/kernel_jit.h
As title
N/A
GitHub action checks.
In addition, it is locally tested that the performance impact of this PR to MHA (FLASH_ATTN_KV_UPDATE) is neglectable.
Before
After
No
=> [LLM Runtime] Correct GCC targe options

.github/workflows/script/unitTest/env_setup.sh
INC smooth quant changed, lead to ITREX error, restrict to safe commit
=> restrain INC version

intel_extension_for_transformers/neural_chat/chatbot.py, intel_extension_for_transformers/neural_chat/docker/Dockerfile, intel_extension_for_transformers/neural_chat/models/model_utils.py, intel_extension_for_transformers/neural_chat/tests/ci/optimization/test_optimization.py, workflows/chatbot/inference/generate.py
=> enable mistral in habana, fix issue in generate.py

intel_extension_for_transformers/llm/runtime/graph/README.md, intel_extension_for_transformers/llm/runtime/graph/requirements.txt, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_baichuan.py, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_chatglm.py, requirements.txt
document
https://github.com/intel/intel-extension-for-transformers/issues/694
=> [LLM Runtime] Update README

.github/workflows/script/unitTest/env_setup.sh
The relative PR is reverted in INC, restriction can be removed
https://github.com/intel/neural-compressor/pull/1395
=> [Infra] remove restriction of INC

intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/README.md
Add introduction about supporting for popular file farmat on retrieval.
=> Update retrieval readme on file farmat

intel_extension_for_transformers/neural_chat/examples/finetuning/instruction/README.md
=> add finetuning metrics doc

intel_extension_for_transformers/neural_chat/examples/finetuning/instruction/README.md
documentation
Add dataset arguments description in readme.
=> Add dataset arguments description in readme

examples/huggingface/pytorch/text-generation/quantization/run_generation.py, intel_extension_for_transformers/llm/evaluation/lm_eval/models/__init__.py, intel_extension_for_transformers/llm/evaluation/lm_eval/models/models.py, intel_extension_for_transformers/transformers/utils/utility.py
in utility.py will cause other example install optimum, although they don't need it.
so remove it to llm.evaluation, only LLM model will use it.
=> Move TSModelCausalLMForOPTLLM to lm-eval

.gitignore, intel_extension_for_transformers/llm/operator/csrc/include/dropout.hpp, intel_extension_for_transformers/llm/operator/csrc/src/dropout.cpp
=> fix QBits compile on windows

intel_extension_for_transformers/llm/finetuning/data_utils.py
=> add dpo data process to clm finetune

examples/huggingface/pytorch/text-generation/quantization/run_generation.py, intel_extension_for_transformers/transformers/utils/quantization_config.py
sq auto tuning need pass recipes to Config, so remove the alpha and add the recipes.
use "black" refine the quantization_config.py style.
=> SmoothQuantConfig support recipes

intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/README.md
=> [NeuralChat] Update retrieval README.md

intel_extension_for_transformers/neural_chat/examples/finetuning/ppo_pipeline/README.md, intel_extension_for_transformers/neural_chat/examples/finetuning/ppo_pipeline/requirements.txt, intel_extension_for_transformers/neural_chat/examples/finetuning/ppo_pipeline/reward_modeling.py, intel_extension_for_transformers/neural_chat/examples/finetuning/ppo_pipeline/rl_training.py, intel_extension_for_transformers/transformers/modeling/trl_models/__init__.py, intel_extension_for_transformers/transformers/modeling/trl_models/modeling_base.py, intel_extension_for_transformers/transformers/modeling/trl_models/modeling_value_head.py, intel_extension_for_transformers/transformers/ppo_config.py, intel_extension_for_transformers/transformers/ppo_core.py, intel_extension_for_transformers/transformers/ppo_trainer.py, tests/CI/test_ppo.py, tests/requirements.txt
=> add initial version of rl_training

README.md
=> [Neural Chat] Added video for QLoRA running on client CPU

intel_extension_for_transformers/transformers/modeling/modeling_auto.py, tests/CI/test_quantization.py
bug fix modeling_auto recipes update.
=> improve modeling_auto recipes setting.

intel_extension_for_transformers/neural_chat/examples/finetuning/dpo_pipeline/README.md, intel_extension_for_transformers/neural_chat/examples/finetuning/dpo_pipeline/dpo_clm.py
support dpo training on CPU (SPR)
=> support dpo training on CPU (SPR)

.github/workflows/script/unitTest/coverage/calc_coverage.sh, .github/workflows/unit-test-llmruntime.yml
CI improvement
(1) update docker name for shared system
(2) increase threshold for ut coverage to 0.5%
=> update docker name and coverage threshold

docker/Dockerfile_chatbot, intel_extension_for_transformers/neural_chat/docker/Dockerfile
dockerfile refine
Use files in the container instead of copying from local
no
no
no
=> dockerfile refine

examples/huggingface/pytorch/text-generation/quantization/run_benchmark.sh, examples/huggingface/pytorch/text-generation/quantization/run_generation.py, examples/huggingface/pytorch/text-generation/quantization/run_tuning.sh, intel_extension_for_transformers/transformers/utils/utility.py
althought dolly 's model_type is gpt_neox, but dolly requests transformers version higher or equal than 4.34.0, so set ipex_opt_llm=False
for gptj, opt, llama, set transformers to 4.31.0
fix bloom
=> Fix nightly CI issue

intel_extension_for_transformers/neural_chat/models/model_utils.py
make ipex.optimize_transformers sq model can be neuralchat used.
=> add neuralchat support ipex.optimize_transformers sq int8 model loading

intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_weight_compression.h, intel_extension_for_transformers/llm/runtime/graph/core/layers/jblas_common.cpp, intel_extension_for_transformers/llm/runtime/graph/core/ne_jblas.h, intel_extension_for_transformers/llm/runtime/graph/models/gptj/gptj.cpp, intel_extension_for_transformers/llm/runtime/graph/models/llama/llama.cpp, intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_files.h
=> [LLM Runtime] Add jblas split weight interface and support jblas models

examples/huggingface/pytorch/code-generation/quantization/Dockerfile-multiple, examples/huggingface/pytorch/code-generation/quantization/requirements.txt, examples/huggingface/pytorch/text-generation/quantization/requirements.txt
=> Fix lm-eval optimum version

intel_extension_for_transformers/llm/runtime/graph/README.md
=> Update GPTQ into README

docs/installation.md, intel_extension_for_transformers/llm/runtime/graph/CMakeLists.txt, intel_extension_for_transformers/llm/runtime/graph/developer_document.md, setup.py
- reinforcement llm runtime graph devleoper guide
- add camke arg about gcc, g++ version
issue : https://github.com/intel/intel-extension-for-transformers/issues/743#issuecomment-1826789762
=> [LLM Runtime] docs : reinforcement llm runtime graph devleoper guide

.dockerignore, .github/workflows/build-container.yaml, docker/Dockerfile, docker/README.md, docker/docker-compose.yml
Docker Change for Release
- update GHA to account for test folder changes
- Include License Files
- Reduce Layer Count
- Update Docs
n/a
Local Build/Test, needs to be sync'd with internal for validation
n/a
=> update docker container and docs for v1.3.0

examples/huggingface/pytorch/text-generation/quantization/README.md, examples/huggingface/pytorch/text-generation/quantization/run_benchmark.sh, examples/huggingface/pytorch/text-generation/quantization/run_generation.py, examples/huggingface/pytorch/text-generation/quantization/run_tuning.sh
1. use llama2 replace llama due to llama models deleted from huggingface. (README.md, run_tuning.sh and run_benchmark.sh)
2. improve run_generation.py save logistic.
3. remove the validated model list, will update by IPEX 2.1.1 release. (README.md)
=> [LLM example] improve text-generation example

intel_extension_for_transformers/neural_chat/examples/finetuning/finetune_neuralchat_v3/README.md
=> update Gaudi2 name.

intel_extension_for_transformers/transformers/modeling/modeling_auto.py
1. alpha=="auto" need pass the dataloader to INC, to align with INC, use dict as input datatype to meet more models.
2. use black to format the modeling_auto.py
=> [LLM] Fix SmoothQuant auto tuning dataloader

docs/weightonlyquant.md
=> [LLM Runtime] Update weightonlyquant.md 

intel_extension_for_transformers/llm/finetuning/finetuning.py, intel_extension_for_transformers/neural_chat/config.py
use validation dataset for evaluation
=> [NeuralChat] use validation dataset for evaluation.

intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/retrieval_agent.py
=> [NeuralChat] Fix the print bug in retriever

intel_extension_for_transformers/neural_chat/pipeline/plugins/video/face_animation/src/facerender/modules/make_animation.py, intel_extension_for_transformers/neural_chat/tests/ci/api/test_chatbot_build_api.py
bug fix
fix tts and face animation UT on NV A100 gpu
JIRA ticket: [NLPTOOLKIU-1046](https://jira.devtools.intel.com/browse/NLPTOOLKIU-1046) [NLPTOOLKIU-1048](https://jira.devtools.intel.com/browse/NLPTOOLKIU-1048)
UT pass on gpu
UT
None
=> fix tts and face animation UT on gpu

intel_extension_for_transformers/llm/runtime/graph/core/ne_layers.h, intel_extension_for_transformers/llm/runtime/graph/models/whisper/dr_wav.h, intel_extension_for_transformers/llm/runtime/graph/models/whisper/whisper.cpp, intel_extension_for_transformers/llm/runtime/graph/models/whisper/whisper.h, intel_extension_for_transformers/llm/runtime/graph/models/whisper/whisper_utils.cpp
=> [LLM Runtime]fix format

intel_extension_for_transformers/llm/finetuning/data_utils.py, intel_extension_for_transformers/neural_chat/examples/finetuning/dpo_pipeline/dpo_clm.py, intel_extension_for_transformers/neural_chat/examples/finetuning/ppo_pipeline/reward_modeling.py
update dpo dataset fields name.
=> [NeuralChat] update dpo dataset fields name.

intel_extension_for_transformers/neural_chat/server/restful/photoai_services.py
fixed typo.
ocurred -> occurred
=> [NeuralChat] Fix typo in photoai_services.py

intel_extension_for_transformers/neural_chat/examples/finetuning/multi_modal/train.py, intel_extension_for_transformers/transformers/modeling/__init__.py, intel_extension_for_transformers/transformers/modeling/llava_models/__init__.py, tests/CI/test_llava.py
update llava model import path.
=> [NeuralChat] update llava model import path

intel_extension_for_transformers/neural_chat/utils/database/mysqldb.py
=> escape sql string for SDL

intel_extension_for_transformers/neural_chat/examples/finetuning/ppo_pipeline/README.md, intel_extension_for_transformers/neural_chat/examples/finetuning/ppo_pipeline/merge_peft_adapter.py, intel_extension_for_transformers/neural_chat/examples/finetuning/ppo_pipeline/reward_modeling.py, intel_extension_for_transformers/neural_chat/examples/finetuning/ppo_pipeline/rl_training.py, intel_extension_for_transformers/transformers/modeling/trl_models/modeling_base.py, intel_extension_for_transformers/transformers/ppo_trainer.py
=> Update ppo readme

intel_extension_for_transformers/llm/finetuning/finetuning.py, intel_extension_for_transformers/neural_chat/examples/finetuning/instruction/llama2_ds_zero3_config.json, intel_extension_for_transformers/neural_chat/examples/finetuning/ppo_pipeline/reward_modeling.py
=> fix save issue of deepspeed zero3

intel_extension_for_transformers/transformers/trainer.py
bug fix
API not change
Move `optimum` package import into function that get export args.
CI
No
=> Move `optimum` package import into export function

examples/.config/pytorch_optimize.json, examples/huggingface/pytorch/code-generation/quantization/README.md, examples/huggingface/pytorch/code-generation/quantization/run_benchmark.sh, examples/huggingface/pytorch/code-generation/quantization/run_generation.py, examples/huggingface/pytorch/code-generation/quantization/run_tuning.sh, examples/huggingface/pytorch/text-generation/quantization/README.md, examples/huggingface/pytorch/text-generation/quantization/run_benchmark.sh, examples/huggingface/pytorch/text-generation/quantization/run_generation.py, examples/huggingface/pytorch/text-generation/quantization/run_tuning.sh, intel_extension_for_transformers/llm/evaluation/models.py
1. add extension
2. fix chatglm judgement
3. remove dolly limitation.
4. improve readme recommendation.
=> [LLM] add chatglm and codellama extension test

intel_extension_for_transformers/llm/finetuning/finetuning.py
fix not define unwrapped_model
=> fix not define unwrapped_model

docs/installation.md
=> Fix typo at installation.md

examples/huggingface/pytorch/text-generation/quantization/README.md, examples/huggingface/pytorch/text-generation/quantization/run_generation.py
=> [LLM] add an option to enable fallback_add

intel_extension_for_transformers/neural_chat/examples/finetuning/dpo_pipeline/requirements.txt, intel_extension_for_transformers/neural_chat/examples/finetuning/finetune_neuralchat_v3/README.md
update dpo dataset and dockerfile
=> [NeuralChat] update dpo dataset

intel_extension_for_transformers/llm/runtime/graph/core/ne_layers.c
=> [LLM Runtime] Fix windows compile error

examples/huggingface/pytorch/question-answering/deployment/squad/bert_large/requirements.txt, examples/huggingface/pytorch/question-answering/deployment/squad/length_adaptive_transformer/requirements.txt, examples/huggingface/pytorch/text-classification/deployment/emotion/distilbert_base_uncased/requirements.txt, examples/huggingface/pytorch/text-classification/deployment/mrpc/bert_base/requirements.txt, examples/huggingface/pytorch/text-classification/deployment/mrpc/bert_base_cased/requirements.txt, examples/huggingface/pytorch/text-classification/deployment/mrpc/bert_mini/requirements.txt, examples/huggingface/pytorch/text-classification/deployment/mrpc/distilbert_base_uncased/requirements.txt, examples/huggingface/pytorch/text-classification/deployment/mrpc/roberta_base/requirements.txt, examples/huggingface/pytorch/text-classification/deployment/sparse/bert_mini/requirements.txt, examples/huggingface/pytorch/text-classification/deployment/sparse/distilbert_base_uncased/requirements.txt, examples/huggingface/pytorch/text-classification/deployment/sst2/bert_mini/requirements.txt, examples/huggingface/pytorch/text-classification/deployment/sst2/distilbert_base_uncased/requirements.txt, examples/huggingface/pytorch/text-classification/deployment/sst2/minilm_l6_h384_uncased/requirements.txt, examples/huggingface/pytorch/text-embedding/deployment/mteb/bge/requirements.txt, examples/huggingface/pytorch/text-to-image/deployment/stable_diffusion/requirements.txt, examples/huggingface/pytorch/textual-inversion/quantization/requirements.txt, tests/requirements.txt
=> update textual-inversion requirements

examples/huggingface/pytorch/text-classification/deployment/emotion/distilbert_base_uncased/run_emotion.py
=> [LLM Runtime] Remove the unnecessary branch

intel_extension_for_transformers/transformers/trainer.py, tests/CI/test_quantization.py
bug fix
API not change
Fix bug of task infer in export
CI, extension test of engine example
No
=> Fix task infer bug in export

intel_extension_for_transformers/neural_chat/examples/deployment/codegen/backend/xeon/README.md, intel_extension_for_transformers/neural_chat/examples/deployment/codegen/backend/xeon/codegen.yaml, intel_extension_for_transformers/neural_chat/examples/deployment/codegen/backend/xeon/run_code_gen.py, intel_extension_for_transformers/neural_chat/server/config/hostfile, intel_extension_for_transformers/neural_chat/server/multi_cpu_server.py, intel_extension_for_transformers/neural_chat/server/neuralchat_server.py
feature
Support multi-cpu neuralchat restful api serving.
Local tested on two SPR servers.
no
=> [NeuralChat] Enable multi-cpu serving

intel_extension_for_transformers/llm/finetuning/finetuning.py, intel_extension_for_transformers/neural_chat/config.py, intel_extension_for_transformers/neural_chat/tests/nightly/finetuning/test_finetuning.py
API changed for supporting full finetuning
add if branch for supporting full parameters finetuning
=> [NeuralChat] support full parameters finetuning

intel_extension_for_transformers/neural_chat/examples/finetuning/dpo_pipeline/README.md, intel_extension_for_transformers/neural_chat/examples/finetuning/dpo_pipeline/dpo_clm.py, intel_extension_for_transformers/transformers/dpo_trainer.py
=> [NeuralChat] Dpo gaudi acceleration

examples/huggingface/pytorch/language-modeling/pruning/README.md, examples/huggingface/pytorch/language-modeling/pruning/run_clm_sparsegpt.py
=> sync with inc, refine data and example

.github/workflows/script/prepare_env_with_conda.bat, .github/workflows/windows-test.yml
=> [Infra] add windows binary build test

.github/workflows/script/formatScan/pylint.sh, tests/requirements.txt
restrict peft version for API change
=> update peft version

examples/huggingface/pytorch/text-embedding/deployment/mteb/bge/README.md
=> [LLM Runtime] Update BGE README.md

examples/huggingface/pytorch/language-modeling/pruning/README.md, examples/huggingface/pytorch/language-modeling/pruning/requirements.txt, examples/huggingface/pytorch/language-modeling/pruning/run_clm_sparsegpt.py, examples/huggingface/pytorch/language-modeling/pruning/scripts/run_llm_sparseGPT.sh
=> remove last_token_acc

intel_extension_for_transformers/neural_chat/requirements.txt
add limitation for tensorflow and onnx for neuralchat
docker build on GPU face conflict and take too long time to solve
=> add limitation for tensorflow and onnx for neuralchat

intel_extension_for_transformers/transformers/modeling/modeling_auto.py
fix example_inputs get when model need required position_ids.
=> Fix miss example_inputs issue

intel_extension_for_transformers/llm/runtime/graph/README.md, intel_extension_for_transformers/llm/runtime/graph/models/baichuan/baichuan.cpp, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_baichuan.py
Bug fix
Baichuan13B Bug fix
This bug will only occur when FFN is not used.
Manually and CI tests.
N/A
=> [LLM Runtime] Baichuan13B inference bug fix

intel_extension_for_transformers/llm/evaluation/models.py
falcon can reuse the default reorder cache
if use ipex.optimize_transformers, the past_kv length is 4, we should do another process.
=> improve reorder cache for the ipex.optimize_transformers.

intel_extension_for_transformers/neural_chat/requirements.txt, intel_extension_for_transformers/neural_chat/requirements_cpu.txt, intel_extension_for_transformers/neural_chat/requirements_hpu.txt, intel_extension_for_transformers/neural_chat/requirements_xpu.txt, intel_extension_for_transformers/neural_chat/tests/requirements.txt
peft upgrade cause error
RecursionError: maximum recursion depth exceeded while calling a Python object
=> add constraint for peft

intel_extension_for_transformers/llm/finetuning/finetuning.py
bug fix
fix gradient issue for qlora on seq2seq.
=> fix gradient issue for qlora on seq2seq

examples/huggingface/pytorch/text-classification/deployment/emotion/distilbert_base_uncased/executor_utils.py, examples/huggingface/pytorch/text-classification/deployment/emotion/distilbert_base_uncased/run_emotion.py, intel_extension_for_transformers/llm/runtime/deprecated/compile/sub_graph/qkv_merge.py, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_gptq_bloom.py
=> [LLM Runtime] Remove the identical branch

.github/workflows/unit-test-engine.yml
=> resolve azure disk structure issues

intel_extension_for_transformers/llm/library/jblas/CMakeLists.txt
fix stack overflow on Windows.
=> enlarge stack size

examples/huggingface/pytorch/code-generation/quantization/requirements.txt, examples/huggingface/pytorch/code-generation/quantization/run_generation.py
=> Fix code-generation woq example

intel_extension_for_transformers/neural_chat/tests/ci/server/test_plugin_service_audio.py, intel_extension_for_transformers/neural_chat/tests/nightly/server/test_retrieval_api.py
=> fix neuralchat nightly ut

intel_extension_for_transformers/neural_chat/tests/ci/api/test_chatbot_build_api.py, intel_extension_for_transformers/neural_chat/tests/ci/api/test_inference.py
skip UT failed in main branch, after root cause and fix, will recover ut test
=> skip UT to avoid block CI

intel_extension_for_transformers/neural_chat/tests/nightly/finetuning/test_finetuning.py
=> [NeuralChat] finetuning ut supports gaudi

.github/workflows/script/formatScan/nlp_dict.txt, docs/contributors.md, intel_extension_for_transformers/neural_chat/README.md
Documentation
add contributors
n/a
n/a
n/a
=> [Doc] add contributors

.github/workflows/cpp-graph-test.yml, .github/workflows/unit-test-engine.yml, .github/workflows/unit-test-kernel.yml, .github/workflows/unit-test-llmruntime.yml, .github/workflows/unit-test-neuralchat.yml, .github/workflows/unit-test-optimize.yml, intel_extension_for_transformers/neural_chat/requirements.txt, intel_extension_for_transformers/neural_chat/requirements_cpu.txt, intel_extension_for_transformers/neural_chat/requirements_hpu.txt, intel_extension_for_transformers/neural_chat/requirements_pc.txt, intel_extension_for_transformers/neural_chat/requirements_xpu.txt, intel_extension_for_transformers/neural_chat/tests/requirements.txt
update neural compressor version
=> update neural compressor version

intel_extension_for_transformers/neural_chat/tests/ci/server/test_multi_cpu_server.py, intel_extension_for_transformers/neural_chat/tests/ci/server/test_server_commands.py, intel_extension_for_transformers/neural_chat/tests/ci/utils/test_dotdict.py, intel_extension_for_transformers/neural_chat/tests/ci/utils/test_mysqldb.py
UT coverage
Add UT for neuralchat utils.
Improve UT coverage
Local tested on SDP server.
no.
=> [NeuralChat] Improve utils UT coverage

intel_extension_for_transformers/llm/finetuning/finetuning.py, intel_extension_for_transformers/neural_chat/config.py
API changed for replacing use_auth_token to token, because of transformers upgrading
upgrade huggingface/transformers use_auth_token to token
=> [NeuralChat] upgrade huggingface/transformers use_auth_token to token

intel_extension_for_transformers/llm/runtime/graph/application/main_pybind.cpp, intel_extension_for_transformers/llm/runtime/graph/scripts/perplexity.py
=> [LLM Runtime] Fix PPL Test

intel_extension_for_transformers/llm/runtime/graph/README.md, intel_extension_for_transformers/llm/runtime/graph/application/common.cpp, intel_extension_for_transformers/llm/runtime/graph/application/common.h, intel_extension_for_transformers/llm/runtime/graph/scripts/python_api_example.py, intel_extension_for_transformers/llm/runtime/graph/scripts/quantize.py, intel_extension_for_transformers/transformers/utils/config.py
=> [LLM Runtime] Add MatMul data types combinations table

examples/huggingface/pytorch/text-classification/auto_slim/README.md, examples/huggingface/pytorch/text-classification/auto_slim/run_auto_slim.sh, examples/huggingface/pytorch/text-classification/auto_slim/run_bge_sts_autoslim.py
=> Add auto slim example for bge models on STS tasks

intel_extension_for_transformers/neural_chat/tests/ci/api/test_chatbot_exception.py, intel_extension_for_transformers/neural_chat/tests/ci/plugins/audio/test_reduce_noise.py
bug fix
Fix UT issues on Gaudi
The UT issues can be cleaned.
None.
=> [NeuralChat] Fix UT issues on Gaudi

intel_extension_for_transformers/llm/runtime/graph/README.md
=> [LLM Runtime] Update README.md

intel_extension_for_transformers/llm/runtime/graph/scripts/convert_mistral.py
=> [LLM Runtime] Fix mistral bf16

intel_extension_for_transformers/neural_chat/models/model_utils.py
bug fix
Fix llama model inference hang issue
The llama model inference can be executed successfully.
None.
=> [NeuralChat] Fix llama model inference hang issue on Gaudi

README.md, intel_extension_for_transformers/llm/runtime/graph/README.md
Documentation 
n/a
n/a
n/a
n/a
=> [Doc]refine example

examples/huggingface/onnxruntime/speech-recognition/quantization/requirements.txt
bug fix 
Fix ORT whisper example
extension test
no
=> Fix ORT whisper example

intel_extension_for_transformers/neural_chat/requirements.txt, intel_extension_for_transformers/neural_chat/tests/nightly/models/test_chatglm.py, intel_extension_for_transformers/neural_chat/tests/nightly/models/test_codellama.py, intel_extension_for_transformers/neural_chat/tests/nightly/models/test_llama.py, intel_extension_for_transformers/neural_chat/tests/nightly/models/test_mistral.py, intel_extension_for_transformers/neural_chat/tests/nightly/models/test_model_utils.py, intel_extension_for_transformers/neural_chat/tests/nightly/models/test_mpt.py, intel_extension_for_transformers/neural_chat/tests/nightly/models/test_neuralchat.py, intel_extension_for_transformers/neural_chat/tests/nightly/models/test_qwen.py, intel_extension_for_transformers/neural_chat/tests/nightly/models/test_starcoder.py, intel_extension_for_transformers/neural_chat/tests/requirements.txt
modify UT model path
Specify local model path for nightly UT
Nightly UT will load model from local path without downloading models. This will save disk space on testign servers.
Local tested.
no.
=> [NeuralChat] Specify local model path for nightly UT

examples/huggingface/pytorch/text-generation/quantization/run_generation.py
1. conver recipes from str to dict.
2. add args.use_llm_runtime to make extension could test llmruntime example.
```
(starcoder) changwa1@ac-spr-2t:~/changwa1/itrex-py310/examples/huggingface/pytorch/text-generation/quantization$ python run_generation.py  --model facebook/opt-125m --sq --recipes "{'smooth_quant': True, 'smooth_quant_args': {'alpha': 'auto', 'folding': False, 'default_alpha': 0.8, 'auto_alpha_args': {'alpha_min': 0.75, 'alpha_max': 0.99, 'alpha_step': 0.01, 'shared_criterion': 'max'}}}"
> /mnt/data2/changwa1/itrex-py310/examples/huggingface/pytorch/text-generation/quantization/run_generation.py(211)<module>()
-> if args.recipes:
(Pdb) p args.use_llm_runtime
False
(Pdb) exit
```
```
(starcoder) changwa1@ac-spr-2t:~/changwa1/itrex-py310/examples/huggingface/pytorch/text-gener …
```
=> [LLM example]Parser args.recipes to dict and add args.use_llm_runtime

intel_extension_for_transformers/neural_chat/models/model_utils.py, intel_extension_for_transformers/neural_chat/tests/ci/api/test_chatbot_build_api.py, intel_extension_for_transformers/neural_chat/tests/ci/api/test_chatbot_normal.py, intel_extension_for_transformers/neural_chat/tests/ci/api/test_inference.py, intel_extension_for_transformers/neural_chat/tests/ci/api/test_rag.py, intel_extension_for_transformers/neural_chat/tests/nightly/models/test_neuralchat.py, intel_extension_for_transformers/neural_chat/tests/nightly/plugins/video/test_sadtalker.py
bug fix
Fix UT issues on Habana
All the UT cases can pass on the Habana HPU devices.
Local test and pre-CI test
None.
=> [NeuralChat] Fix UT issues on Habana

intel_extension_for_transformers/langchain/embeddings/optimized_instructor_embedding.py, intel_extension_for_transformers/langchain/embeddings/optimized_sentence_transformers.py, intel_extension_for_transformers/langchain/embeddings/utils.py, intel_extension_for_transformers/neural_chat/tests/ci/api/test_chatbot_build_api.py
bug fix
Fix embeddings to support local file
CI
No
=> Fix embeddings to support local file

README.md
Documentation 
n/a
n/a
n/a
n/a
=> [Doc] update data format and release data

examples/huggingface/pytorch/text2text-generation/requirements.txt
bug fix
No API changed
Fixed import error for T5 text2text generation example.
Run example successfully with accuracy.
local tested
=> Fixed example error for T5 text2text generation

intel_extension_for_transformers/llm/quantization/utils.py
fixed typo.
successfull -> successfully
=> [LLM] Update utils.py

docs/weightonlyquant.md
=> [Doc] Add doc of save & load low bit model in CPU

docker/Dockerfile_chatbot, examples/huggingface/pytorch/language-modeling/nas/README.md, intel_extension_for_transformers/neural_chat/docker/Dockerfile
update datasets version for docker build
=> update datasets version for docker

intel_extension_for_transformers/llm/runtime/graph/__init__.py, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_llama.py, setup.py
=> [LLM Runtime] support neural chat on windows with magicoder

examples/huggingface/pytorch/text-generation/quantization/run_generation.py, intel_extension_for_transformers/transformers/modeling/modeling_auto.py, intel_extension_for_transformers/transformers/utils/__init__.py, intel_extension_for_transformers/transformers/utils/config.py, intel_extension_for_transformers/transformers/utils/utility.py
Disable SQ calibration dataset shuffle by "--calib_shuffle False" 
=> [LLM example] add calib_shuffle args for text-generation example

examples/huggingface/pytorch/text-generation/quantization/llm_quantization_recipes.md
Add documentation for LLM quantization recipes.
SmoothQuant/Weight-Only Quantization command.
no
no
no
=> Add documentation for LLM quantization recipes.

examples/huggingface/tensorflow/text-classification/quantization/ptq/requirements.txt
update requirements for tensorflow example
=> add accelerate

examples/huggingface/tensorflow/language-modeling/quantization/ptq/requirements.txt, examples/huggingface/tensorflow/multiple-choice/quantization/requirements.txt, examples/huggingface/tensorflow/token-classification/quantization/requirements.txt
add accelerate for tensorflow examples
=> add accelerate for tensorflow examples

examples/huggingface/pytorch/text-generation/quantization/llm_quantization_recipes.md
update Llama-2-13b-hf command
no
no
no
=> update Llama-2-13b-hf command

intel_extension_for_transformers/neural_chat/tests/ci/api/test_chatbot_build_api.py
bug fix
Fix unit test issues caused by the activation of different plugins
The unit test can run without error.
Pre-CI test.
None.
=> [NeuralChat] Fix unit test issues caused by the activation of different plugins

intel_extension_for_transformers/neural_chat/pipeline/plugins/prompt/prompt_template.py
change the position of the user query to get a better performance.
=> [NeuralChat] Optimize the prompt follow the suggestion from cnvrg.io team

intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/README.md
add a comprehensive readme for the new langchain-based RAG system
=> [NeuralChat] Update the readme for RAG

docs/papers/efficient_LLM_inference_on_cpus.md
add  tutorial to reproduce paper's performance
=> add paper documents

.github/workflows/script/unitTest/run_unit_test_neuralchat.sh, .github/workflows/unit-test-neuralchat.yml, intel_extension_for_transformers/neural_chat/tests/requirements.txt
=> try remove paddle speed limitation

.github/workflows/script/unitTest/run_unit_test_neuralchat.sh, .github/workflows/unit-test-neuralchat.yml, .github/workflows/unit-test-optimize.yml
recover limitation for paddle speech
https://github.com/PaddlePaddle/PaddleSpeech/issues/3485#issuecomment-1715145045
=> Fix neuralchat ut requirement

intel_extension_for_transformers/llm/evaluation/lm_eval/models/huggingface.py
=> fix Qwen-72b eval precision issue

intel_extension_for_transformers/neural_chat/chatbot.py, intel_extension_for_transformers/neural_chat/models/base_model.py, intel_extension_for_transformers/neural_chat/models/model_utils.py, intel_extension_for_transformers/neural_chat/tests/nightly/models/test_phi2.py
feature
Support Phi-2 model
Users can run Phi-2 model using NeuralChat
None.
=> [NeuralChat] Support Phi-2 model

examples/huggingface/pytorch/text-generation/quantization/llm_quantization_recipes.md
=> Fix doc about LLM example recipes.

intel_extension_for_transformers/neural_chat/examples/finetuning/multi_modal/README.md, intel_extension_for_transformers/neural_chat/examples/finetuning/multi_modal/train.py, intel_extension_for_transformers/transformers/modeling/llava_models/__init__.py, intel_extension_for_transformers/transformers/modeling/llava_models/llava_llama.py
API changed for different version transformers for llama series models because of breaking changes
support llama series model for llava finetuning
=> [NeuralChat] support llama series model for llava finetuning.

.github/workflows/script/unitTest/run_unit_test_neuralchat.sh
change install queue to make sure torch is installed at the last
=> change install queue

.github/workflows/script/unitTest/run_unit_test_optimize.sh, docker/Dockerfile_chatbot, intel_extension_for_transformers/neural_chat/docker/Dockerfile
remove restrict for transformers and datasets
=> remove transformers==4.34.1

intel_extension_for_transformers/neural_chat/examples/finetuning/instruction/finetune_clm.py
use "from intel_extension_for_transformers.utils.device_utils import is_hpu_available"
=> [NeuralChat] fix finetuning example import issue.

examples/huggingface/pytorch/text-generation/quantization/run_generation.py, intel_extension_for_transformers/llm/quantization/gptq_utils.py, intel_extension_for_transformers/llm/quantization/nn/modules.py, intel_extension_for_transformers/llm/quantization/utils.py
=> remove GPTQ llama dependence

intel_extension_for_transformers/neural_chat/tests/ci/api/test_chatbot_exception.py, intel_extension_for_transformers/neural_chat/tests/nightly/models/test_phi2.py
bug fix
Fix UT issues
The nightly test can pass.
Local test, pre-CI and nightly test.
None.
=> [NeuralChat] Fix UT issues

intel_extension_for_transformers/transformers/modeling/modeling_auto.py, tests/CI/test_quantization.py
https://github.com/intel/neural-compressor/pull/1554 depend on INC PR.
=> Fix TEQ UT

intel_extension_for_transformers/llm/runtime/graph/tests/test_llm_runtime.py
=> [LLM Runtime]Add GGUF API UT

conda_meta/meta.yaml
=> update conda meta version

intel_extension_for_transformers/neural_chat/tests/nightly/models/test_error_code.py
bug fix
Fix nightly unit test issue
The nightly UT can pass.
Local test and nightly test.
None.
=> [NeuralChat] Fix nightly unit test issue

.github/workflows/script/unitTest/env_setup.sh
due to transformers latest release 4.37 has compatibility, need to limit transformers to 4.36.2
=> restrain transformers to 4.36.2

.github/workflows/unit-test-engine.yml, .github/workflows/unit-test-neuralchat.yml, .github/workflows/unit-test-optimize.yml
=> fix docker clean when generating report

.github/workflows/script/formatScan/pylint.sh, .github/workflows/script/unitTest/env_setup.sh, .github/workflows/script/unitTest/run_unit_test_llmruntime.sh, examples/huggingface/neural_speed/perplexity/requirements.txt, intel_extension_for_transformers/llm/runtime/graph/requirements.txt, intel_extension_for_transformers/neural_chat/tests/requirements.txt, tests/requirements.txt
replace neural-speed build from source with pypi install neural-speed
=> add pypi install neural-speed

.github/workflows/script/formatScan/nlp_dict.txt, README.md, docs/weightonlyquant.md, intel_extension_for_transformers/llm/quantization/nn/modules.py, intel_extension_for_transformers/neural_chat/models/model_utils.py, intel_extension_for_transformers/transformers/modeling/modeling_auto.py, intel_extension_for_transformers/transformers/utils/config.py, tests/CI/test_weight_only.py
documentation 
n/a
n/a
n/a
n/a
=> add validated sw

examples/huggingface/pytorch/text-generation/quantization/run_generation.py
=> Fix LLM example model eval

intel_extension_for_transformers/llm/quantization/utils.py, intel_extension_for_transformers/transformers/modeling/modeling_auto.py, intel_extension_for_transformers/transformers/utils/config.py
bug fix
No API changed
fixed example of cpu woq accuracy issue
Run the example of CPU WOQsuccessfully  with correct accuracy
Local tested
=> fixed example of cpu woq accuracy issue

intel_extension_for_transformers/transformers/modeling/modeling_auto.py, intel_extension_for_transformers/transformers/utils/config.py
=> [LLM Runtime] Update parameters for llm runtime

.github/workflows/sample_data/alpaca_data_sample_45.json
=> recover validation data

.github/workflows/script/unitTest/run_unit_test_neuralchat.sh, examples/huggingface/pytorch/code-generation/quantization/requirements.txt, examples/huggingface/pytorch/image-classification/deployment/imagenet/vit/requirements.txt, examples/huggingface/pytorch/image-classification/quantization/requirements.txt, examples/huggingface/pytorch/question-answering/dynamic/requirements.txt, examples/huggingface/pytorch/textual-inversion/quantization/requirements.txt, intel_extension_for_transformers/neural_chat/tests/requirements.txt, tests/requirements.txt, workflows/hf_finetuning_and_inference_nlp/requirements.txt
restrain torch/ipex version to make them match
=> update torch version

.github/workflows/sample_data/alpaca_data_sample_45.json, intel_extension_for_transformers/neural_chat/examples/finetuning/multi_modal/README.md, intel_extension_for_transformers/neural_chat/examples/finetuning/multi_modal/gaudi_spawn.py, intel_extension_for_transformers/neural_chat/examples/finetuning/multi_modal/llava_utils.py, intel_extension_for_transformers/neural_chat/examples/finetuning/multi_modal/scripts/finetune.sh, intel_extension_for_transformers/neural_chat/examples/finetuning/multi_modal/scripts/finetune_lora.sh, intel_extension_for_transformers/neural_chat/examples/finetuning/multi_modal/scripts/pretrain.sh, intel_extension_for_transformers/neural_chat/examples/finetuning/multi_modal/scripts/zero2.json, intel_extension_for_transformers/neural_chat/examples/finetuning/multi_modal/scripts/zero3.json, intel_extension_for_transformers/neural_chat/examples/finetuning/multi_modal/train.py, intel_extension_for_transformers/transformers/modeling/llava_models/llava_arch.py, intel_extension_for_transformers/transformers/modeling/llava_models/llava_llama.py, intel_extension_for_transformers/transformers/modeling/llava_models/llava_mistral.py
feature/bug enhancement that supports static shape input for gaudi2
rewrite finetuning data preprocessing with static shape for Gaudi2
fix issue: [#1201 ](https://github.com/intel/intel-extension-for-transformers/issues/1201)
=> rewrite finetuning data preprocessing with static shape for Gaudi2.

intel_extension_for_transformers/neural_chat/examples/finetuning/multi_modal/llava_trainer.py, intel_extension_for_transformers/neural_chat/examples/finetuning/multi_modal/llava_utils.py
Bug fix
Fixes a few minor errors for the trainer to save when fine tuning on HPU.
=> [NeuralChat] Fix errors in trainer save

docker/Dockerfile_chatbot, intel_extension_for_transformers/neural_chat/docker/Dockerfile
Use `python setup.py install` replace `pip install -v .`
no
no
no
no
=> [NeuralChat] fix itrex install

intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/requirements.txt
bug fix
Add requirements.txt for retrieval plugin
Users can install required software packages based on the provided requirements.txt.
None.
=> [NeuralChat] Add requirements.txt for retrieval plugin

examples/huggingface/neural_speed/README.md, examples/huggingface/neural_speed/runtime_example.py
not
updata neural speed example
=> [LLM Runtime]updata neural speed example

.pre-commit-config.yaml, pyproject.toml
remove pyproject.toml
no
no
no
=> remove pyproject.toml

intel_extension_for_transformers/neural_chat/models/base_model.py, intel_extension_for_transformers/neural_chat/tests/ci/server/test_textchat_server.py, workflows/chatbot/inference/generate.py
enhancement
allow users to set system prompts
allow users to set system prompts
ut
None
=> [NeuralChat] add customized system prompts

intel_extension_for_transformers/neural_chat/tests/ci/server/test_textchat_server.py
bug fix
Current main baseline UT has a bug
Fix main branch baseline UT
ut
None
=> [NeuralChat] fix system prompt

README.md, docs/installation.md
update installation requirement
=> update system libs

docker/README_chatbot.md
(1) fix docker readme
(2) update neuralchat requirement
=> fix readme

examples/huggingface/pytorch/code-generation/quantization/requirements.txt, examples/huggingface/pytorch/text-generation/quantization/requirements.txt, tests/requirements.txt
=> remove optimum-intel commit limit

docker/README_chatbot.md, docs/installation.md, intel_extension_for_transformers/neural_chat/README.md, intel_extension_for_transformers/neural_chat/requirements.txt, intel_extension_for_transformers/neural_chat/requirements_cpu.txt, intel_extension_for_transformers/neural_chat/requirements_hpu.txt, intel_extension_for_transformers/neural_chat/requirements_pc.txt, intel_extension_for_transformers/neural_chat/requirements_xpu.txt
=> Update neuralchat readme

intel_extension_for_transformers/neural_chat/README.md, intel_extension_for_transformers/neural_chat/server/restful/faceanimation_api.py, intel_extension_for_transformers/neural_chat/server/restful/plugin_audio_api.py
bug fix
API  not changed
Fix pydub library import issues.
Users can run NeuralChat without errors.
None.
=> [NeuralChat] Fix pydub library import issues

intel_extension_for_transformers/neural_chat/examples/finetuning/instruction/README.md
update finetuning validated model.
=> [NeuralChat] update finetuning validated model

intel_extension_for_transformers/neural_chat/chatbot.py, intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/parser/context_utils.py, intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/parser/html_parser.py, intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/requirements.txt, intel_extension_for_transformers/neural_chat/tests/requirements.txt
Enable a more efficient and accurate way to parse text and image.
=> [NeuralChat] Retrieval pdf figure to text

intel_extension_for_transformers/neural_chat/tools/rome/examples/README.md, intel_extension_for_transformers/neural_chat/tools/rome/examples/editor.py, intel_extension_for_transformers/neural_chat/tools/rome/examples/example.json
documentation change
Refined readme of ROME.
=> [NeuralChat] Refined readme of ROME

intel_extension_for_transformers/neural_chat/server/restful/textchat_api.py
bug fix
Fix local model check issue
Local model can pass the model checking.
None.
=> [NeuralChat] Fix local model check issue

intel_extension_for_transformers/neural_chat/models/model_utils.py, intel_extension_for_transformers/neural_chat/models/qwen_model.py
bug fix
Fix Qwen chat model output undesirable on HPU issue caused by input padding.
pass test 
UT
=> [NeuralChat] Fix Qwen chat model output undesirable on HPU issue caused by input padding

examples/mlperf/neural_speed/README.md
=> Add MLPerf Example

intel_extension_for_transformers/neural_chat/models/base_model.py, intel_extension_for_transformers/neural_chat/models/model_utils.py, intel_extension_for_transformers/neural_chat/requirements.txt, intel_extension_for_transformers/neural_chat/requirements_cpu.txt, intel_extension_for_transformers/neural_chat/requirements_hpu.txt, intel_extension_for_transformers/neural_chat/requirements_pc.txt, intel_extension_for_transformers/neural_chat/requirements_xpu.txt, intel_extension_for_transformers/neural_chat/tests/nightly/models/test_biogpt.py, intel_extension_for_transformers/neural_chat/tests/requirements.txt
feature
Support microsoft/biogpt model in NeuralChat.
microsoft/biogpt model can run well in NeuralChat
sacremoses
=> [NeuralChat] Support microsoft/biogpt model as per the request

examples/huggingface/tensorflow/language-modeling/quantization/run_clm.py
bug fix
fix distilgpt2 tf signature issue
bug fix
test
None
=> fix distilgpt2 tf signature issue

intel_extension_for_transformers/llm/finetuning/finetuning.py, intel_extension_for_transformers/neural_chat/examples/finetuning/instruction/README.md
example
Added finetuning example for gemma-2b on ARC.
pass local test
follow readme
=> [NeuralChat] Added finetuning example for gemma-2b on ARC

examples/huggingface/pytorch/code-generation/quantization/requirements.txt, examples/huggingface/pytorch/code-generation/quantization/run_generation.py, examples/huggingface/pytorch/text-generation/quantization/requirements.txt, examples/huggingface/pytorch/text-generation/quantization/run_generation.py, intel_extension_for_transformers/llm/quantization/utils.py, intel_extension_for_transformers/transformers/modeling/modeling_auto.py, requirements.txt, tests/CI/test_quantization.py, tests/requirements.txt
upgrade auto-round commit
fix auto-round calib dataloader
=> Improve WOQ algo autoround

intel_extension_for_transformers/neural_chat/pipeline/plugins/audio/README.md, intel_extension_for_transformers/neural_chat/pipeline/plugins/audio/asr.py, intel_extension_for_transformers/neural_chat/pipeline/plugins/audio/tts.py
bug fix
Fix audio plugin sample code issue and provide a way to set tts/asr model path
Users can follow the audio plugin README to create audio related code and export environment variable to set tts/asr model path.
None.
=> [NeuralChat] Fix audio plugin sample code issue and provide a way to set tts/asr model path

intel_extension_for_transformers/neural_chat/examples/finetuning/instruction/README.md
documentation
Added description of task argument for each finetuning dataset.
=> [NeuralChat] Added description of task argument for each finetuning dataset in NeuralChat

docs/weightonlyquant.md, examples/huggingface/pytorch/text-generation/quantization/README.md, examples/huggingface/pytorch/text-generation/quantization/requirements_GPU.txt
Documentation
No API changed
Update WOQ doc and example README
=> Update WOQ doc and example README

intel_extension_for_transformers/transformers/modeling/modeling_auto.py
get config need add args trust_remote_code.
=> Fix modeling_auto trust_remote_code issue

docs/weightonlyquant.md, intel_extension_for_transformers/transformers/modeling/modeling_auto.py
bug fix 
https://github.com/intel/intel-extension-for-transformers/issues/1352
=> update demo for ipex gpu

intel_extension_for_transformers/neural_chat/assets/docs/sample_workshop.txt, intel_extension_for_transformers/neural_chat/docs/notebooks/workshop/01_quickstart_neuralchat.ipynb, intel_extension_for_transformers/neural_chat/docs/notebooks/workshop/README.md, intel_extension_for_transformers/neural_chat/docs/notebooks/workshop/env_setup.sh
Updated README, bug fixes, improvements.
Add setup_env.sh to install all requirements
Add instructions in README to create own conda environment.
Add descriptions in the notebook
Add latency measurements of BF16 and INT8/INT4 with FP32
Add usage with llama2 and print out latencies of FP32 vs BF16
Replace retrieval example with a better question: Super Bowl 58 winner and score?
JIRA ticket: https://jira.devtools.intel.com/browse/NLPTOOLKIU-1250
Taking feedback from person who hosted workshop at a hackathon and making improvements.
Tested on an SPR lab machine with the jupyter notebook opened on a web browser.
Added installation of notebook and pydub.
=> Update Quickstart NeuralChat notebook for workshops

intel_extension_for_transformers/llm/evaluation/lm_eval/models/huggingface.py
=> Fix lm-eval neuralspeed loading model

intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/parser/context_utils.py
Expand the scope of the available character types from the loaded documents.
=> [NeuralChat]Update the character checking function to enable the Chinese character

intel_extension_for_transformers/neural_chat/models/model_utils.py
bug fix
Enlarge the context window for HPU graph recompile
The models with long context window can work well on Habana Gaudi.
None.
=> [NeuralChat] Enlarge the context window for HPU graph recompile

examples/huggingface/pytorch/text-classification/deployment/emotion/distilbert_base_uncased/executor_utils.py
=> [Example] update the deprate example dataset load

intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/requirements.txt, intel_extension_for_transformers/neural_chat/tests/requirements.txt
=> restrain langchain community version

intel_extension_for_transformers/transformers/utils/config.py
QuantizationMixin raised by transformers equal or higher than 4.32.0, so add alias for version lower than 4.32.0
=> add version limit for WOQConfig

intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/retrieval_agent.py, intel_extension_for_transformers/neural_chat/tests/ci/plugins/retrieval/test_parameters.py
feature
API changed or not: yes
Support IPEX bf16 & fp32 optimization for emebedding model by adding a new arg `embedding_precision`.
```python
plugins.retrieval.enable = True
plugins.retrieval.args['embedding_model'] = "hkunlp/instructor-large"
plugins.retrieval.args['precision'] = "bf16"
plugins.retrieval.args["input_path"] = './cnvrg_docs_rag/'
plugins.retrieval.args["persist_dir"] = "./test_dir"
config = PipelineConfig(model_name_or_path="facebook/opt-125m", plugins=plugins)
chatbot = build_chatbot(config)
response = chatbot.predict("Who are the founders of cnvrg.io?")
```
=> Support IPEX bf16 & fp32 optimization for emebedding model 

intel_extension_for_transformers/llm/finetuning/data_utils.py, intel_extension_for_transformers/llm/finetuning/finetuning.py, intel_extension_for_transformers/neural_chat/config.py, intel_extension_for_transformers/neural_chat/examples/finetuning/image_to_text/README.md, intel_extension_for_transformers/neural_chat/examples/finetuning/image_to_text/finetune_clm.py, intel_extension_for_transformers/neural_chat/examples/finetuning/image_to_text/requirements.txt
feature
Enabled image2text finetuning and added an example.
follow readme
=> [NeuralChat] Enabled image2text finetuning and added an example

intel_extension_for_transformers/llm/evaluation/lm_eval/evaluator.py, intel_extension_for_transformers/llm/evaluation/lm_eval/models/huggingface.py, intel_extension_for_transformers/llm/finetuning/eval_utils.py, intel_extension_for_transformers/llm/finetuning/finetuning.py, intel_extension_for_transformers/neural_chat/config.py
1. support lm_eval tasks evaluation during training. 
2. optimize lm_eval on Gaudi.
=> [NeuralChat] enable lm_eval during training.

intel_extension_for_transformers/langchain/vectorstores/chroma.py, intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/README.md, intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/retrieval_agent.py, intel_extension_for_transformers/neural_chat/prompts/prompt.py, intel_extension_for_transformers/neural_chat/tests/ci/plugins/retrieval/test_parameters.py
add more RAG readme component
add the length limitation to avoid too short or void chuck
fix chroma build function bug
=> [NeuralChat] Add readme, add content length filter, fix build error

intel_extension_for_transformers/neural_chat/docs/advanced_features.md
fix link path in advanced_features.md
=> [NeuralChat] Refine document

intel_extension_for_transformers/langchain/retrievers/child_parent_retriever.py
fix ut errors in https://jira.devtools.intel.com/browse/NLPTOOLKIU-1280
=> [NeuralChat] Fix index error in Child-parent retriever

intel_extension_for_transformers/transformers/llm/quantization/nn/modules.py, intel_extension_for_transformers/transformers/modeling/modeling_auto.py
for gptq algo --desc_act --static_group usage.
option 1: --desc_act , benefits, g_idx raised, it could add memory
option 2: --desc_act --static_group , benefits，no g_idx and save memory
option3: --static_group, no benefits (Not recommended)
=> Fix gptq desc_act and static_group

intel_extension_for_transformers/transformers/modeling/modeling_auto.py, tests/CI/test_weight_only.py
=> Fix WOQ huggingface model loading

intel_extension_for_transformers/neural_chat/tests/ci/tools/test_embedding_finetune.py
Update input path in test_embedding_finetune.py
=> [NeuralChat] Fix path in UT

.github/workflows/script/formatScan/pylint.sh
=> restrain transformers

examples/huggingface/pytorch/code-generation/quantization/run_generation.py, examples/huggingface/pytorch/text-generation/quantization/run_generation.py, intel_extension_for_transformers/transformers/utils/utility.py
[[NLPTOOLKIU-1299] smoothquant qconfig restore error - IT JIRA (Supports IC/ITS Data) (intel.com)](https://jira.devtools.intel.com/browse/NLPTOOLKIU-1299)
https://jira.devtools.intel.com/browse/NLPTOOLKIU-1298
=> Fix SQ model restore loading

examples/huggingface/pytorch/language-modeling/pruning/run_clm_sparsegpt.py, examples/huggingface/pytorch/language-modeling/pruning/scripts/run_llm_sparseGPT.sh
=> update sparseGPT example

examples/huggingface/pytorch/question-answering/deployment/squad/MLperf_example/datasets/tokenization.py, examples/huggingface/pytorch/question-answering/deployment/squad/MLperf_example/tokenization.py
Changed regular expression to add support of the unicode characters processing and make code simple
Signed-off-by: Evgenii K <kublin@it8.ru>
=> Changed regular expression

examples/huggingface/pytorch/text-generation/quantization/run_generation_gpu_woq.py
bug fix
No API changed
Fixed origin model benchmark error in intel GPU WOQ example.
=> Fixed exmple error for Intel GPU WOQ

intel_extension_for_transformers/transformers/modeling/modeling_auto.py
Dug fix
No API changed
Fixed import error for neural_speed
Running neuralSpeed examples successfully。
Local tested
=> Fixed import error for neural_speed

README.md
=> [Doc] Fix README ITREX V1.3 NS link

intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/requirements.txt
requirements
Update retrieval `requirements.txt` of `unstructured[all-docs]` to support file types of `docx`, `pptx` and others.
With the updated `requirements.txt`, RAG service will support uploading docx/pptx files to create knowledge base.
Local tested on SPR.
`unstructured[all-docs]` is introduced.
=> [NeuralChat] Update retrieval requirements

examples/huggingface/pytorch/code-generation/quantization/run_generation.py, intel_extension_for_transformers/transformers/modeling/modeling_auto.py
https://jira.devtools.intel.com/browse/NLPTOOLKIU-1310
https://jira.devtools.intel.com/browse/NLPTOOLKIU-1311
=> check and convert contiguous tensor when model saving

examples/huggingface/pytorch/code-generation/quantization/run_generation.py, examples/huggingface/pytorch/text-generation/quantization/llm_quantization_recipes.md, examples/huggingface/pytorch/text-generation/quantization/run_generation.py
- Add int4 GPTQ & AutoRound recipes
- bug fix
- Add tiiuae/falcon-7b,  baichuan-inc/Baichuan-13B-Chat, baichuan-inc/Baichuan2-13B-Chat, baichuan-inc/Baichuan2-7B-Chat, bigscience/bloom-1b7, databricks/dolly-v2-12b, EleutherAI/gpt-neox-20b, mistralai/Mistral-7B-v0.1, THUDM/chatglm2-6b, THUDM/chatglm3-6b scripts
no
local test
no
=> update LLM recipes

intel_extension_for_transformers/neural_chat/server/restful/codegen_api.py
bug fix
Fix code generation code format issue, need to encode the content to avoid the "\n\r" being removed.
The code format issue can be fixed.
Local test.
None
=> [NeuralChat] Fix code generation code format issue

examples/huggingface/pytorch/text-generation/quantization/README.md, examples/huggingface/pytorch/text-generation/quantization/run_generation.py, examples/huggingface/pytorch/text-generation/quantization/run_generation_gpu_woq.py
Align parameters for WOQ pre-CI test. 
No API changed
Align parameters for WOQ pre-CI test. 
pre-CI test successfully
Local tested
=> Unify the parameters for woq examples by CPU and GPU

examples/huggingface/pytorch/code-generation/quantization/run_generation.py
=> fix code-generation params issue

examples/huggingface/pytorch/text-generation/quantization/run_generation.py, examples/huggingface/pytorch/text-generation/quantization/run_generation_gpu_woq.py
=> fix lm_eval params

intel_extension_for_transformers/neural_chat/server/restful/textchat_api.py
feature
Support deepspeed for textchat API
When starting services using deepspeed (multi-sockets or multi-nodes), textchat API will be able to launch multiple threads of executors.
None.
=> [NeuralChat] Support deepspeed for textchat API

examples/huggingface/pytorch/text-generation/quantization/run_generation.py, intel_extension_for_transformers/transformers/llm/evaluation/lm_eval/evaluator.py
remove hardcode and fix wrong typing.
=> fix typing

examples/huggingface/pytorch/text-generation/quantization/run_generation_gpu_woq.py
=> Update run_generation_gpu_woq.py for auto round

intel_extension_for_transformers/neural_chat/examples/plugins/table_extraction/README.md, intel_extension_for_transformers/neural_chat/examples/plugins/table_extraction/configs/detection_config.json, intel_extension_for_transformers/neural_chat/examples/plugins/table_extraction/configs/structure_config.json, intel_extension_for_transformers/neural_chat/examples/plugins/table_extraction/extract_tables.py, intel_extension_for_transformers/neural_chat/examples/plugins/table_extraction/models/__init__.py, intel_extension_for_transformers/neural_chat/examples/plugins/table_extraction/models/backbone.py, intel_extension_for_transformers/neural_chat/examples/plugins/table_extraction/models/detr.py, intel_extension_for_transformers/neural_chat/examples/plugins/table_extraction/models/detr_multi.py, intel_extension_for_transformers/neural_chat/examples/plugins/table_extraction/models/matcher.py, intel_extension_for_transformers/neural_chat/examples/plugins/table_extraction/models/position_encoding.py, intel_extension_for_transformers/neural_chat/examples/plugins/table_extraction/models/segmentation.py, intel_extension_for_transformers/neural_chat/examples/plugins/table_extraction/models/transformer.py, intel_extension_for_transformers/neural_chat/examples/plugins/table_extraction/requirements.txt, intel_extension_for_transformers/neural_chat/examples/plugins/table_extraction/util/__init__.py, intel_extension_for_transformers/neural_chat/examples/plugins/table_extraction/util/box_ops.py, intel_extension_for_transformers/neural_chat/examples/plugins/table_extraction/util/misc.py, intel_extension_for_transformers/neural_chat/examples/plugins/table_extraction/util/plot_utils.py, intel_extension_for_transformers/neural_chat/examples/plugins/table_extraction/util/postprocess.py
Added example for table extraction, and enabled multi-page table handling pipeline.
example
follow the README
=> Added example for table extraction, and enabled multi-page table handling pipeline

examples/.config/pytorch_optimize.json
=> support ipex arc test

intel_extension_for_transformers/neural_chat/README.md, intel_extension_for_transformers/neural_chat/examples/deployment/codegen/backend/pc/gguf/README.md, intel_extension_for_transformers/neural_chat/examples/deployment/codegen/backend/pc/gptq/README.md, intel_extension_for_transformers/neural_chat/examples/deployment/codegen/backend/pc/woq/README.md, intel_extension_for_transformers/neural_chat/models/model_utils.py, intel_extension_for_transformers/neural_chat/requirements.txt, intel_extension_for_transformers/neural_chat/requirements_cpu.txt, intel_extension_for_transformers/neural_chat/requirements_hpu.txt, intel_extension_for_transformers/neural_chat/requirements_win.txt, intel_extension_for_transformers/neural_chat/requirements_xpu.txt
bug fix
Update code for running on Windows
Users can use NeuralChat on Windows to build Chatbot.
None.
=> [NeuralChat] Update code for running on Windows

intel_extension_for_transformers/neural_chat/server/neuralchat_server.py
bug fix
Fix TPP support for single socket
Even for single socket, the TPP also can run well without parallel.
None.
=> [NeuralChat] Fix TPP support for single socket

intel_extension_for_transformers/neural_chat/docs/notebooks/deploy_chatbot_on_spr_with_tp.ipynb
documentation
Add notebook for chatbot with Tensor Parallel.
Users will be able to run chatbot on multi sockets with Tensor Parallel.
Local tested.
None.
=> [NeuralChat] Add notebook for chatbot with TP

README.md, docs/weightonlyquant.md, examples/huggingface/pytorch/text-generation/quantization/README.md
=> doc: add example for autoround and llama3 on intel gpu

.github/workflows/script/unitTest/run_unit_test_optimize.sh
=> update ci script

intel_extension_for_transformers/neural_chat/examples/deployment/codegen/backend/xeon/ipex/README.md, intel_extension_for_transformers/neural_chat/examples/deployment/codegen/backend/xeon/ipex/codegen.yaml, intel_extension_for_transformers/neural_chat/examples/deployment/codegen/backend/xeon/ipex/run.sh, intel_extension_for_transformers/neural_chat/examples/deployment/codegen/backend/xeon/ipex/run_code_gen.py, intel_extension_for_transformers/neural_chat/examples/deployment/codegen/backend/xeon/tpp/README.md, intel_extension_for_transformers/transformers/modeling/modeling_auto.py
Document refine
Refine the README for TPP usage
User can follow the TPP readme to deploy the chatbot service using TPP and IPEX.
None.
=> Refine the README for TPP usage

intel_extension_for_transformers/transformers/modeling/modeling_auto.py
=> improve low bits model loading

intel_extension_for_transformers/transformers/mixture/auto_distillation.py
bug fix
fix tf autodistill bug of transformers>=4.37
None
None
=> fix tf autodistill bug of transformers>=4.37

.github/workflows/unit-test-optimize.yml, .github/workflows/windows-test.yml, examples/.config/pytorch_optimize.json, examples/huggingface/pytorch/text-generation/quantization/run_tuning.sh
=> add qbits ci

intel_extension_for_transformers/qbits/.clang-format, intel_extension_for_transformers/qbits/dispatcher/src/bestla_packq_impl.cpp, intel_extension_for_transformers/qbits/dispatcher/src/bestla_weightonly_dispatcher.cpp, intel_extension_for_transformers/qbits/qbits.cpp
=> add bias internal convertion in qbits

docker/Dockerfile_chatbot, intel_extension_for_transformers/neural_chat/docker/Dockerfile, intel_extension_for_transformers/neural_chat/docker/code_generation/hpu/Dockerfile, intel_extension_for_transformers/neural_chat/docker/finetuning/Dockerfile, intel_extension_for_transformers/neural_chat/docker/text_generation/hpu/Dockerfile
=> update deepspeed version for habana docker

intel_extension_for_transformers/tools/utils.py, requirements.txt, setup.py
=> fix is_intel_gpu_available

intel_extension_for_transformers/transformers/llm/evaluation/lm_eval/models/huggingface.py
to support INC SQ example both for 2.x API and 3.x API.
=> lm-eval supports tuple output return

examples/huggingface/pytorch/text-generation/quantization/run_generation_gpu_woq.py
=> [GPU] script for phi3 on windows

examples/huggingface/pytorch/text-generation/quantization/run_tuning.sh
add params in examples scripts
=> add schema to control asym/sym

examples/huggingface/pytorch/text-generation/quantization/run_generation_cpu_woq.py, intel_extension_for_transformers/transformers/utils/config.py
=> Update config.py due to qbits expanded asym scheme and scale scope

.github/workflows/llm-test.yml, .github/workflows/optimize-test.yml, .github/workflows/script/SparseLibCI/generate_sparse_lib.sh, .github/workflows/unit-test-engine.yml
=> fix url issue

intel_extension_for_transformers/transformers/llm/quantization/utils.py
=> Remove the useless code about ipex cpu woq

.github/workflows/probot.yml
=> fix CI-summary branch

examples/huggingface/pytorch/question-answering/deployment/squad/ipex/bert_large/requirements.txt, examples/huggingface/pytorch/question-answering/deployment/squad/ipex/distilbert_base_uncased/requirements.txt, examples/huggingface/pytorch/question-answering/deployment/squad/ipex/distilbert_base_uncased_sparse/requirements.txt, intel_extension_for_transformers/transformers/runtime/test/pytest/requirements.txt
=> remove limitation for torch

examples/huggingface/pytorch/text-generation/quantization/run_generation_cpu_woq.py, intel_extension_for_transformers/transformers/llm/quantization/utils.py, intel_extension_for_transformers/transformers/utils/config.py
follows INC PR: https://github.com/intel/neural-compressor/pull/1656
=> add true_sequential for WOQ GPTQ

.github/workflows/script/unitTest/run_unit_test_engine.sh, intel_extension_for_transformers/transformers/runtime/test/pytest/test_static_compressed_buffer.py
=> update onnxruntime version for engine

intel_extension_for_transformers/transformers/utils/config.py
=> Fix gptq true_sequential default False

intel_extension_for_transformers/neural_chat/models/model_utils.py, intel_extension_for_transformers/transformers/modeling/modeling_auto.py, tests/Nightly/test_neural_speed.py
align with HF API https://huggingface.co/docs/transformers/en/gguf 
=> Align gguf_file with HF API

README.md
=> Add GGUF support in ITREX readme

tests/requirements.txt
=> Fix CI due to optimum-intel upgrade

examples/huggingface/pytorch/code-generation/quantization/requirements.txt, examples/huggingface/pytorch/text-generation/quantization/requirements_GPU.txt, examples/huggingface/pytorch/text-generation/quantization/requirements_cpu_woq.txt, tests/requirements.txt
due to auto-round recent release, the latest version is 0.2.
=> update auto-round version to 0.2

docs/qbits.md
=> update qbits doc

intel_extension_for_transformers/neural_chat/ui/gradio/side_by_side/app.py, intel_extension_for_transformers/neural_chat/ui/gradio/side_by_side/conversation.py
Updated the side-by-side gradio client to make it work with the current backend.
Changes were made to make the client work. Most of the code was taken from the basic client.
the client seems to work now, user can set optimized/baseline clients to compare results
local manual testing was performed
None, same dependencies as in the basic client, nothing was changed
=> [NeuralChat][UI]: updated side_by_side client

README.md, docs/publication.md
documentation 
add publications
n/a
n/a
n/a
=> add publications

intel_extension_for_transformers/neural_chat/examples/quick_start/chatbot/README.md
Update neural_chat quick start example document
=> [DOC] Update example doc

.github/checkgroup.yml, .github/workflows/Scaner_BDBA.yaml, .github/workflows/Scaner_Coverity.yaml, .github/workflows/Scaner_Trivy.yaml, .github/workflows/build-container.yaml, .github/workflows/chatbot-finetune-mpt-7b-chat-hpu.yml, .github/workflows/chatbot-finetune-mpt-7b-chat.yml, .github/workflows/chatbot-inference-llama-2-7b-chat-hf.yml, .github/workflows/chatbot-inference-llama-2-7b_70b-chat-hf-hpu.yml, .github/workflows/chatbot-inference-mpt-7b-chat-hpu.yml, .github/workflows/chatbot-inference-mpt-7b-chat.yml, .github/workflows/chatbot-test.yml, .github/workflows/chatbot_finetuning.yml, .github/workflows/deploy-test.yml, .github/workflows/format_scan.yml, .github/workflows/llm-test.yml, .github/workflows/optimize-test.yml, .github/workflows/publish.yml, .github/workflows/script/launch_llm.sh, .github/workflows/script/models/run_llm.sh, .github/workflows/script/prepare_env_with_conda.sh, .github/workflows/sparse_lib_CI.yml, .github/workflows/trellix.yaml, .github/workflows/unit-test-engine.yml, .github/workflows/unit-test-kernel.yml, .github/workflows/unit-test-neuralchat.yml, .github/workflows/unit-test-neuralspeed.yml, .github/workflows/unit-test-optimize.yml, .github/workflows/windows-test.yml
=> Remove permissions.

SECURITY.md
=> Add OpenSSF Badge

workflows/chatbot/inference/README.md
Typo
Fixed typos and added an extra word to improve a phrase's legibility from README.
Not applicable
Not applicable
Not applicable
=> Fix typo at README.md

examples/huggingface/pytorch/text-generation/inference/run_generation_with_deepspeed.py
This PR introduced optimum-intel to optimize the deepspeed model, it can support high version transformers (v4.41.2), and also fixed some errors.
=> fix deepspeed script and add a optimum-intel option

docs/contributors.md
documentation
add contributors
n/a
n/a
n/a
=> add contributors

workflows/chatbot/inference/backend/fastrag/fastrag_service.py, workflows/chatbot/inference/requirements.txt
https://github.com/intel/intel-extension-for-transformers/security/code-scanning/57
=> solve codescan#57

intel_extension_for_transformers/neural_chat/models/model_utils.py
https://github.com/intel/intel-extension-for-transformers/security/code-scanning/45
https://github.com/intel/intel-extension-for-transformers/security/code-scanning/44
https://github.com/intel/intel-extension-for-transformers/security/code-scanning/43
=> solve codescan#43-45

examples/huggingface/pytorch/question-answering/deployment/squad/ipex/bert_large/requirements.txt, examples/huggingface/pytorch/question-answering/deployment/squad/ipex/distilbert_base_uncased_sparse/requirements.txt
=> update torch version to 2.3.0 in example/requirements.txt

.github/workflows/script/formatScan/pylint.sh, examples/huggingface/pytorch/language-modeling/inference/requirements.txt, examples/huggingface/pytorch/language-modeling/pruning/requirements.txt, examples/huggingface/pytorch/language-modeling/quantization/requirements.txt, examples/huggingface/pytorch/text2text-generation/requirements.txt, examples/modelscope/requirements.txt, intel_extension_for_transformers/neural_chat/requirements_cpu.txt, intel_extension_for_transformers/neural_chat/requirements_hpu.txt, intel_extension_for_transformers/neural_chat/requirements_win.txt, intel_extension_for_transformers/neural_chat/tests/requirements.txt, requirements-cpu.txt
lm-eval update to 0.4.3 and will bring some api change, so set it to 0.4.2, will update to adapt the latest version later.
=> Set lm-eval to 0.4.2

examples/huggingface/pytorch/text-generation/quantization/llm_quantization_recipes.md
=> update recipes to align INC2.6
