setup.py
feature
add SKIP_RUNTIME when running setup.py
change BACKENDS_ONLY to RUNTIME_ONLY
SKIP_RUNTIME=True python setup.py install/develop works well without cmake
local test
=> add SKIP_RUNTIME and RUNTIME_ONLY in setup

intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_utils.cpp, intel_extension_for_transformers/llm/runtime/graph/vectors/cpu/vec_arithmetic.cpp, intel_extension_for_transformers/llm/runtime/graph/vectors/cpu/vec_base.hpp, intel_extension_for_transformers/llm/runtime/graph/vectors/cpu/vec_store.cpp
Fixed a few problems that prevent the code compile and run on AVX2 platforms (with Windows11 in my case). Therefore, I can prepare / update quantized models on my local windows machine and saving disk space on servers~
N/A
`cmake -GNinja -DNE_AVX512=OFF -DNE_AVX512_VBMI=OFF -DNE_AVX512_VNNI=OFF ..`. Commands for model conversion / quantization are the same as that in README.
N/A
=> [CPP Graph] Fix Graph Model quantization on AVX2-only Platforms

intel_extension_for_transformers/neural_chat/README.md
documentation fix
fix a typo existing in NeuralChat README
=> Fix a link typo in NeuralChat README

intel_extension_for_transformers/llm/runtime/graph/models/gptj/gptj.cpp, intel_extension_for_transformers/llm/runtime/graph/models/gptj/gptj_utils.cpp, intel_extension_for_transformers/llm/runtime/graph/models/llama/llama_utils.cpp, intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_types.h, intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_utils.cpp
API not changed.
After #179, JBLAS-managed kv-cache is used on platforms with ISA support if compiled with a compiler of high enough version. However, it forgets to check if the model supports MHA fusion.
Models without MHA-fusion implemented should be able run without `--memory-f16` flag on SPR with GCC13.
GPTJ ext test (internal access required): TODO
N/A
=> [CPP Graph] Fix models without jblas-based kvcache support

intel_extension_for_transformers/neural_chat/chatbot.py, intel_extension_for_transformers/neural_chat/config.py, intel_extension_for_transformers/neural_chat/models/base_model.py, intel_extension_for_transformers/neural_chat/models/nueralchat_model.py, intel_extension_for_transformers/neural_chat/requirements.txt
feature
Support NeuralChatV2 model and add hf_access_token for llama2 model download
llama2 model can be downloaded by providing token and Intel/neural-chat-7b-v2 can be used to test.
No.
=> Support NeuralChatV2 model and add hf_access_token

intel_extension_for_transformers/neural_chat/pipeline/plugins/audio/tts.py
bug fix
https://github.com/intel/intel-extension-for-transformers/blob/main/intel_extension_for_transformers/neural_chat/pipeline/plugins/audio/tts.py#L106 this line is incorrect, fixed.
Add another backup speaker embedding when users do not have default_speaker_embedding.pt in their assets
Increase Usability
You can delete intel-extension-for-transformers/intel_extension_for_transformers/neural_chat/assets/speaker_embeddings and trigger UT to reproduce. We cannot test it by creating another UT because it exists in our default environment. So I just skip coverage check
None
=> fix speaker embedding path issue

.github/CODEOWNERS, .github/workflows/cpp-graph-test.yml, .github/workflows/deploy-test.yml, .github/workflows/llm-test.yml, .github/workflows/optimize-test.yml, .github/workflows/script/install_binary.sh, .github/workflows/unit-test-engine.yml, .github/workflows/unit-test-neuralchat.yml, .github/workflows/unit-test-optimize.yml, examples/huggingface/pytorch/summarization/quantization/run_benchmark.sh, examples/huggingface/pytorch/summarization/quantization/run_tuning.sh, setup.py
(1) update requirement version
(2) update project name in setup
(1) update to latest transformers
(2) according to this ticket https://support.github.com/ticket/personal/0/2321688, dependency graph not detected due to project name not explicitly in the setup call 
no risk
extension test
no
=> update transformers version

.github/workflows/script/models/cpp_graph_inference.sh, intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_weight_compression.h, intel_extension_for_transformers/llm/runtime/graph/models/gptj/gptj.h, intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_files.h, intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_utils.cpp
introduce asymmetric quantization for jblas backend
support bf16 & f32, int8 not supported yet
```
./build/bin/quant_gptj --model_file {f32.bin} --bits 4 --compute_type f32 --alg asym --model_name gptj --block_size -1 --out_file {quantized.bin}
./build/bin/quant_gptj --model_file {f32.bin} --bits 4 --compute_type bf16 --alg asym --model_name gptj --block_size -1 --out_file {quantized.bin}
```
compared with symmetric quantization, slightly larger weight with similar performance
```shell
[   4/ 285]   transformer.h.0.attn.k_proj.weight -     4096 x  4096, type =    f32, 0_1_128_1_2,quantizing .. JBLAS size =    64.00 MB ->     8.69 MB
[   4/ 285]   transformer.h.0.attn.k_proj.weight -     4096 x  4096, type =    f32, 0_1_128_1_2,quantizing .. JBLAS size =    64.00 MB ->     8.47 MB
``` …
=> [CPP Graph] Asym model

intel_extension_for_transformers/llm/finetuning/finetuning.py, intel_extension_for_transformers/neural_chat/docker/Dockerfile, intel_extension_for_transformers/neural_chat/server/neuralchat_client.py
bug fix
Fix load model config two times issue;
Fix device hpu issue
Users will not see two times load model config when do finetuning.
Users set device set to 'hpu' to run finetuning on Habana.
No.
=> Fix Habana finetuning issues

.github/workflows/unit-test-neuralchat.yml, intel_extension_for_transformers/neural_chat/server/neuralchat_client.py, intel_extension_for_transformers/neural_chat/server/restful/openai_protocol.py, intel_extension_for_transformers/neural_chat/server/restful/textchat_api.py, intel_extension_for_transformers/neural_chat/tests/server/test_textchat_server.py, intel_extension_for_transformers/neural_chat/tests/server/test_textchat_with_retrieval_server.py, intel_extension_for_transformers/neural_chat/tests/server/test_voicechat_server.py
bug fix
Support streaming mode for neuralchat server.
Users can use model.generate streaming mode when deploy neuralchat server.
No.
=> Support streaming mode for neuralchat server

intel_extension_for_transformers/neural_chat/pipeline/plugins/audio/utils/english_normalizer.py, intel_extension_for_transformers/neural_chat/tests/audio/test_english_normalizer.py
Bug fix
fix ordinals and conjunctions in tts normalizer
correctly handle following:
* conjunctions
CVPR-15 => cee vee pee ar fifteen
* ordinals
1st 2nd 3rd 4th 5th 11th 12th 21st 22nd => first second third fourth fifth eleventh twelfth twenty first twenty second
Make the normalizer more robust.
There still are some words such as `i7, ffmpeg, BTW` not spelled correctly and should be hardcoded maybe in an advanced Trie. Also, the potention number is only treated as a year when it has prepositions in front of it and between (1000,2999), which still is not an absolute mapping (e.g. in `Tom's 1986 report indicated that...`, 1986 should be a year but with no prepositions it is converted as cardinal number).
add two UTs
re should be built-in Python package
=> fix ordinals and conjunctions in tts normalizer

intel_extension_for_transformers/llm/library/jblas/jblas/jit_base.hpp, intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas.h, intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_gemm.h, intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_utils.h, intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_weight_compression.h, intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_wrapper.h, intel_extension_for_transformers/llm/library/jblas/jblas/kernel_avx2.h, intel_extension_for_transformers/llm/library/jblas/jblas/kernel_avx512_bf16.h, intel_extension_for_transformers/llm/library/jblas/jblas/kernel_avx512f.h, intel_extension_for_transformers/llm/library/jblas/jblas/kernel_ref.h, intel_extension_for_transformers/llm/library/jblas/jblas/kernel_wrapper.h, intel_extension_for_transformers/llm/operator/cscr/dispatcher/src/jblas_weightonly_dispatcher.cpp, intel_extension_for_transformers/llm/operator/cscr/qbits_ut/weightonly_test.py, intel_extension_for_transformers/llm/runtime/graph/core/layers/inner_product.cpp, intel_extension_for_transformers/llm/runtime/graph/core/layers/ip_fusion_ffn.cpp, intel_extension_for_transformers/llm/runtime/graph/core/layers/ip_fusion_qkv.cpp, intel_extension_for_transformers/llm/runtime/graph/core/layers/jblas_common.hpp
1. update jblas
2. Use the new avx512_vnni kernel to get a higher first token perf.
llama-7B bits=4 group_size=128, 32 comp_type=int8
=> New avx512_vnni kernel

examples/huggingface/pytorch/summarization/quantization/run_summarization.py, intel_extension_for_transformers/transformers/modeling/modeling_auto.py
bug fix
No API changed
Fixed error for replace -100s in predictions by the pad token, refer to https://github.com/huggingface/transformers/pull/22693
Run summarization examples successfully 
Local tested
=> Fixed error for replace -100s in predictions by the pad token

intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_weight_compression.h, intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_wrapper.h, intel_extension_for_transformers/llm/operator/cscr/dispatcher/CMakeLists.txt, intel_extension_for_transformers/llm/operator/cscr/dispatcher/src/jblas_weightonly_dispatcher.cpp, intel_extension_for_transformers/llm/runtime/deprecated/executor/src/operators/convolution.cpp, intel_extension_for_transformers/llm/runtime/deprecated/executor/src/operators/inner_product.cpp, intel_extension_for_transformers/llm/runtime/deprecated/executor/src/operators/matmul.cpp, intel_extension_for_transformers/llm/runtime/deprecated/executor/src/operators/reorder.cpp
- As title, as well as fixing narrowing conversion problems in qbit
- Compilation portability of qbit: use c++20 as MSVC does not have a feature switch for concept (`-fconcept` of GCC).
- Circumvent [a potential MSVC bug](https://developercommunity.visualstudio.com/t/Compilation-bug-C2760-when-using-omp-b/10470905?) that prevent using `}` just after `#progma omp barrier` inside a template.
No
=> Add dnnl_dim_t cast to fix executor windows failure

intel_extension_for_transformers/llm/evaluation/lm_eval/models/huggingface.py, tests/test_evaluation.py
feature
API not change
`decoder.onnx` and `decoder_with_past.onnx`  can be merged in a single model proto `decoder_model_merged.onnx`. Support lm-eval for `decoder_model_merged.onnx`
evaluate  `decoder_model_merged.onnx` with lm-eval
CI, local test
no
=> Support lm-eval for merged decoder ONNX models

intel_extension_for_transformers/transformers/utils/quantization_config.py, tests/test_weight_only.py
Bug fix
API changed or not: None
The `compute_dtype` is a string not include `.`.
```shell
output["compute_dtype"] = str(output["compute_dtype"]).split(".")[1]
IndexError: list index out of range
```
Pre-CI
None
=> Fix the Woq config serialization issue

intel_extension_for_transformers/llm/library/jblas/jblas/jit_base.hpp, intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_transformer.h, intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_utils.h, intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_weight_compression.h, intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_wrapper.h, intel_extension_for_transformers/llm/library/jblas/jblas/kernel_avx2.h, intel_extension_for_transformers/llm/library/jblas/jblas/kernel_jit.h, intel_extension_for_transformers/llm/runtime/graph/core/layers/mha_dense.cpp, intel_extension_for_transformers/llm/runtime/graph/core/ne.h, intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_utils.cpp
- The FLASH_ATTN_KV_UPDATE op now uses JIT implementations for first token inference
- Update jblas to 21757a4
N/A
<details>
<summary>Interference result:</summary>
```bash
set -ex
#main branch
rm -rf bin && cmake .. -GNinja -DNE_BUILD_TESTS=ON -DNE_PROFILING=ON -DCMAKE_BUILD_TYPE=Release && ninja run_gptj && env ENGINE_PROFILING=1 numactl -m 1 -C 56-111 bin/run_gptj -m /home_local/dingyi/data/gpt-j-6B-pr347-q4j-sym-int8-fp32-g128.bin --seed 1234 -t 48 -b 2048 -c 2048 -n 1 -p "$LUOYU_PROMPT"
rm -rf bin && cmake .. -GNinja -DNE_BUILD_TESTS=ON -DNE_PROFILING=ON -DCMAKE_BUILD_TYPE=Release && ninja run_gptj && env ENGINE_PROFILING=1 numactl -m 1 -C 56-111 bin/run_gptj -m /home_local/dingyi/data/gpt-j-6B-pr347-q4j-sym-int8-fp32-g128.bin --seed 1234 -t 56 -b 2048 -c 2048 -n 1 -p …
```
=> [CPP Graph] KV-Update Optimization

intel_extension_for_transformers/llm/runtime/graph/README.md
Refine LLM runtime readme: 
* Use NeuralChatv1.1 as example
* Add binary installation instruction
* Unify the aug description
=> Refine LLM runtime readme

README.md, intel_extension_for_transformers/llm/runtime/graph/README.md, intel_extension_for_transformers/llm/runtime/graph/__init__.py, intel_extension_for_transformers/llm/runtime/graph/application/main_pybind.cpp, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_chatglm.py, intel_extension_for_transformers/llm/runtime/graph/scripts/python_api_example.py, intel_extension_for_transformers/neural_chat/examples/talkingbot_pc/build_talkingbot_on_pc.ipynb, intel_extension_for_transformers/transformers/modeling/modeling_auto.py, intel_extension_for_transformers/transformers/utils/quantization_config.py, setup.py, tests/test_llm_runtime.py
feature
API changed
```python
from transformers import AutoTokenizer, TextStreamer
from intel_extension_for_transformers.transformers import AutoModel, WeightOnlyQuantConfig
model_name = "THUDM/chatglm2-6b"  # or local path to model
woq_config = WeightOnlyQuantConfig(compute_dtype="int8", weight_dtype="int4")
prompt = "She opened the door and see"
tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
input_ids = tokenizer(prompt, return_tensors="pt").input_ids
streamer = TextStreamer(tokenizer)
model = AutoModel.from_pretrained(model_name, quantization_config=woq_config, use_llm_runtime=True, trust_remote_code=True)
gen_tokens = model.generate(input_ids, streamer=streamer, max_new_tokens=300)
```
=> Use transfomers tokenizer and streamer for python api

intel_extension_for_transformers/llm/runtime/graph/README.md, intel_extension_for_transformers/llm/runtime/graph/core/layers/Ops.h, intel_extension_for_transformers/llm/runtime/graph/core/layers/mha_dense.cpp, intel_extension_for_transformers/llm/runtime/graph/core/layers/mha_dense.h, intel_extension_for_transformers/llm/runtime/graph/core/ne_layers.c, intel_extension_for_transformers/llm/runtime/graph/core/ne_layers.h, intel_extension_for_transformers/llm/runtime/graph/models/falcon/falcon.cpp, intel_extension_for_transformers/llm/runtime/graph/models/falcon/falcon_utils.cpp, intel_extension_for_transformers/llm/runtime/graph/models/gptj/gptj.cpp, intel_extension_for_transformers/llm/runtime/graph/models/llama/llama.cpp, intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_utils.cpp, intel_extension_for_transformers/llm/runtime/graph/models/opt/opt.cpp, intel_extension_for_transformers/llm/runtime/graph/models/starcoder/starcoder.cpp, intel_extension_for_transformers/llm/runtime/graph/scripts/inference.py
Add MHA fusion support for Falcon, including:
- Support GQA and MQA
- Replace is_causal by attn_flags for future flags (particularly prepared for MPT's alibi)
- Forward the `--memory-f16/f32/auto` tags to the python script
- Add `NE_OP_DEBUG` for debugging experience
N/A
<details>
<summary>Test commands:</summary>
```bash
set -ex
#main branch
rm -rf bin && cmake .. -GNinja -DNE_BUILD_TESTS=ON -DNE_PROFILING=OFF -DCMAKE_BUILD_TYPE=Release && ninja run_falcon && numactl -m 1 -C 56-111 bin/run_falcon -m /home_local/dingyi/data/falcon-7b-pr410-q40.bin --seed 1234 -t 56 -b 2048 -c 2048 -n 64 --memory-auto -p "$GIRL_PROMPT"
rm -rf bin && cmake .. -GNinja -DNE_BUILD_TESTS=ON -DNE_PROFILING=ON -DCMAKE_BUILD_TYPE=Release && ninja run_falcon && env ENGINE_PROFILING=1 numactl -m 1 -C …
```
=> [CPP Graph] Falcon MHA support

intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/indexing/indexing.py, intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/retrieval_bm25.py
bug fix
no change to API
Neural Chat SparseBM25Retriever pipeline had some minor typos that caused the code to error.
Specifically:
https://github.com/intel/intel-extension-for-transformers/blob/9491bbb8aa2b36a530abfcdc1155ffa17f3246f8/intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/retrieval_bm25.py#L23
Should be `__init__`
and
https://github.com/intel/intel-extension-for-transformers/blob/9491bbb8aa2b36a530abfcdc1155ffa17f3246f8/intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/indexing/indexing.py#L136
should be `self.document_store`
JIRA ticket: N/A
Using Neural chat with SparseBM25Retriever should successfully retrieve outputs from inputted documents without error-ing out
Tested on AWS M7i EC2 instance - Intel(R) Xeon(R) Platinum 8488C …
=> fixes to Neural Chat SparseBM25Retriever pipeline

intel_extension_for_transformers/llm/runtime/graph/models/chatglm/chatglm2.cpp, intel_extension_for_transformers/llm/runtime/graph/models/chatglm/chatglm2_utils.cpp, intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_utils.cpp
Add MHA fusion support for ChatGLM2 and avoiding initialize kv-cache twice (even with MHA fusion disabled)
N/A
<details>
<summary>Test commands:</summary>
```bash
set -ex
#main branch
rm -rf bin && cmake .. -GNinja -DNE_BUILD_TESTS=ON -DNE_PROFILING=OFF -DCMAKE_BUILD_TYPE=Release && ninja run_chatglm2 && numactl -m 1 -C 56-111 bin/run_chatglm2 -m /home_local/dingyi/data/chatglm2-6b-pr410-q4j-sym-int8-fp32-g128.bin --seed 1234 -t 56 -b 2048 -c 2048 -n 256 --memory-auto -p "$GIRL_PROMPT"
rm -rf bin && cmake .. -GNinja -DNE_BUILD_TESTS=ON -DNE_PROFILING=OFF -DCMAKE_BUILD_TYPE=Release && ninja run_chatglm2 && numactl -m 1 -C 56-111 bin/run_chatglm2 -m /home_local/dingyi/data/chatglm2-6b-pr410-q4j-sym-int8-fp32-g128.bin --seed 1234 -t 56 -b 2048 -c 2048 -n 256 --memory-auto -p …
```
=> [CPP Graph] ChatGLM2 MHA support

intel_extension_for_transformers/llm/runtime/graph/__init__.py, intel_extension_for_transformers/llm/runtime/graph/models/falcon/falcon.h, intel_extension_for_transformers/llm/runtime/graph/models/falcon/falcon_utils.cpp, intel_extension_for_transformers/llm/runtime/graph/scripts/convert.py, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_falcon.py, intel_extension_for_transformers/llm/runtime/graph/scripts/run.py
bug fix, no api change
JIRA ticket: None
falcon model updates some parameter names, see [here](https://huggingface.co/tiiuae/falcon-40b/blob/main/config.json)
```json
{
"alibi": false,
"apply_residual_connection_post_layernorm": false,
"architectures": [
"FalconForCausalLM"
],
"attention_dropout": 0.0,
"auto_map": {
"AutoConfig": "configuration_falcon.FalconConfig",
"AutoModel": "modeling_falcon.FalconModel",
"AutoModelForSequenceClassification": "modeling_falcon.FalconForSequenceClassification",
"AutoModelForTokenClassification": "modeling_falcon.FalconForTokenClassification",
"AutoModelForQuestionAnswering": "modeling_falcon.FalconForQuestionAnswering",
"AutoModelForCausalLM": "modeling_falcon.FalconForCausalLM"
},
"bias": false,
"bos_token_id": 11,
"eos_token_id": …
```
=> [Cpp Graph] Update Falcon HF para and support Falcon-180B

intel_extension_for_transformers/llm/runtime/graph/core/layers/mha_dense.cpp, intel_extension_for_transformers/llm/runtime/graph/core/ne_layers.c, intel_extension_for_transformers/llm/runtime/graph/core/ne_layers.h, intel_extension_for_transformers/llm/runtime/graph/models/chatglm/chatglm2.cpp, intel_extension_for_transformers/llm/runtime/graph/models/falcon/falcon.cpp, intel_extension_for_transformers/llm/runtime/graph/models/gptj/gptj.cpp, intel_extension_for_transformers/llm/runtime/graph/models/llama/llama.cpp, intel_extension_for_transformers/llm/runtime/graph/models/mpt/mpt.cpp, intel_extension_for_transformers/llm/runtime/graph/models/mpt/mpt_utils.cpp
Add MHA fusion support for MPT including [ALiBi](https://arxiv.org/abs/2108.12409) support in fused attention operation.
N/A
This PR is tested with CI vi GHA and local tests for accuracy and performance.
As a result, the model can generate reasonable text with MHA fusion enabled, and it preserves the identical behavior when disable the fusion (with `--memory-f16`). The fusion brings ~850% (12656.38ms => 1330.82ms) performance for first token and ~40% (73.29ms => 52.63ms) performance for next token inference.
In addition, it is tested that llama & gptj will preserve its behavior in this PR (q4j-int8-g128). 
<details>
<summary>Accuracy Tests Details:</summary>
Commands:
```bash
set -ex
#main branch
rm -rf bin && cmake .. -GNinja -DNE_BUILD_TESTS=ON -DNE_PROFILING=OFF …
```
=> [CPP Graph] MPT MHA support

.github/workflows/cpp-graph-test.yml, .github/workflows/script/models/cpp_graph_inference.sh, intel_extension_for_transformers/llm/runtime/graph/core/ne_layers.c
- CPP Graph CI speedup
- llama: 10min => 4min
- gptj: 13min => 8min
- The test result can now be previewed without downloading
- The test results of different models won't replace others any more
- Support trigger CI manually with different models. Developers can use it as a light-weight extension test, which makes our project more open! **(But DO NOT ABUSE! It will block all PRs if too many tests are triggered)**
N/A
N/A
No
=> GitHub Action Workflows speedup

intel_extension_for_transformers/neural_chat/examples/instruction_tuning/requirements.txt
bug fix : add missing python packages for neural_chat/examples/instruction_tuning
it runs after we following the README and requirement.txt
AWS m7i.24xlarge
=> add missing packages for neural_chat example

requirements.txt, setup.py
bug fix
No API changed
There is issue for setuptools version<65, so limited setuptools version.
Build ITREX successfully.
Local tested
=> Fixed setuptools version limitation for build

intel_extension_for_transformers/neural_chat/models/model_utils.py
os.environ["ONEDNN_MAX_CPU_ISA"] = "AVX512_CORE_BF16" will cause int8 starcoder mha fusion failed.
=> Fix NeuralChat starcoder mha fusion env issue

.github/workflows/script/unitTest/env_setup.sh
INC API changed in this commit https://github.com/intel/neural-compressor/pull/1323, but ITREX are ready to adapt to new API. So temperately use the latest release version 2.3.1
=> use INC 2.3.1

intel_extension_for_transformers/neural_chat/models/model_utils.py, intel_extension_for_transformers/neural_chat/pipeline/plugins/ner/ner.py, intel_extension_for_transformers/neural_chat/pipeline/plugins/ner/utils/utils.py
bug fix
Remove OneDNN graph env setting for BF16 inference
Latest official pytorch version has fixed the onednn graph https://github.com/pytorch/pytorch/pull/97957. 
LLM inference for BF16 can be run successfully and without any performance reduce.
None.
=> Remove OneDNN graph env setting for BF16 inference

intel_extension_for_transformers/neural_chat/examples/instruction_tuning/README.md
Add docker setup session for neuralchat finetuning sample
add a docker setup session for customers
customers should be able to setup docker instance for this sample
validate on AWS SPR instance
no
=> Add docker setup session for neuralchat finetuning sample

intel_extension_for_transformers/neural_chat/examples/instruction_tuning/README.md
Fixed GPTNeoXTokenizer missing issue and added section how to get MPT models
missing GPTNeoXTokenizer, so we change it to GPTNeoXTokenizerFast. 
Also add section how to get all models files like MPT
test on AWS m7i.24xlarge instance by following the instructions
NA
=> Update README.md for fast token issue

intel_extension_for_transformers/llm/runtime/graph/README.md
Fixed typo.
convertion -> conversion
=> Fix typo in README.md

intel_extension_for_transformers/llm/runtime/graph/CMakeLists.txt, intel_extension_for_transformers/llm/runtime/graph/README.md, intel_extension_for_transformers/llm/runtime/graph/vectors/cpu/vec_load.hpp, intel_extension_for_transformers/llm/runtime/graph/vectors/cpu/vec_store.hpp
remove warning in MSVC
default to set AVX512 OFF 
Setting AVX512 OFF have no regress on SPR.
=> improve Avx2 

examples/huggingface/pytorch/text-generation/README.md, examples/huggingface/pytorch/text-generation/deployment/README.md
This pull request fixes some of the typos of "examples/huggingface/pytorch/text-generation/README.md" and "examples/huggingface/pytorch/text-generation/deployment/README.md" . I kindly request repository maintainers to review and merge it. 
Typos fixes are:
Eabled -> Enabled
FrequencyGoverner -> FrequencyGovernor
runing -> running 
=> fixed typos

intel_extension_for_transformers/neural_chat/docker/Dockerfile, intel_extension_for_transformers/neural_chat/docker/finetuning/README.md
=> [NeuralChat] Supported dockerfile for NV GPU.

intel_extension_for_transformers/transformers/utils/utility.py
summary:
transformers version >=4.34.0, num_key_values_heads is used to decrease past-kv shape to reduce memory.
details:
most model change num_attention_heads to num_key_values_heads, usually they are same, but when the size is large, such as 70b, they are different, num_key_values_heads is smaller than num_attention_heads to reduce memory.
=> [LLM] Adapt to transformers 4.34

workflows/chatbot/inference/generate.py
bug fix
Fix workflow generate.py import issue.
Directory  /root /.deepface/weights created
from intel_extension_for_transformers.neural_chat.config import (
ImportError: cannot import name 'MixedPrecisionConfig' from 'intel_extension_for_transformers.neural_chat.config' (/opt/conda/envs/neuralchat/lib/python3.9/site-packages/intel_extension_for_transformers-0.1.dev1+g108d761-py3.9-linux-x86_64.egg/intel_extension_for_transformers/neural_chat/config.py)
This import issue reported by CI can be fixed.
None.
=> Fix workflow generate.py import issue

examples/huggingface/pytorch/text-generation/quantization/run_generation.py, intel_extension_for_transformers/transformers/modeling/modeling_auto.py, intel_extension_for_transformers/transformers/utils/quantization_config.py
add op_name_dict to check which observer(kl, minmax) sq should use.
INC will check op_type_dict first and then check op_name_dict
=> [LLM] Add op_name_dict attribute to SmoothQuantConfig

intel_extension_for_transformers/llm/runtime/graph/models/llama/llama.cpp
Fix of #580.
N/A
`./build/bin/run_llama -m ne_llama_qj.bin -p "[INST]tell me about intel[\INST]" -c 100 --seed 1 -n 1000` on ICX with GCC9.
Where is `q4j-int8-g32`.
Result is now the same of that before the merging of #580.
No
=> [LLM Runtime] Fix LLaMA after discarding KV-cache

intel_extension_for_transformers/neural_chat/tests/ci/optimization/test_optimization_llmruntime.py
There is the core dump raised when itrex woq use_llmruntime=False and True in one UT, the probable for doubt is they both use the same jblas which some objects are static and sharing, so split the ut now.
=> [Neural Chat] Fix neuralchat woq UT

intel_extension_for_transformers/neural_chat/requirements.txt, intel_extension_for_transformers/neural_chat/requirements_cpu.txt, intel_extension_for_transformers/neural_chat/requirements_hpu.txt, intel_extension_for_transformers/neural_chat/requirements_pc.txt, intel_extension_for_transformers/neural_chat/requirements_xpu.txt, intel_extension_for_transformers/neural_chat/tests/requirements.txt
bug fix
Latest chromadb 0.4.16 API changed which caused the CI failed, fix the chromadb version to 0.4.15.
======================================================================
[8127](https://github.com/intel/intel-extension-for-transformers/actions/runs/6794388851/job/18470729429#step:8:8128)ERROR: test_retrieval (__main__.UnitTest)
[8128](https://github.com/intel/intel-extension-for-transformers/actions/runs/6794388851/job/18470729429#step:8:8129)----------------------------------------------------------------------
[8129](https://github.com/intel/intel-extension-for-transformers/actions/runs/6794388851/job/18470729429#step:8:8130)Traceback (most recent call last):
[8130](https://github.com/intel/intel-extension-for-transformers/actions/runs/6794388851/job/18470729429#st …
=> Fix latest chromadb version issue

intel_extension_for_transformers/llm/runtime/graph/core/README.md, intel_extension_for_transformers/llm/runtime/graph/core/layers/inner_product.cpp, intel_extension_for_transformers/llm/runtime/graph/core/layers/ip_fusion_ffn.cpp, intel_extension_for_transformers/llm/runtime/graph/core/layers/ip_fusion_qkv.cpp, intel_extension_for_transformers/llm/runtime/graph/core/layers/jblas_common.hpp
NO API changed or not
integrate AVX_VNNI
=> [LLM Runtime] integrate AVX_VNNI

.github/workflows/cpp-graph-test.yml, intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_utils.h, intel_extension_for_transformers/llm/library/jblas/jblas/kernel_avx2.h, intel_extension_for_transformers/llm/library/jblas/jblas/kernel_avx512_bf16.h, intel_extension_for_transformers/llm/library/jblas/jblas/kernel_avx512f.h, intel_extension_for_transformers/llm/library/jblas/jblas/kernel_wrapper.h, intel_extension_for_transformers/llm/runtime/graph/README.md, intel_extension_for_transformers/llm/runtime/graph/docs/fused_attention.md
Allow CompileBF16 on GCC11 (thus fused attention can be enabled on GCC11).
Jblas upgrade to 5a2df34410f31a91da22cca94b69ed73d3edce40
N/A
- GHA for
- GCC11: https://github.com/intel/intel-extension-for-transformers/actions/runs/6809809234
- GCC12: https://github.com/intel/intel-extension-for-transformers/actions/runs/6809805199
- GCC13: https://github.com/intel/intel-extension-for-transformers/actions/runs/6809791965
- Extension test (internal access required) for
- GCC11: https://inteltf-jenk.sh.intel.com/job/ITREX-cpp-graph-extension/179
- GCC12: https://inteltf-jenk.sh.intel.com/job/ITREX-cpp-graph-extension/180
- GCC13: https://inteltf-jenk.sh.intel.com/job/ITREX-cpp-graph-extension/178
No
=> [LLM Runtime] Allow CompileBF16 on GCC11

intel_extension_for_transformers/llm/runtime/graph/scripts/convert_llama.py
Loading a safetensors model like [CodeLlama-13B-hf](https://huggingface.co/codellama/CodeLlama-13b-hf), I got an error: "Key Error: BF16". 
This was also observed in the llama.cpp repository and the issue is described [here](https://github.com/ggerganov/llama.cpp/issues/1473). 
I have tested this change and the models now work just fine.
Safetensors BF16 can load without errors.
Load a model with safetensors bf16 and use the convert.py script on that model, the error should be visible.
No changes in dependencies
=> fixed bf16 error in convert_llama.py

tests/test_quantization.py
https://github.com/intel/intel-extension-for-transformers/pull/655 this PR support gcc 11 compile and have some affects on jblas, woq quantization use the qbitsLinear which based jblas, so the output value change.
the optimization ut test based gcc 11 now.
=> update ut value due to gcc change

tests/test_evaluation.py, tests/test_quantization.py
add skip operator for nightly or weekly unit test.
lm-eval requests python version higher or equal than 3.9.0.
llm sq requests pytorch version higher or equal than 2.1.0.
=> Add skip for UT

intel_extension_for_transformers/llm/runtime/graph/developer_document.md
documentation
Modify link that is not referenced because graph_developer_document branch no longer exists
=> fix typo : graph_developer_document branch no longer exists

README.md, intel_extension_for_transformers/llm/runtime/graph/README.md, intel_extension_for_transformers/transformers/modeling/modeling_auto.py
feature
Support load_in_nbit in llm runtime
=> [LLM Runtime] Support load_in_nbit in llm runtime

intel_extension_for_transformers/llm/finetuning/finetuning.py
fix tokenizer for code generation evaluation
fix codellama acc=0 when finetuning
set `postprocess` to True (by default) so that batch_size can be set to smaller
local test passed
=> fix tokenizer for code generation eval

.github/workflows/chatbot-finetune-mpt-7b-chat-hpu.yml, .github/workflows/chatbot-finetune-mpt-7b-chat.yml, .github/workflows/chatbot-inference-llama-2-7b-chat-hf.yml, .github/workflows/chatbot-inference-llama-2-7b_70b-chat-hf-hpu.yml, .github/workflows/chatbot-inference-mpt-7b-chat-hpu.yml, .github/workflows/chatbot-inference-mpt-7b-chat.yml, .github/workflows/script/chatbot/hpu_check/run_check.sh, .github/workflows/script/chatbot/hpu_check/to_hpu.py, .github/workflows/script/chatbot/prepare_ft_mpt-7b-chat_mpi.sh, .github/workflows/script/chatbot/start_ft_mpt-7b-chat_mpi.sh
validation
remove chatbot test dependency on local scripts
CI pass, extension test pass 
CI pass, extension test pass 
No
=> remove chatbot test dependency on local scripts

.gitignore, intel_extension_for_transformers/llm/runtime/graph/README.md, intel_extension_for_transformers/llm/runtime/graph/__init__.py, intel_extension_for_transformers/llm/runtime/graph/application/main_pybind.cpp, intel_extension_for_transformers/llm/runtime/graph/requirements.txt, intel_extension_for_transformers/llm/runtime/graph/scripts/cal_diff.py, intel_extension_for_transformers/llm/runtime/graph/scripts/perplexity.py, tests/requirements.txt, tests/test_llm_runtime.py
- Add PPL script
- Add `cal_diff.py` script for future CI @zhenwei-intel
- Fix UT (`test_llm_runtime.py`)
N/A
Internal extension test:
- Llama2: https://inteltf-jenk.sh.intel.com/job/ITREX-cpp-graph-extension-WIP/32/artifact/report.html
- GPT-NEOX and OPT: https://inteltf-jenk.sh.intel.com/job/ITREX-cpp-graph-extension-WIP/33/artifact/report.html
- All models: https://inteltf-jenk.sh.intel.com/job/ITREX-cpp-graph-extension-WIP/34/
No
=> [LLM Runtime] Add Script for PPL Evaluation

.github/workflows/unit-test-kernel.yml, .github/workflows/unit-test-optimize.yml, intel_extension_for_transformers/llm/library/jblas/jblas/kernel_avx512_bf16.h, intel_extension_for_transformers/llm/library/jblas/jblas/kernel_avx512f.h, intel_extension_for_transformers/llm/operator/csrc/CMakeLists.txt, intel_extension_for_transformers/llm/operator/csrc/dispatcher/include/jblas_weightonly_dispatcher.hpp, intel_extension_for_transformers/llm/operator/csrc/dispatcher/src/jblas_weightonly_dispatcher.cpp, intel_extension_for_transformers/llm/operator/csrc/include/dropout.hpp, intel_extension_for_transformers/llm/operator/csrc/qbits.cpp, intel_extension_for_transformers/llm/operator/csrc/qbits_ut/dropout_test.py, intel_extension_for_transformers/llm/operator/csrc/qbits_ut/ut_utils.py, intel_extension_for_transformers/llm/operator/csrc/qbits_ut/weightonly_test.py, intel_extension_for_transformers/llm/operator/csrc/src/dropout.cpp
feature or bug fix or documentation or others: feature
API changed or not: Yes
user can call optimized fwd/bwd dropout operator in QBits, 3X+ perf improvement compared to pytorch.
e.g.
```
torch.ops.qbits_customop.qbits_dropout_fwd(weight, p)
torch.ops.qbits_customop.qbits_dropout_bwd(grad, mask)
```
JIRA ticket: https://jira.devtools.intel.com/browse/NLPTOOLKIU-958
optmized fwd/bwd dropout operator under AVX512/AVX2 ISA, including a high-performance rand-generator.
change QBits log from cout to torch::LOG.
tested on 335T(spr) & desktop(Core i9-10900)
No.
=> [LLM Runtime] Optmized dropout operator

intel_extension_for_transformers/transformers/utils/quantization_config.py
Bug Fix
Before, `-1` as group size in `WeightOnlyQuantConfig` was rejected. However, this is the recommended value for several ISAs when using LLM Runtime according to https://github.com/intel/intel-extension-for-transformers/blob/main/intel_extension_for_transformers/llm/runtime/graph/core/README.md. 
group size -1 is now accepted when creating a `WeightOnlyQuantConfig`.
Creating a quantization config with corresponding group size and using it for inference: `config = intel_extension_for_transformers.transformers.WeightOnlyQuantConfig(compute_dtype='int8', weight_dtype='int4', group_size=-1, use_cache=True)`
none
=> allow group_size -1 in quantization_config

intel_extension_for_transformers/neural_chat/pipeline/plugins/audio/tts.py, intel_extension_for_transformers/neural_chat/tests/ci/plugins/audio/test_tts.py
bug fix
Sometimes text to speech output is slightly different and causes UT error, and this is because a dropout is also applied in inference (https://github.com/huggingface/transformers/blob/main/src/transformers/models/speecht5/modeling_speecht5.py#L687), so we keep the seed to be the same before each inference, to keep the same bernoulli sequence. Meanwhile, the `reduce_noise` flag is disabled by default.
Same as above.
UT
None
=> fix tts ut random issue

intel_extension_for_transformers/llm/runtime/graph/README.md, intel_extension_for_transformers/llm/runtime/graph/application/main_pybind.cpp, intel_extension_for_transformers/llm/runtime/graph/application/pybind_gptj.cpp, intel_extension_for_transformers/llm/runtime/graph/core/layers/mha_dense.cpp, intel_extension_for_transformers/llm/runtime/graph/core/layers/mha_dense.h, intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_utils.cpp
As title.
the expected behavior that triggered by this PR
q4_j1_bf16_pc: {'rouge1': 42.8563, 'rouge2': 19.8546, 'rougeL': 29.4987, 'rougeLsum': 40.0661, 'gen_len': 4581237, 'gen_num': 13368}
> A bit low, but probably due to the calculation precision itself
<details>
<summary>`python -m unittest tests/test_llm_runtime.py -vk beam` with single prompt:</summary>
```diff
diff --git a/intel_extension_for_transformers/llm/runtime/graph/tests/test_llm_runtime.py b/intel_extension_for_transformers/llm/runtime/graph/tests/test_llm_runtime.py
index 5c93edaa07..0bc2392534 100644
--- a/intel_extension_for_transformers/llm/runtime/graph/tests/test_llm_runtime.py
+++ b/intel_extension_for_transformers/llm/runtime/graph/tests/test_llm_runtime.py
@@ -49,7 +49,7 @@ class …
```
=> [LLM Runtime] Beam Search Support of Fused Attention

README.md, docs/publication.md, intel_extension_for_transformers/neural_chat/models/model_utils.py, intel_extension_for_transformers/transformers/trainer.py
Enhanced the LLaMa model family by incorporating an optimization pipeline using ipex.optimize_transformers(). The API remains unchanged.
This change adds support for ipex.optimize_transformers, which is causing significant perfromance boost for LLaMa model familly.
Implemented modifications to enable quantization for the LLaMa model family, with the added option to optionally trace the model for FP32/BF16 precision.
Neuralchat localhost deployment was tested on c7i.24xlarge AWS instance. 
Confirmed compatibility with frontend.
This PR is not changing any dependencies.
As ipex.optimize_transformers() brings a notable performance boost to models, it is advisable to contemplate a gradual transition to using this library once it is supported by ipex
=> [NeuralChat]  Add optimization pipeline for LLaMa model familly

intel_extension_for_transformers/llm/runtime/graph/__init__.py, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_llama.py, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_mistral.py
=> [LLM Runtime]  fix added_tokens error

intel_extension_for_transformers/neural_chat/examples/finetuning/instruction/README.md
documentation
1. https://huggingface.co/datasets/HuggingFaceH4/oasst1_en does not exist any more, use https://huggingface.co/datasets/HuggingFaceH4/ultrachat_200k instead
2. add **--task code-generation** in sample code for code generation finetuning
=> fix finetuning instruction readme issue

intel_extension_for_transformers/llm/evaluation/models.py, intel_extension_for_transformers/transformers/modeling/modeling_auto.py
code improve
1. move  how to get position_ids for THUDM/chatglm-6b from forward to prepare_generation_for_inputs.
2. add use_cache=True for fp32 model when sq.
=> improve prepare_generation_for_inputs for chatglm

third_party_programs.txt
Typo
The file path is misspelled
=> Fix typo at third_party_programs.txt file

examples/huggingface/pytorch/text-embedding/deployment/mteb/bge/executor_utils.py, intel_extension_for_transformers/llm/library/kernels/src/cpu/jit_domain/jit_softmax_Ab16a.cpp, intel_extension_for_transformers/llm/runtime/deprecated/kernels/src/cpu/jit_domain/jit_softmax_Ab16a.cpp, intel_extension_for_transformers/transformers/modeling/modeling_auto.py
Fixed a bug in the softmax sub-kernel of MHA of the NeuralEngine (deprecated) that may cause accuracy when seqlen (with mask) is small.
The BGE accuracy with MHA-fusion is increased. 
```bash
bash run_bge.sh --model=BAAI/bge-base-en-v1.5 --precision=int8 --mode=accuracy
```
- BAAI/bge-base-en-v1.5: STS res 82.219  ===with-mha in this PR===> 81.541
- BAAI/bge-small-en-v1.5: STS res 81.430  ===with-mha in this PR===> 80.911
- --model=BAAI/bge-base-en-v1.5 --precision=fp32: STS res 82.392
- --model=BAAI/bge-small-en-v1.5 --precision=fp32: STS res 81.593
No
=> [Neural Engine] Fix kernels softmax in int8 mha

intel_extension_for_transformers/neural_chat/pipeline/plugins/video/face_animation/src/test_audio2coeff.py
bug fix
ut fix
'##' in path will be double quoted with `shlex.quote()`, which will lead to a wrong path. `shlex.quote()` is needed for security check, so we replace '##' with '-' to resolve that.
JIRA ticket: [NLPTOOLKIU-1083](https://jira.devtools.intel.com/browse/NLPTOOLKIU-1083)
ut pass
run nightly CI
None
=> fix imageio path issue

intel_extension_for_transformers/llm/runtime/graph/core/ne_layers.c, intel_extension_for_transformers/llm/runtime/graph/core/ne_layers.h, intel_extension_for_transformers/llm/runtime/graph/models/baichuan/baichuan.cpp, intel_extension_for_transformers/llm/runtime/graph/models/chatglm/chatglm.cpp, intel_extension_for_transformers/llm/runtime/graph/models/chatglm/chatglm2.cpp, intel_extension_for_transformers/llm/runtime/graph/models/falcon/falcon.cpp, intel_extension_for_transformers/llm/runtime/graph/models/gptj/gptj.cpp, intel_extension_for_transformers/llm/runtime/graph/models/gptneox/gptneox.cpp, intel_extension_for_transformers/llm/runtime/graph/models/llama/llama.cpp, intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_files.h, intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_types.h, intel_extension_for_transformers/llm/runtime/graph/models/qwen/qwen.cpp, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_baichuan.py, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_bloom.py, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_chatglm.py, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_dolly.py, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_falcon.py, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_gptj.py, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_gptneox.py, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_gptq_bloom.py, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_llama.py, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_mistral.py, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_mpt.py, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_opt.py, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_qwen.py, intel_extension_for_transformers/llm/runtime/graph/scripts/convert_starcoder.py, intel_extension_for_transformers/transformers/modeling/modeling_auto.py
bug fix
neural_chat_v3.1:
- before fix:  fp32 {'diff2': 0.15223888, 'cos': 0.9888011}
- after fix: fp32 {'diff2': 8.285937e-05, 'cos': 1.0}
chatglm2:
- before fix: fp32 {'diff2': 0.01901678, 'cos': 0.99988997}
- after fix: fp32 {'diff2': 0.009832479, 'cos': 0.99995184}
codellama
- before fix: fp32 {'diff2': 0.07989038, 'cos': 0.99698734}
- after fix rms_norm_eps: fp32 {'diff2': 0.0529107, 'cos': 0.99863917}
- after fix freq_bas: fp32 {'diff2': 0.00017308403, 'cos': 0.9999999}
=> [LLM Runtime] make rms_norm_eps and freq_base as parameter

intel_extension_for_transformers/neural_chat/config.py
bug fix
Fix the issue that itrex has different result compared with huggingface interfaces.
Modify the parameter top_k to 40 as hugging face.
https://wiki.ith.intel.com/pages/viewpage.action?pageId=3042423855#LLMInferenceParameters-ComparisontoHuggingFace
The LLM inference result will be `sampling`, as same as huggingface.
Local tested on SDP server.
no
=> [NeuralChat] Align inference generation configuration behaviour with HF

intel_extension_for_transformers/transformers/modeling/modeling_auto.py, tests/CI/test_quantization.py
sq alpha auto tuning need use calib_dataloader, but position_ids is not used by all models.
add ut opt-125m for models which didn't have position_ids parameters.
raised by @yintong-lu  please review.
=> [LLM] Adapt models didn't need position ids do sq auto tune

examples/.config/pytorch_optimize.json, examples/huggingface/pytorch/text2text-generation/requirements.txt, examples/huggingface/pytorch/text2text-generation/run_benchmark.sh, examples/huggingface/pytorch/text2text-generation/run_seq2seq_generation.py, examples/huggingface/pytorch/text2text-generation/run_tuning.sh, requirements.txt
bug fix 
No API changed
Fixed quantization failure when T5 base model be quantized with IPEX smoothquant.
Quantize successfully
Local tested
=> Fixed issue for T5 base model quantization issue with IPEX smoothquant

intel_extension_for_transformers/neural_chat/models/base_model.py, intel_extension_for_transformers/neural_chat/prompts/prompt.py
bug fix
A simple example will reproduce this issue, when the second output contains template information and no correct output. I think we should by default clear the previous prompt template unless we know exactly our model can work on multi-round speech.
```
from intel_extension_for_transformers.neural_chat import build_chatbot, PipelineConfig
config = PipelineConfig()
chatbot = build_chatbot(config)
out = chatbot.predict("Tell me about Intel Xeon Scalable Processors.")
print(out)
out = chatbot.predict("Tell me about Intel")
print(out)
```
This is because the new query is simply appended to the previous template and the default model cannot deal with it.
bug fix
example
None
=> [NeuralChat] fix wrong output of multi-round prediction

intel_extension_for_transformers/llm/runtime/graph/CMakeLists.txt, intel_extension_for_transformers/llm/runtime/graph/cmake/Common.cmake, intel_extension_for_transformers/llm/runtime/graph/core/CMakeLists.txt
=> [LLM Runtime] dynamic link the layer to compress binary size

intel_extension_for_transformers/llm/quantization/nn/__init__.py, intel_extension_for_transformers/llm/quantization/nn/modules.py, intel_extension_for_transformers/llm/quantization/utils.py, intel_extension_for_transformers/transformers/modeling/modeling_auto.py, intel_extension_for_transformers/transformers/utils/config.py, intel_extension_for_transformers/transformers/utils/utility.py, tests/CI/test_weight_only.py
feature or bug fix or documentation or others: feature
porting some changes from #441 
TODO:
*This interface may be changed in #441 after discussed with @PenghuiCheng . Just a transition interface.*
```python
workspace= "./model_dir"
model_path = "gpt-j-6b"
model = AutoModelForCausalLM.from_pretrained(model_path, load_in_4bit=True, use_llm_runtime=False)
model.save_pretrained(workspace)
loaded_model = AutoModelForCausalLM.from_pretrained(workspace)
```
=> [LLM] Save && Load INT4 model on CPU

intel_extension_for_transformers/llm/quantization/nn/modules.py
bug fix
API  not changed
issue description as following, the root cause is tensor.view requests the tensor is contiguous, so add the check, we will correct it if it is not contiguous.
```
File "/dataset/huggingface/modules/transformers_modules/THUDM/chatglm2-6b/7fabe56db91e085c9c027f56f1c654d137bdba40/modeling_chatglm.py", line 640, in forward
layer_ret = layer(
File "/home/changwa1/anaconda3/envs/starcoder/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "/home/changwa1/anaconda3/envs/starcoder/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
return forward_call(*args, **kwargs)
File "/dataset/huggingface/modules/transformers_modules/THUDM/chatglm2-6b/7fabe56db91e085c9c …
```
=> [LLM WOQ] add QuantizedLinearQbits activation contiguous check

intel_extension_for_transformers/llm/runtime/graph/scripts/ci/cpp_graph_inference.sh, intel_extension_for_transformers/llm/runtime/graph/scripts/requirements/baichuan.sh, intel_extension_for_transformers/llm/runtime/graph/scripts/requirements/baichuan.txt, intel_extension_for_transformers/llm/runtime/graph/scripts/requirements/chatglm-6b.sh, intel_extension_for_transformers/llm/runtime/graph/scripts/requirements/chatglm-6b.txt
API not changed.
This dependency is only used if a user wants to run these 3 specific models. Some users (and our tests) do want to use these models which cannot work with newer version of transformers. Users using these 3 models should be aware of this risk and should trust the publisher of these 3 models.
Due to internal regulations, we cannot dismiss [this vulnerability check](https://github.com/intel/intel-extension-for-transformers/pull/1074) and have to add the workaround here.
Ignore security check for model-specific requirements.
No
=> [LLM Runtime] Circumvent dependabot check for chatglm/baichuan/baichuan2

intel_extension_for_transformers/neural_chat/pipeline/plugins/audio/tts_chinese.py
bug fix
centos does not have a glibc version that paddle requires, and causes the UT to crash.
I will implement CN TTS through other paths, as a substitute for paddle, to totally fix this issue. For now we just skip the UT coverage check.
skip UT coverage check
UT
None
=> [NeuralChat] remove coverage check tts cn

intel_extension_for_transformers/neural_chat/pipeline/plugins/audio/tts.py, intel_extension_for_transformers/neural_chat/pipeline/plugins/audio/utils/english_normalizer.py, intel_extension_for_transformers/neural_chat/tests/ci/plugins/audio/test_english_normalizer.py, intel_extension_for_transformers/neural_chat/tests/ci/plugins/audio/test_tts.py
bug fix
there is a random issue in UT that retrieval generate some messy output that TTS cannot correctly convert to speech, I fix that and fix some other issues
UT will not encounter random issues.
UT
None
=> [NeuralChat] Fix tts crash with messy retrieval input and enhance normalizer

intel_extension_for_transformers/neural_chat/requirements.txt, intel_extension_for_transformers/neural_chat/requirements_cpu.txt, intel_extension_for_transformers/neural_chat/requirements_hpu.txt, intel_extension_for_transformers/neural_chat/requirements_pc.txt, intel_extension_for_transformers/neural_chat/requirements_xpu.txt, intel_extension_for_transformers/neural_chat/tests/requirements.txt
bug fix
Fix langchain version issue since langchain upgrade to v0.1.0
NeuralChat can run without error raised.
Pre-CI test.
None.
=> [NeuralChat] Fix langchain version issue since langchain upgrade to v0.1.0

intel_extension_for_transformers/langchain/embeddings/optimized_instructor_embedding.py, intel_extension_for_transformers/langchain/embeddings/optimized_sentence_transformers.py
bug fix 
Fix bug of 'TypeError: _load_auto_model() got an unexpected keyword argument 'trust_remote_code'' caused by SentenceTranformer updated.
CI
No
=> Fix unexpected keyword argument 'trust_remote_code' in embedding

intel_extension_for_transformers/llm/runtime/graph/README.md, intel_extension_for_transformers/llm/runtime/graph/scripts/run.py
- Fix missing documentation in LLM runtime, and a broken link + some typos
- User needs to install the dependencies in requirements.txt, not only in Transformer-based API option but also when running the Straightforward Python script option, otherwise the convert.py throws an error of many missing packages.
- Fix a broken link of Python script option: When clicking on it doesn't take you to the right part in the README.
- Fix typos in run.py script.
N/A
Any HW
N/A
=> Fix missing documentation in LLM runtime, and a broken link + some typos

intel_extension_for_transformers/langchain/embeddings/requirements.txt, intel_extension_for_transformers/neural_chat/pipeline/plugins/caching/requirements.txt, intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/retrieval_agent.py, intel_extension_for_transformers/neural_chat/requirements.txt, intel_extension_for_transformers/neural_chat/requirements_cpu.txt, intel_extension_for_transformers/neural_chat/requirements_hpu.txt, intel_extension_for_transformers/neural_chat/requirements_pc.txt, intel_extension_for_transformers/neural_chat/tests/requirements.txt, workflows/chatbot/demo/docker/Dockerfile
others
Limit sentence-transformers version to 5c838a705c24c2dfd151a71674c99d09d014c1a9. 
Sentence-transformers will release a new version (v2.2.3) soon. We will update the version limit once a new version is released.
CI
NO
=> Limit sentence-transformers version

intel_extension_for_transformers/neural_chat/models/model_utils.py
bug fix
Fix GPT-J model name issue
GPT-J model has model type 'gptj' but it name includes 'gpt-j'.
None.
=> [NeuralChat] Fix GPT-J model name issue

.github/workflows/script/unitTest/run_unit_test_neuralchat.sh, intel_extension_for_transformers/neural_chat/requirements.txt, intel_extension_for_transformers/neural_chat/requirements_hpu.txt, intel_extension_for_transformers/neural_chat/requirements_pc.txt, intel_extension_for_transformers/neural_chat/requirements_xpu.txt, intel_extension_for_transformers/neural_chat/tests/requirements.txt
bug fix
pip install neural_speed from wheel
Now neural_speed can be pip install from wheel.
pre-CI test
None.
=> [NeuralChat] pip install neural_speed from wheel

intel_extension_for_transformers/llm/quantization/utils.py
=> fix of calling is_ipex_available

intel_extension_for_transformers/transformers/modeling/modeling_auto.py
bug fix
No API changed
Change the default value for XPU weight-only quantization
=> Change the default value for XPU weight-only quantization

intel_extension_for_transformers/neural_chat/pipeline/plugins/audio/asr.py
bug fix
latest transformers >=4.37.0 cause error when passing forced_decoder_ids in model.generate
I fix the problem and test that it is compatible with transformers == 4.37.0 as well as 4.36.2
ut
None
=> [NeuralChat] fix latest transformers whisper forced_decoder_ids error

intel_extension_for_transformers/neural_chat/examples/finetuning/multi_modal/llava_utils.py
Bug fix
There's an off by one error in the preprocessor for generating the inputs and targets. [This line](https://github.com/intel/intel-extension-for-transformers/blob/main/intel_extension_for_transformers/neural_chat/examples/finetuning/multi_modal/llava_utils.py#L338) sets the `instruction_len = len(tokenizer_image_token(parts[0], tokenizer)) - 1` but if we do that we get the following mask:
```
ipdb> p target
tensor([ -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
-100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
-100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
-100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
-100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
1579,   297,   272,  3469, …
```
=> [NeuralChat] Fixed off by one error on masking

intel_extension_for_transformers/transformers/modeling/llava_models/llava_arch.py
Bug fix
This PR fixes the problem reported in [#1181](https://github.com/intel/intel-extension-for-transformers/issues/1181). The problem only happens on HPU devices and can be recreated with this simple script:
```python
import torch
import habana_frameworks.torch.core as htcore
import habana_frameworks.torch as htorch
a = torch.ones([10], requires_grad=True).to("hpu")
b = torch.ones([10], requires_grad=True).to("hpu")
c = torch.cat([a, b[0:0]], dim=0)
c.sum().backward()
```
which outputs:
```
Traceback (most recent call last):
File "/intel-extension-for-transformers/intel_extension_for_transformers/neural_chat/examples/finetuning/multi_modal/test.py", line 9, in <module>
c.sum().backward()
File "/usr/local/lib/python3.10/dist-packages/torch/_tensor.py", line 502, in backward …
```
=> [NeuralChat] Fix backprop error for text only examples

intel_extension_for_transformers/llm/quantization/utils.py
for cpu device, if the ipex doesn't install, it will raise error that no module named "ipex"
=> Fix WOQ IPEX condition

intel_extension_for_transformers/neural_chat/examples/finetuning/multi_modal/llava_utils.py, intel_extension_for_transformers/neural_chat/examples/finetuning/multi_modal/train.py
Bug fix
In the train.py code the `pad_token` is set to the `eos_token` [here](https://github.com/intel/intel-extension-for-transformers/blob/main/intel_extension_for_transformers/neural_chat/examples/finetuning/multi_modal/train.py#L222). Because `eos_token`'s are present in every conversation when we calculate the `total_len` of a conversation [here](https://github.com/intel/intel-extension-for-transformers/blob/main/intel_extension_for_transformers/neural_chat/examples/finetuning/multi_modal/llava_utils.py#L322-L323) we basically ignore one token per conversation `int(target.ne(tokenizer.pad_token_id).sum()) == int(target.ne(tokenizer.eos_token_id).sum())` so we have to add in the extra counts by adding `+ len([rou for rou in rounds if rou != ""])`. This in itself isn't bad, but if we …
=> [NeuralChat] Use unk token instead of eos token

intel_extension_for_transformers/neural_chat/server/restful/plugin_audio_api.py
code refine
knowledge id is not needed in TTS router
remove the knowledge id parameter
ut
None
=> [NeuralChat] Remove redundant knowledge id in audio plugin api

intel_extension_for_transformers/neural_chat/examples/finetuning/instruction/README.md, intel_extension_for_transformers/neural_chat/ui/customized/talking_photo/README.md, intel_extension_for_transformers/neural_chat/ui/customized/talkingbot/README.md
Documentation cleanup
Neural Chat UI documentation had 3 broken links, finetuning example README uses the wrong Llama-2 model, should have hf in its name in order to access its config.json
N/A
N/A
None
=> [NeuralChat] Fixed broken links, model name typo

intel_extension_for_transformers/langchain/vectorstores/qdrant.py
bug fix 
Fix qdrant bug caused by langchain_core upgrade: `'ScoredPoint' object has no attribute 'collection_name'`
TODO: `langchain` is limited to 0.0.354, while `langchain_core` is latest version now. Will check and limit `langchain_core`  version in a new PR
CI
No
=> Fix Qdrant bug caused by langchain_core upgrade

intel_extension_for_transformers/neural_chat/chatbot.py, intel_extension_for_transformers/neural_chat/models/deepseek_coder_model.py, intel_extension_for_transformers/neural_chat/models/model_utils.py, intel_extension_for_transformers/neural_chat/requirements.txt, intel_extension_for_transformers/neural_chat/requirements_hpu.txt, intel_extension_for_transformers/neural_chat/requirements_pc.txt, intel_extension_for_transformers/neural_chat/requirements_xpu.txt, intel_extension_for_transformers/neural_chat/tests/nightly/models/test_deepseekcoder.py, intel_extension_for_transformers/neural_chat/tests/requirements.txt
feature
Support deepseek-coder models in NeuralChat
Users can use the deepseek-ai/deepseek-coder models in NeuralChat.
None.
=> [NeuralChat] Support deepseek-coder models in NeuralChat

examples/huggingface/pytorch/text-generation/quantization/requirements.txt, examples/huggingface/pytorch/text-generation/quantization/run_generation.py
1. fix gptq args, args.woq_group_size is different with args.gptq_block_size
2. _commit_hash default is None, but evaluate func need pass the string.
=> Fix text-generation example accuracy test

intel_extension_for_transformers/neural_chat/models/model_utils.py
Bug fix
Resolves: #1267
Error seems to be caused by generation config
https://github.com/huggingface/transformers/issues/25353#issuecomment-1669339754
Setting `pad_token_id=tokenizer.eos_token_id` during the initial definition of `GenerationConfig()` resolves this bug
Quantized model using neuralchat functions should be able to run properly
Run:
```
from intel_extension_for_transformers.neural_chat import build_chatbot, PipelineConfig
from intel_extension_for_transformers.transformers import WeightOnlyQuantConfig
from intel_extension_for_transformers.neural_chat.config import LoadingModelConfig
config = PipelineConfig(model_name_or_path="Intel/neural-chat-7b-v3-1",
optimization_config=WeightOnlyQuantConfig(compute_dtype="int8", weight_dtype="int4_fullrange"), …
```
=> resolve woq quantization error when running neuralchat

intel_extension_for_transformers/llm/quantization/autograd/functions.py, intel_extension_for_transformers/llm/quantization/nn/modules.py, intel_extension_for_transformers/neural_chat/models/model_utils.py, intel_extension_for_transformers/transformers/utils/config.py, tests/CI/test_quantization.py
I add limitation in the python config.py due to kernel only supports asym in some cases( when enable asym , computer_dtype!=int8,weight-type is int, scale-type is fp32)
update other code to auto get scheme.
Here is the local test results.
rtn facebook/opt-1.3b sym
```
python run_generation.py --model facebook/opt-1.3b --woq --woq_weight_dtype "int4_clip" --woq_scheme "asym" --benchmark --batch_size 1
['Once upon a time, there existed a little girl, who liked to have adventures. She wanted to go to places and meet new people, and have fun.\n\nOnce upon a time, there existed a little girl, who liked to have adventures. She wanted to go to places and meet new people, and have']
['Once upon a time, there existed a little girl, who liked to have adventures. She wanted to go to places and meet …
```
=> [LLM] Support WOQ scheme asym

intel_extension_for_transformers/neural_chat/README.md, intel_extension_for_transformers/neural_chat/docs/neuralchat_api.md
documentation
Update openai-python API usage since the library API has upgraded.
Users can use openai-python API to access the server endpoint using latest openai-python library.
Just documentation change, verified the openai-python API usage on local.
None.
=> [NeuralChat] Update openai-python API usage for library API upgrade

intel_extension_for_transformers/neural_chat/requirements.txt
bug fix
Fix IPEX version mismatch with Pytorch issue
ERROR! Intel® Extension for PyTorch* needs to work with PyTorch 2.2.*, but PyTorch 2.1.0+cu121 is found. Please switch to the matching version and run again.
The above issue can be fixed.
None.
=> [NeuralChat] Fix IPEX version mismatch with Pytorch issue

intel_extension_for_transformers/neural_chat/server/restful/textchat_api.py
bug fix
Fix chat history issue, the chat history should be maintained by users. Users pass down all the chat history in 'messages', so neuralchat doesn't need to record all the chat history.
The chat history issue can be fixed.
None.
=> [NeuralChat] Fix chat history issue

examples/huggingface/pytorch/code-generation/quantization/requirements.txt, examples/huggingface/pytorch/code-generation/quantization/run_generation.py, examples/huggingface/pytorch/text-generation/quantization/requirements.txt, examples/huggingface/pytorch/text-generation/quantization/run_generation.py, intel_extension_for_transformers/llm/quantization/utils.py, tests/CI/test_quantization.py, tests/requirements.txt
```
python run_generation.py --model facebook/opt-125m --woq --woq_algo "AUTOROUND" --woq_weight_dtype "int4_clip" --calib_iters 20 --benchmark --batch_size 1
['Once upon a time, there existed a little girl, who liked to have adventures. She wanted to go to places and meet new people, and have fun. When she was a little girl, she liked to go to the movies. She liked to go to the movies. She liked to go to the movies. She']
['Once upon a time, there existed a little girl, who liked to have adventures. She wanted to go to places and meet new people, and have fun. When she was a little girl, she liked to go to the movies. She liked to go to the movies. She liked to go to the movies. She']
```
```
python run_generation.py --model facebook/opt-125m --woq --woq_algo "AUTOROUND" …
```
=> WOQ support autoround algo on cpu device

examples/huggingface/pytorch/language-modeling/quantization/requirements.txt
ticket https://jira.devtools.intel.com/browse/NLPTOOLKIU-1241
transformers requests pytest 8.0.0 but lm-eval will auto request the latest 8.0.2 pytest to install, so fix the pytest version.
if transformers upgrades, we can try to remove the pytest version limit.
the latest version of pytest (>= 8.0.1) have finally deprecated including import_path from _pytest.doctest to _pytest.pathlib, so this import path needs to be updated.
=> Fix clm model with transformers 4.38.1

intel_extension_for_transformers/neural_chat/cli/cli_commands.py
bug fix
Fix finetuning unit test issue
2024-03-12 16:06:20,905 - intel_extension_for_transformers.llm.finetuning.finetuning - INFO - Using data collator of type DataCollatorForSeq2Seq
trainable params: 294,912 || all params: 125,534,208 || trainable%: 0.23492560689115113
2024-03-12 16:06:20,922 - root - ERROR - Exception: '>' not supported between instances of 'str' and 'int'
2024-03-12 16:06:20 [ERROR] neuralchat error: LORA finetuning failed
The finetuning unit test case will not raise any error.
None.
=> [NeuralChat] Fix finetuning unit test issue

intel_extension_for_transformers/neural_chat/examples/finetuning/instruction/README.md
1. support [mistralai/Mixtral-8x7B-v0.1](https://huggingface.co/mistralai/Mixtral-8x7B-v0.1) finetuning with peft/lora on Guadi2, which depends on the PR [optimum-habana/pull/716](https://github.com/huggingface/optimum-habana/pull/716) and [optimum-habana/pull/668](https://github.com/huggingface/optimum-habana/pull/668)
2. enable phi series models training and generation, which depends on this https://github.com/huggingface/optimum-habana/pull/732
=> [NeuralChat] enable mixtral lora finetuning on Gaudi2.

intel_extension_for_transformers/transformers/llm/quantization/nn/modules.py, intel_extension_for_transformers/transformers/llm/quantization/utils.py, intel_extension_for_transformers/transformers/modeling/modeling_auto.py, tests/CI/test_quantization.py, tests/CI/test_weight_only.py
fix #1375 remaining int8 issue.
=> Fix WOQ int8 unpack weight

intel_extension_for_transformers/neural_chat/tests/ci/server/test_askdoc_server.py, intel_extension_for_transformers/neural_chat/tests/ci/server/test_photoai_api.py
bug fix
Fix request.client=None issue using async UT.
fastapi.TestClient.client was set to `None` in 
link: 
- https://github.com/tiangolo/fastapi/discussions/11019
- https://github.com/encode/starlette/pull/2525
UT of test_photoai_api.py and test_askdoc_server.py will pass.
Local tested on SPR.
None
=> [NeuralChat] Fix UT TestClient.client=None issue

examples/huggingface/pytorch/code-generation/quantization/run_generation.py, examples/huggingface/pytorch/text-generation/quantization/run_generation.py, intel_extension_for_transformers/transformers/llm/quantization/utils.py, intel_extension_for_transformers/transformers/utils/config.py
https://github.com/intel/neural-compressor/blob/master/docs/source/quantization_layer_wise.md add layerwise for rtn and gptq woq due to INC limit.
--layer_wise is used to enable layerwise feature
```
python run_generation.py --model facebook/opt-125m --woq --woq_algo "GPTQ" --bits 4 --scheme "asym" --desc_act --blocksize 32 --nsamples 32 --max_input_length 256 --static_groups --layer_wise
```
=> add layerwise for WOQ Rtn&GPTQ

intel_extension_for_transformers/transformers/modeling/modeling_auto.py
New feature.
Add the model_type list for GPTQ
N/A
```python
from transformers import AutoTokenizer
from intel_extension_for_transformers.transformers import AutoModelForCausalLM, GPTQConfig
model_name = "/home/zhenzhong/model/Llama-2-7B-Chat-GPTQ"  # local path to model
woq_config = GPTQConfig(bits=4)   # use AwqConfig for AWQ models, and AutoRoundConfig for AutoRound models
prompt = "Once upon a time, a little girl"
tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
inputs = tokenizer(prompt, return_tensors="pt").input_ids
model = AutoModelForCausalLM.from_pretrained(model_name, quantization_config=woq_config, trust_remote_code=True)
outputs = model.generate(inputs)
print(tokenizer.decode(outputs[0]))
```
N/A
=> [Neural Speed] Add the model_type list for GPTQ

intel_extension_for_transformers/transformers/llm/quantization/utils.py, intel_extension_for_transformers/transformers/modeling/modeling_auto.py, intel_extension_for_transformers/transformers/utils/config.py
due to chatglm and dolly_v2 last layer name are not "lm_head".
we usually don't quant the last linear for WOQ.
https://jira.devtools.intel.com/browse/NLPTOOLKIU-1286
=> Fix woq autoround last layer quant issue

intel_extension_for_transformers/neural_chat/chatbot.py, intel_extension_for_transformers/neural_chat/models/model_utils.py, intel_extension_for_transformers/transformers/llm/quantization/optimization.py
support hackathon
```
from intel_extension_for_transformers.neural_chat import build_chatbot, PipelineConfig
from intel_extension_for_transformers.transformers import RtnConfig
from intel_extension_for_transformers.neural_chat.config import LoadingModelConfig
config = PipelineConfig(model_name_or_path="baichuan-inc/Baichuan2-7B-Chat",
optimization_config=RtnConfig(bits=4, compute_dtype="int8", weight_dtype="int4_fullrange"),
loading_config=LoadingModelConfig(use_neural_speed=False))
chatbot = build_chatbot(config)
response = chatbot.predict(query="Tell me about Intel Xeon Scalable Processors.")
print(response)
```
offline validation pass.
any …
=> support qwen and baichuan with neuralchat ns=False

README.md, examples/huggingface/pytorch/text-generation/quantization/run_generation.py, intel_extension_for_transformers/transformers/llm/evaluation/lm_eval/models/huggingface.py, intel_extension_for_transformers/transformers/modeling/modeling_auto.py, tests/Nightly/test_llm_runtime.py, tests/Nightly/test_neural_speed.py
- fp32 model in, fp32 dtype inference
```python
itrex_model = AutoModelForCausalLM.from_pretrained(model_name, quantization_config=None, use_neural_speed=True, 
trust_remote_code=True)
itrex_generate_ids = itrex_model.generate(inputs.input_ids, do_sample=False, max_new_tokens=100)[0]
```
- fp32 model in, low-bits dtype inference
```python
woq_config=RtnConfig(compute_dtype="int8", weight_dtype="int4", group_size=128)
itrex_model = AutoModelForCausalLM.from_pretrained(model_name, quantization_config=woq_config, use_neural_speed=True,  
trust_remote_code=True)
itrex_generate_ids = itrex_model.generate(inputs.input_ids, do_sample=False, max_new_tokens=100)[0]
```
- low-bits model in, …
=> [Transformers] Refine Model `from_pretrained` When `use_neural_speed`

intel_extension_for_transformers/transformers/modeling/modeling_auto.py
bug fix:
add scale dtype and weight dtype check for quantization config when loading.
no API changed 
scale dtype: we only support [fp32, bf16, fp16], if the scale_dtype doesn't in the support list, we will report the warning log and then use the fp32 as the default scale_dtype.
weight dtype: when bits and weight dtype both in config.json, we higher priority to choice weight_dtype as inference weight datatype.
=> Add scale and weight dtype check for quantization config

.github/workflows/build-container.yaml, .github/workflows/chatbot-finetune-mpt-7b-chat-hpu.yml, .github/workflows/chatbot-finetune-mpt-7b-chat.yml, .github/workflows/chatbot-inference-llama-2-7b-chat-hf.yml, .github/workflows/chatbot-inference-llama-2-7b_70b-chat-hf-hpu.yml, .github/workflows/chatbot-inference-mpt-7b-chat-hpu.yml, .github/workflows/chatbot-inference-mpt-7b-chat.yml, .github/workflows/chatbot-test.yml, .github/workflows/chatbot_finetuning.yml, .github/workflows/cpp-graph-test.yml, .github/workflows/deploy-test.yml, .github/workflows/format_scan.yml, .github/workflows/llm-test.yml, .github/workflows/optimize-test.yml, .github/workflows/probot.yml, .github/workflows/publish.yml, .github/workflows/sparse_lib_CI.yml, .github/workflows/unit-test-engine.yml, .github/workflows/unit-test-kernel.yml, .github/workflows/unit-test-neuralchat.yml, .github/workflows/unit-test-neuralspeed.yml, .github/workflows/unit-test-optimize.yml, .github/workflows/windows-test.yml, intel_extension_for_transformers/neural_chat/ui/gradio/basic/README.md, intel_extension_for_transformers/neural_chat/ui/gradio/basic/requirements.txt
=> move limitation of gradio to readme

intel_extension_for_transformers/neural_chat/docs/notebooks/workshop/01_quickstart_neuralchat.ipynb
Bug Fix to use token latency instead of total inference time to measure performance
The workshop notebook measure total inference time for performance instead of token latency.
change it to use token latency.
use token latency for performance measurement
manually test it on AWS
no
=> Fix to use token latency to measure performance 

examples/huggingface/pytorch/text-generation/quantization/README.md, examples/huggingface/pytorch/text-generation/quantization/run_generation_cpu_woq.py, intel_extension_for_transformers/transformers/llm/quantization/utils.py, intel_extension_for_transformers/transformers/modeling/modeling_auto.py, intel_extension_for_transformers/transformers/utils/config.py, tests/CI/test_weight_only.py
1. add config parameter `use_ipex_cpu` to distinguish qbits and ipex_cpu backend under cpu device.
2. support save and loading following Transformers-likely API, but not optimum format.
3. command and results, the results is close to qbits backend accuracy mentioned in #1535
RTN
```
python run_generation_cpu_woq.py --model facebook/opt-125m --bits 4 --woq --accuracy --batch_size 56 --use_ipex
hf (pretrained=./saved_results,trust_remote_code=False), gen_kwargs: (None), limit: None, num_fewshot: None, batch_size: 56
|    Tasks     |Version|Filter|n-shot|  Metric  | Value |   |Stderr|
|--------------|------:|------|-----:|----------|------:|---|-----:|
|lambada_openai|      1|none  |     0|perplexity|41.0024|±  |1.5290|
|              |       |none  |     0|acc       | 0.3150|±  |0.0065| …
```
=> Support ipex cpu WOQ backend

examples/huggingface/pytorch/code-generation/quantization/requirements.txt, examples/huggingface/pytorch/text-generation/quantization/requirements_GPU.txt, examples/huggingface/pytorch/text-generation/quantization/requirements_cpu_woq.txt, examples/huggingface/pytorch/text-generation/quantization/requirements_sq.txt, examples/huggingface/pytorch/text-generation/quantization/run_generation_cpu_woq.py, intel_extension_for_transformers/transformers/llm/quantization/nn/modules.py, intel_extension_for_transformers/transformers/llm/quantization/utils.py, intel_extension_for_transformers/transformers/utils/config.py, tests/CI/test_quantization.py, tests/requirements.txt
```
external change:
autoroundconfig parameter, use_quant_input  -->  enable_quanted_input
internal change:
seq_len --> seqlen
autoround use autoround package get dataloader, not used with itrex bulit-in
```
please validate base the following message, @XuehaoSun 
INC PR: https://github.com/intel/neural-compressor/pull/1806
AutoRound main branch: https://github.com/intel/auto-round
=> adapt autoround release

examples/huggingface/pytorch/text-generation/quantization/run_generation_cpu_woq.py, intel_extension_for_transformers/transformers/llm/quantization/utils.py, intel_extension_for_transformers/transformers/utils/config.py
update AutoRoundConfig from  `enable_quanted_input` to `disable_quanted_input`,
=> Update WOQ AutoRoundConfig parameter

setup.py
=> Add Habana HPU check in setup.py

intel_extension_for_transformers/transformers/modeling/modeling_auto.py
=> add model_type tinyllama

.github/workflows/unit-test-optimize.yml, tests/requirements.txt
=> Set optimum-intel to 1.16.1

intel_extension_for_transformers/transformers/llm/evaluation/lm_eval/models/huggingface.py
ticket https://jira.devtools.intel.com/browse/NLPTOOLKIU-1383
improve the tokenizer loading like the following code.
```
tokenizer = AutoTokenizer.from_pretrained(
"THUDM/chatglm2-6b", trust_remote_code=args.trust_remote_code
)
tokenizer.saved_pretrained("saved_results")
```
```
tokenizer = AutoTokenizer.from_pretrained(
args.model, trust_remote_code=args.trust_remote_code
)
```
if args.model == "THUDM/chatglm2-6b", it works.
if args.model == "saved_results", it fails.
=> improve lm_eval get chatglm2 tokenizer from local saved files

docs/weightonlyquant.md, examples/.config/pytorch_optimize.json, examples/huggingface/pytorch/code-generation/quantization/run_generation.py, examples/huggingface/pytorch/text-generation/quantization/llm_quantization_recipes.md, examples/huggingface/pytorch/text-generation/quantization/run_generation_cpu_woq.py, examples/huggingface/pytorch/text-generation/quantization/run_generation_gpu_woq.py, examples/huggingface/pytorch/text-generation/quantization/run_tuning.sh, intel_extension_for_transformers/transformers/llm/quantization/nn/modules.py, intel_extension_for_transformers/transformers/llm/quantization/utils.py, intel_extension_for_transformers/transformers/modeling/modeling_auto.py, intel_extension_for_transformers/transformers/utils/config.py, tests/CI/test_weight_only.py, tests/CI/test_weight_only_gpu.py
bug fix
No API changed
Unify the woq config weight_dtype for int4 and fp4 on different devices
Local tested
=> Unify the woq config weight_dtype for int4 and fp4 on different devices

intel_extension_for_transformers/neural_chat/requirements_cpu.txt
bug fix
No API changed
Add a dependency "oneccl_bind_pt" for  Neural_chat on CPU device
Issue report:
https://github.com/intel/intel-extension-for-transformers/issues/1574
Run Neural_chat on the CPU device successfully with IPEX.
Local tested
=> Add a dependency for  Neural_chat on CPU device

intel_extension_for_transformers/transformers/utils/utility.py
bug fix.
ticket [[NLPTOOLKIU-1366] [chatglm-6b][SQ]RuntimeError: quantize_tensor_per_channel_affine expects a Float Tensor, got Half - IT JIRA (Supports IC/ITS Data) (intel.com)](https://jira.devtools.intel.com/browse/NLPTOOLKIU-1366)
=> Improve SQ model restored from json

requirements.txt
set setuptools==69.5.1
To avoid `ImportError: cannot import name 'packaging' from 'pkg_resources'` when use setuptools>=70
=> limit setuptools version

examples/huggingface/tensorflow/language-modeling/quantization/README.md
Typo
Removed an extra space from two shell commands examples
Not applicable
Not applicable
Not applicable
=> Fix typo at README.md

intel_extension_for_transformers/neural_chat/models/base_model.py
https://github.com/intel/intel-extension-for-transformers/security/code-scanning/56
https://github.com/intel/intel-extension-for-transformers/security/code-scanning/55
https://github.com/intel/intel-extension-for-transformers/security/code-scanning/54
https://github.com/intel/intel-extension-for-transformers/security/code-scanning/53
=> solve codescan#53-56

intel_extension_for_transformers/transformers/modeling/modeling_auto.py
bug fix
No API changed
Fixed issue of loading woq model for intel GPU
load woq model successfully for intel GPU device. 
Local tested
=> Fixed issue of loading woq model for intel GPU

intel_extension_for_transformers/qbits/__init__.py
feature or bug fix or documentation or others: bug fix
GPU version itrex will not build qbits.so but try to import it in qbits/__init__.py, this pr target to fix this bug.
any library dependency introduced or removed: NO
=> disable qbits lib import when using gpu version itrex

intel_extension_for_transformers/transformers/llm/evaluation/models.py, intel_extension_for_transformers/transformers/modeling/modeling_auto.py, intel_extension_for_transformers/transformers/utils/utility.py
to adapt ipex 2.3.
1.5 release bug fix. 
[NLPTOOLKIU-1394]](https://jira.devtools.intel.com/browse/NLPTOOLKIU-1394)
=> Fix  SQ bloom

.github/workflows/script/install_binary.sh, .github/workflows/script/unitTest/env_setup.sh, intel_extension_for_transformers/qbits/__init__.py, setup.py
feature or bug fix or documentation or others: bug fix
JIRA ticket: https://jira.devtools.intel.com/browse/NLPTOOLKIU-1399
as there is no `xpu._is_compiled()` function in 2.2.0 torch, append GPU postfix to `itrex.__version__`  for multi-torch-version xpu available checking. 
the expected behavior that triggered by this PR: xpu detection works well on multi-version torch
how to reproduce the test (including hardware information) 64-core emr
any library dependency introduced or removed: no
=> fix xpu version itrex detect

.github/workflows/script/install_binary.sh, .github/workflows/unit-test-optimize.yml, examples/huggingface/pytorch/text-generation/quantization/requirements_sq.txt, tests/requirements.txt
=> remove optimum-intel version limit

examples/huggingface/pytorch/code-generation/quantization/Dockerfile-multiple, examples/huggingface/pytorch/code-generation/quantization/requirements.txt, examples/huggingface/pytorch/text-generation/quantization/requirements_GPU.txt, examples/huggingface/pytorch/text-generation/quantization/requirements_sq.txt, tests/requirements.txt
fix optimum-intel version due to the fixed PR (remove INC 1.x dependence of optimum-intel) is merged but not released.
so fix the commit first, will remove the limitation util the optimum-intel next release.
=> Fix optimum-intel version for INC v3.0

docker/Dockerfile_chatbot
https://ubuntu.com/security/CVE-2024-6387
=> Apply regreSSHion mitigation

intel_extension_for_transformers/qbits/dispatcher/include/bestla_weightonly_dispatcher.hpp, intel_extension_for_transformers/qbits/dispatcher/include/dispatcher_utils.hpp, intel_extension_for_transformers/qbits/dispatcher/src/bestla_packq_impl.cpp, intel_extension_for_transformers/qbits/dispatcher/src/bestla_weightonly_dispatcher.cpp
=> qbits support f4 weight repack

examples/huggingface/pytorch/code-generation/quantization/README.md, examples/huggingface/pytorch/code-generation/quantization/run_benchmark.sh, examples/huggingface/pytorch/code-generation/quantization/run_generation.py, examples/huggingface/pytorch/code-generation/quantization/run_generation_cpu_woq.py, examples/huggingface/pytorch/code-generation/quantization/run_generation_sq.py, examples/huggingface/pytorch/code-generation/quantization/run_tuning.sh, examples/huggingface/pytorch/text-generation/quantization/run_generation_cpu_woq.py, examples/huggingface/pytorch/text-generation/quantization/run_generation_gpu_woq.py, examples/huggingface/pytorch/text-generation/quantization/run_generation_sq.py, intel_extension_for_transformers/tools/utils.py, intel_extension_for_transformers/transformers/modeling/modeling_auto.py, intel_extension_for_transformers/transformers/utils/__init__.py, intel_extension_for_transformers/transformers/utils/utility.py, tests/CI/test_quantization.py
=> improve SQ/WOQ examples

.github/workflows/unit-test-optimize.yml, examples/huggingface/pytorch/code-generation/quantization/requirements.txt, examples/huggingface/pytorch/text-generation/quantization/requirements_GPU.txt, examples/huggingface/pytorch/text-generation/quantization/requirements_cpu_woq.txt, intel_extension_for_transformers/transformers/llm/quantization/utils.py, tests/CI/test_quantization.py, tests/CI/test_weight_only.py, tests/requirements.txt
=> Adapt INC autoround changes

examples/huggingface/pytorch/text-generation/quantization/run_generation_gpu_woq.py, intel_extension_for_transformers/transformers/llm/quantization/utils.py, intel_extension_for_transformers/transformers/modeling/modeling_auto.py, intel_extension_for_transformers/transformers/utils/config.py
=> Adapt quant lm head

.github/workflows/script/unitTest/run_unit_test_optimize.sh, .github/workflows/unit-test-optimize.yml
=> Fix intel tbb

examples/huggingface/pytorch/text-generation/quantization/run_generation_cpu_woq.py, intel_extension_for_transformers/transformers/llm/quantization/utils.py, intel_extension_for_transformers/transformers/utils/config.py
=> Add `use_mse_search` to GPTQ Config

intel_extension_for_transformers/transformers/modeling/modeling_auto.py, intel_extension_for_transformers/transformers/utils/config.py
=> fix int8 skip module config

examples/huggingface/pytorch/text-generation/quantization/llm_quantization_recipes.md
=> Update LLM recipes to align INC 3.0

intel_extension_for_transformers/transformers/llm/quantization/utils.py, intel_extension_for_transformers/transformers/modeling/modeling_auto.py, tests/requirements.txt
=> Adapt `INCWeightOnlyLinear` 
